### ISSUE TITLE
Music Mode Progress Bar hang + opening position

### ISSUE THREAD

**Issue by Jae0143** [iina/iina#4157] opened 2023-01-04 01:49 UTC
**System and IINA version:**

- macOS  13.1
- IINA  1.3.1 Build 133

**Expected behavior:**
I expect IINA to start around center of screen, and progress bar to continue in music mode while audio is playing. 

**Actual behavior:**
progress bar gets stuck after 2-3 seconds, and starts moving again when i pause and press continue button again. Weirdly, the audio continues to play, even when the progress bar isn't moving. Also, iina opens at the bottom of the screen when in music mode. 

<details>
<summary><b>Crash report:</b></summary>

```
```
</details>

<br>

<details>
<summary><b>mpv log:</b></summary>

```
```
</details>

<br>

**Steps to reproduce:**

- [ ] MPV does not have this problem.

**How often does this happen?**
everytime I open mp3

**Comment by low-batt** [comment] 2023-02-07 01:36
This is the problem reported in issue #4051. That regression is fixed by changes in PR  #4087. That PR is in review.

I'm going to mark this as a duplicate of #4051.

**Closed as not planned** 2023-03-24 12:20 UTC
Labels: other: duplicate
