### ISSUE TITLE
MAC CRASH REPORT REPORT pops up every time closing/quitting iinna

### ISSUE THREAD

**Issue by soundiz** [iina/iina#4208] opened 2023-02-02 17:36 UTC
MAC CRASH REPORT REPORT pops up every time closing/quitting iinna

happens every time quitting iina.

MAC MINI M1
VENTURA 13.2 PUBLIC

**Comment by low-batt** [comment] 2023-02-02 17:53
Without the crash report I have to guess what might be going wrong based on the description. If this is happening when quitting while in full screen mode then it is very likely this is a duplicate of issue #4020. There is a fix for that problem waiting to be reviewed and merged.

If the crash is happening when quitting while not in full screen mode then please capture and post the crash report.

**Closed as completed** 2023-03-25 15:27 UTC
