### ISSUE TITLE
Zoom In more than 100%

### ISSUE THREAD

**Issue by LeonardoGentile** [iina/iina#3873] opened 2022-07-14 10:37 UTC
Hello,
not a bug, just a simple question: Is there a way to zoom-in more than a 100%? 

For example to see a particular detail of the video, even if that mean we don't have the best of the sharp resolution. 
Using the standard 2 finger pinch stops at 100% of the screen resolution, I'd like to continue to zoom-in after that. Is that possible anyhow?

Thanks 👍

**Comment by svobs** [comment] 2022-10-26 03:33
Duplicate of #3208

**Closed** 2024-06-24 13:46 UTC
Labels: other: duplicate
