### ISSUE TITLE
HDR doesn't seem to work if playing via URL

### ISSUE THREAD

**Issue by sunflsks** [iina/iina#3875] opened 2022-07-17 01:27 UTC
macOS 12.4, IINA 1.3.0 Build 132

**Expected behavior:**
Whenever playing a video through a URL (such as a direct HTTP MPV link, a youtube URL, etc), the option to playback in HDR is enabled for HDR content.

**Actual behavior:**
This is not the case, and the HDR toggle switch is greyed out.

**Steps to reproduce:**
Try to play any HDR URL through IINA, and the option to display the content in HDR will be greyed out.

[Here is the MPV log.](https://github.com/iina/iina/files/9126873/mpv.log), and [here is the IINA log](https://github.com/iina/iina/files/9126877/iina.log)

**Comment by sunflsks** [comment] 2022-07-17 17:15
I did some looking, and it seems this is an MPV issue, so I'll close this for now.

**Comment by low-batt** [comment] 2022-07-17 23:43
What was the mpv issue that seemed like it was the cause? We always want to know if mpv also shows the problem as that means the fix has to be made by that project and an issue needs to be posted with that project. Even when that is the case it is still a valid issue for IINA as IINA is failing too. It is desirable for the IINA project to be aware of such "upstream" issues as it can be a factor when IINA is deciding if it should upgrade the version of libmpv it is using. In this particular case this does not appear to be a mpv issue.

I tried playing the YouTube video "COSTA RICA IN 4K 60fps HDR (ULTRA HD)" in IINA 1.30 by opening the URL. IINA played the video in HDR on my M1 MacBook Pro.

Possibly this is a duplicate of the problem discussed in issue #3806, "Will M1 macbook air get iina HDR support anytime soon?". Although that sounds like some sort of problem related to that particular kind of MacBook, what it proved to be is a problem with IINA randomly failing to enable HDR for a video. There is a thread race condition in the code that determines if HDR should be enabled and depending upon timing IINA may fail to activate HDR.

If that does not sound like what you are encountering, we can take a closer look into the problem.

**Closed** 2022-07-18 20:02 UTC

**Comment by low-batt** [comment] 2022-07-18 20:17
Thank you for responding and confirming this is a duplicate of #3806.

You correctly traced the problem to the offending code. Depending upon thread timing that property may or may not be available when IINA checks it. That might be more likely to occur when streaming. It is IINA's responsibility to listen for changes to that property, so this is an IINA issue. It is a priority to merge the fix for this that is in IINA+ in the upcoming IINA maintenance release.
