### ISSUE TITLE
The spacebar key (resume the playback) stops working after the video has ended in IINA 1.3.3. 

### ISSUE THREAD

**Issue by EugeneTarasenko** [iina/iina#4692] opened 2023-11-16 03:00 UTC
In IINA 1.3.3, when the video reaches its end, pressing the spacebar does nothing, although it should restart the video playback.

In version 1.3.2, the spacebar key works fine, the playback of a video restarts.

**Comment by EugeneTarasenko** [comment] 2023-11-16 03:13
Duplicate of #4562

**Comment by low-batt** [comment] 2023-11-16 20:24
Thanks for pointing out the other issue. This is indeed a duplicate of that issue. As this is a regression it is a high priority to fix.

**Closed as completed** 2024-06-24 13:14 UTC
Labels: other: duplicate
