### ISSUE TITLE
Artifacts in video HEVC 10 bit (in hardware mode).

### ISSUE THREAD

**Issue by Acerbicus** [iina/iina#2468] opened 2019-05-26 06:14 UTC
**System and IINA version:**

- macOS 10.14.5
- IINA 1.0.3

**Expected behavior:**
When playing video.

**Actual behavior:**
Artifacts in video HEVC 10 bit (in hardware mode).

**IINNA** 👎
![IInna](https://user-images.githubusercontent.com/32012394/58600352-00630600-828d-11e9-9513-f9b0273c267b.jpg)

**Movist** 👍
![Movist](https://user-images.githubusercontent.com/32012394/58600366-0953d780-828d-11e9-958c-d1a23d5755a0.jpg)

<br>

**Steps to reproduce:**
Play video.

**Comment by alejx** [comment] 2019-05-29 10:43
Decoding issues are always likely to be upstream issues. Duplicate of #2255, also https://github.com/mpv-player/mpv/issues/6369.

**Closed** 2024-06-22 00:17 UTC
Labels: other: duplicate, upstream
