### ISSUE TITLE
Import only video type files when open folder.

### ISSUE THREAD

**Issue by davidkolesom** [iina/iina#4813] opened 2024-02-10 15:20 UTC
I have issue when opening folder from iina, its importing all type of kind/type of files (picture, document, etc).

Please make an option to import video type only.

Thanks.

**Comment by low-batt** [comment] 2024-02-11 03:31
That IINA importing all kinds of files in a folder is not a feature, it is a recently introduced regression reported in issue #4548. This defect was intended to be fixed in 1.3.4, but that release had to be rushed due to an externally imposed end of year deadline. Quite a few planned fixes were not completed in time. 

A follow up release is planned to address the defects that missed the deadline. This particular problem has already been fixed in the current development version of IINA. Considerable progress has been made on the follow up release, but there are still a few issues that need to be resolved.

**Closed as completed** 2024-06-24 13:42 UTC
Labels: other: duplicate
