### ISSUE TITLE
RTL causes icons to overlap with the text in the Quick Settings tabs

### ISSUE THREAD

**Issue by ShlomoCode** [iina/iina#4925] opened 2024-05-10 02:40 UTC
**System and IINA version:**

- macOS 14.4.1
- IINA 1.3.4 + PR #4922

**Expected behavior:**

The icons do not overlap with the label text in right-to-left languages such as Arabic and Hebrew.

**Actual behavior:**

Currently IINA does not support any right-to-left languages. However PR #4922 allows Hebrew. If you build IINA with this pull request and set Hebrew as the language then the tabs labels in IINA quick settings overlap the labels. (see screenshots below)

<details>
<summary><b>Screenshots:</b></summary>

![CleanShot 2024-05-10 at 05 18 48@2x](https://github.com/iina/iina/assets/78599753/9d2cb25c-efd6-4a39-a582-59ddf284f688)
![CleanShot 2024-05-10 at 05 23 59@2x](https://github.com/iina/iina/assets/78599753/525e37ab-f5d9-4832-bcda-713f19e6176b)

</details>

**Steps to reproduce:**

- Open the IINA project in Xcode
- Under the `Product` menu open the Scheme menu and select `Edit Scheme…`
- Click on the `Options` tab
- Scroll down to the `App Language` setting
- In the pull down select `Right-to-Left Pseudolanguage` near the end of the list
- Start IINA running under Xcode
- Open Quick Settings
- Notice that the icons overlap the text

However, only two of the 3 tabs seem to overlap. It might help with the investigation.

- [x] MPV does not have this problem.

mpv does not support localization.

**How often does this happen?**

Every time.

**Comment by low-batt** [comment] 2024-05-10 02:42
I will look into this.

**Comment by low-batt** [comment] 2024-05-10 19:34
These are buttons that have an image and a title. The buttons are configured with `Image Hugs Title`. The problem is that the images are not centered:
![video](https://github.com/iina/iina/assets/86170219/59f7eeb9-8479-46e3-8f30-1ef02abe034b)
![audio](https://github.com/iina/iina/assets/86170219/04111004-a9fb-47d2-b1de-99de41af4e59)
![subtitles](https://github.com/iina/iina/assets/86170219/81019ce6-b255-4dc8-be1e-a08540c4b880)

In addition the alignment is not uniform between the images. This is why when reversed with an RTL language the `SUBTITLES` button has a larger gap between the image and the title compared to the other tabs.

One solution would be to create a second set of images for when the title is left of the image.

One of the IINA developers who are able to create images will need to fix this issue.

**Comment by ShlomoCode** [comment] 2024-05-29 00:34
ping @lhc70000

**Comment by uiryuu** [comment] 2024-05-29 02:06
![image](https://github.com/iina/iina/assets/20237141/99afc0a6-4f45-4c69-a2ce-b954cdb94b5b)
I don't observe overlaps here (top is RTL pseudolanguage, bottom is English). I've also tried in Hebrew and also didn't have overlaps. Is the issue already fixed in develop?

**Comment by ShlomoCode** [comment] 2024-05-29 02:22
It looks exactly like the screenshots above
![CleanShot 2024-05-29 at 05 17 40@2x](https://github.com/iina/iina/assets/78599753/70e7d7bd-20d3-401a-9fef-ca21c7ddf4ad)
![CleanShot 2024-05-29 at 05 16 39@2x](https://github.com/iina/iina/assets/78599753/c1d301d3-1ef4-4bf7-b9a1-257128906a38)
Can you upload a screenshot with Hebrew?

**Comment by lhc70000** [comment] 2024-05-29 03:33
Fixed in 5728044.

**Closed as completed** 2024-07-12 03:07 UTC
Labels: bug, progress: fixed/implemented, feature: ui/ux, type: localization, priority: high
