### ISSUE TITLE
Preferences' first item is too close to the top

### ISSUE THREAD

**Issue by Sun0613** [iina/iina#4100] opened 2022-11-27 09:46 UTC
**System and IINA version:**

- macOS 10.15.7
- IINA 1.3.1

**Expected behavior:**
In Ventura , it looks right:
<img width="808" alt="截屏2022-11-27 17 22 27" src="https://user-images.githubusercontent.com/46019412/204128793-bc4094e4-9d29-411f-9630-5bdf45626bb1.png">

**Actual behavior:**
In Catalina , it looks like :

<img width="856" alt="截屏2022-11-27 下午5 24 59" src="https://user-images.githubusercontent.com/46019412/204128772-1b05eff2-c567-4e11-b957-956c7563ac8c.png">

<details>
<summary><b>Crash report:</b></summary>

```
```
</details>

<br>

<details>
<summary><b>mpv log:</b></summary>

```
```
</details>

<br>

**Steps to reproduce:**

- [ ] MPV does not have this problem.

**How often does this happen?**
1.3.1 is not correct,1.3.0 is fine

**Comment by low-batt** [comment] 2022-11-27 15:15
Reproduced for me using my MacBook Air running macOS 10.15.7.

**Comment by svobs** [comment] 2022-11-30 15:05
@low-batt I think I may have solved this but I don't have access to anything but Ventura. Can you try building PR #4107 and let me know if it works?

**Comment by low-batt** [comment] 2022-12-01 04:50
See my comments in the PR. This issue is fixed, but I have a couple of concerns.

**Comment by low-batt** [comment] 2023-03-12 20:12
The fix for this issue has been merged into the IINA `develop` branch. GitHub [automatically closed](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue) the linked issue in reaction to the merge. I am reopening this issue until the fix is available in an official release of IINA so that users intending to report this problem can easily locate this existing report. Once the fix for this issue has been included in an official release this issue will be closed.

Should you wish to confirm the fix is working and do not have the ability to build IINA from the sources in the `develop` branch, at some point a new unsigned [nightly build](https://nightly.iina.io/) will be available for download. If you encounter a defect in a nightly build that has not been reported please enter an issue for it and be sure to indicate the problem was found in a nightly build.

The ability to disable this GitHub automatic closing action has been requested by GitHub users (discussions [#23476](https://github.com/orgs/community/discussions/23476) and [#17308](https://github.com/orgs/community/discussions/17308) for example), but so far GitHub has not implemented a way to control this behavior.

**Comment by svobs** [comment] 2023-03-12 23:02
> The fix for this issue has been merged into the IINA develop branch. GitHub [automatically closed](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue) the linked issue in reaction to the merge. I am reopening this issue until the fix is available in an official release of IINA so that users intending to report this problem can easily locate this existing report. Once the fix for this issue has been included in an official release this issue will be closed.

@low-batt is this what the `progress: fixed/implemented` label is for? Would maybe changing the wording to `progress: fixed in nightly builds` (or something) be clearer?

**Comment by low-batt** [comment] 2023-03-13 00:15
Yes, the label `progress: fixed/implemented` (not created by me) means the issue has been fixed (bug) or implemented (feature) in the `develop` branch.

This does not mean it is available in a [nightly build](https://nightly.iina.io/). If you check that page right now you will see the latest build is from 2022-12-02. I'd have to ask the team about the status of the build server as to why that is. This is the reason my post above says _at some point_ when discussing the nightly build.

GitHub labels do have an associated description field. If you look at the `bug: hig` label that I created you will see a description. A few of the other IINA labels have descriptions. So that is one place to say more about this label. Trouble is that field is pretty short.

I started writing a document about submitting issues. Just been too busy to finish it. That might be a good place to discuss this convention.

**Comment by svobs** [comment] 2023-03-13 00:58
I see. Not really a huge deal, especially if there's lots of red tape to change it.

Didn't notice there's no nightly build yet! Though to be fair it looks like the build server is just now reaching nighttime, so I will keep my fingers crossed.

**Comment by low-batt** [comment] 2024-01-02 20:35
This is fixed in the released version of IINA.

**Closed as completed by low-batt** 2024-01-02 20:35 UTC
Labels: progress: fixed/implemented, bug: regression
