### ISSUE TITLE
Mkv crashes on 1.0.5 but the same mkv working with VLC

### ISSUE THREAD

**Issue by telepati** [iina/iina#2709] opened 2020-01-11 02:33 UTC
It could be a bug. When I drag the mkv file to IINA its directly crashes. It gives me a crash report. I am using the latest IINA on Catalina 10.15.2. I attached the all crash reports. BTW same mkv working with VLC I test it.
[Crash Reports.zip](https://github.com/iina/iina/files/4048882/Crash.Reports.zip)

**Comment by tsialex** [comment] 2020-01-11 11:34
You have the same EXC_BAD_INSTRUCTION (SIGILL) as my issue #2696. Could you please post the result of the command below?
`$ /usr/sbin/system_profiler -micro 2> /dev/null`

**Comment by saagarjha** [comment] 2020-01-11 11:40
The first crash report has that information, luckily, so there's no need to gather a system profile manually. The code is failing on `pcmpgtq`, a SSE4.2 instruction; the Penryn core in the iMac only does SSE4.1. Closing as a duplicate of #2696.

**Closed by saagarjha** 2020-01-11 11:40 UTC

**Comment by tsialex** [comment] 2020-01-11 11:47
I looked at 4 crash reports before asking and none had the system profiler info, now that I checked all, only IINA_2020-01-11-033358_iMac have it. 

Like me, it's from an unsupported Mac. ;)
