### ISSUE TITLE
iina无法识别到mp3的内嵌字幕 如irc srt 之类 而win上的potplayer却可以

### ISSUE THREAD

**Issue by 3345730458** [iina/iina#4628] opened 2023-09-24 04:34 UTC
**System and IINA version:**

- macOS 
- IINA 

**Expected behavior:**

**Actual behavior:**

<details>
<summary><b>Crash report:</b></summary>

```
```
</details>

<br>

<details>
<summary><b>mpv log:</b></summary>

```
```
</details>

<br>

**Steps to reproduce:**

- [ ] MPV does not have this problem.

**How often does this happen?**

**Comment by uiryuu** [comment] 2024-06-24 13:23
Duplicate of #4699

**Closed as not planned by uiryuu** 2024-06-24 13:23 UTC
