### ISSUE TITLE
Cannot log in to opensubtitles.org

### ISSUE THREAD

**Issue by adamlogan** [iina/iina#4754] opened 2024-01-06 23:43 UTC
**System and IINA version:**

- macOS 14.2.1 (23C71)
- IINA version: 1.3.4 Build 140

**Expected behavior:** To remain logged into opensubtitles.org between software updates. To be able to log into opensubtitles.org.

**Actual behavior:** I was kicked out of opensubtitles.org and could not log back in despite trying to use email address as username, username as username, and password from password manager. I was able to log into the opensubtitles.org webapp via web-browser fine. I see opensubtitles.org has implemented a captcha, I suspect this is why I can no longer login with just username & passcode anymore with inna. Since inna doesn't provide a way to answer the captcha, we cannot authenticate and establish a connection. inna will need to allow for answering captchas or communicate with opensubtitles.org to figure out an authentication solution that works.

**Steps to reproduce:** Log out of opensubtitles.org. Log in to opensubtitles.org..

**How often does this happen?** In perpetuity.

**Comment by low-batt** [comment] 2024-01-07 13:48
@adamlogan Sorry for the trouble!

Open IINA's settings panel and click on the `Subtitles` tab and scroll down to the `Online Subtitles` section and look really closely at the `Download subtitles from` setting. In IINA 1.3.4 it will not be set to `opensubtitles.org`. Support for that site was removed because Open Subtitles announced the API endpoint would be shutdown at the end of 2023.

Open Subtitles [opensubtitles.org](https://www.opensubtitles.org/) is being rebuilt as [opensubtitles.com](https://www.opensubtitles.com/). They have finally reached the stage where they have mandated that applications switch to the new site. IINA 1.3.4 automatically switched the `Download subtitles from` to `opensubtitles.com` since there was no reason to preserve compatibility with the `.org` site with the API being shutdown.

The transition to the `.com` site is not automatic for users with Open Subtitles accounts. Open Subtitles is unable to migrate user accounts from `.org` to `.com`. Users must use the Open Subtitles import mechanism to bring their account over to the new site. See the closed IINA issue #3920 for details on this.

Thus the reason why login is failing is because IINA is trying to log into the `.com` site using your `.org` account credentials. That will not work until your account has been imported into the new site.

Also take note of issue #4749. That issue reports the need to improve the search results from the `.com` site. That problem is a high priority and will be fixed in the next release of IINA.

Sorry about all this, but IINA was required to transition to the new site.

**Comment by adnan-smlatic** [comment] 2024-06-08 12:10
I've encountered this same issue, but even after creating an account on .com it now just says "Network error"

**Comment by low-batt** [comment] 2024-06-08 14:19
Open Subtitles servers are sometimes overloaded. I just tried it and it worked for me. If it is still failing for you please attach a log file. To enable logging follow these instructions:
- Start IINA
- Click on  `Settings…` under the `IINA` menu
- The settings panel appears
- On the left side of the panel click on `Advanced`
- Slide the `Enable advanced settings` toggle button to be on (blue)
- Click on the checkbox `Enable logging to file` 
- Confirm the settings panel looks like the screenshot below
- **Restart IINA** to activate logging

![enable-logging](https://github.com/iina/iina/assets/86170219/7474c18c-68bb-4e39-84fe-9c8abe4e68b1)

Once IINA has restarted, try downloading subtitles to reproduce the problem. Then:
- Click on  `Settings…` under the `IINA` menu
- The settings panel appears
- On the left side of the panel click on `Advanced`
- Click on `Open log directory`
- A new `Finder` window appears containing the logs for this session
- **Quit IINA** to complete the log files

The `Finder` window contains two files, `iina.log` and `mpv.log`. To attach the log files to this issue, drag-n-drop them from the `Finder` window to the `Leave a comment` section below. Include both the `iina.log` and the `mpv.log`

The log files can also be accessed using [Terminal](https://support.apple.com/guide/terminal/welcome/mac) as shown here:
```bash
low-batt@gag com.colliderli.iina$ pwd
/Users/low-batt/Library/Logs/com.colliderli.iina
low-batt@gag com.colliderli.iina$ ls
2022-10-04-17-57-15_jVrbWy
low-batt@gag com.colliderli.iina$ cd 2022-10-04-17-57-15_jVrbWy
low-batt@gag 2022-10-04-17-57-15_jVrbWy$ ls
iina.log	mpv.log
low-batt@gag 2022-10-04-17-57-15_jVrbWy$ 
```

With logging enabled IINA creates a new log directory each time it is started. If accessing the logs using `Terminal` be sure to obtain them from the latest log directory.

**DO NOT FORGET** to disable logging once you have obtained log files for the problem being investigated. IINA does not restrict the size of log files or delete old logs. If you leave logging enabled the logs will continue to accumulate.

**Comment by adnan-smlatic** [comment] 2024-06-08 16:51
@low-batt Thank you for such a detailed response. I started following your steps, and then it randomly started working, so it seems to have been just an Open subtitles issue and not IINA related.

**Comment by low-batt** [comment] 2024-06-08 20:57
Glad to hear it is now working!

The public Open Subtitles servers can get overloaded. Open Subtitles has a separate set of servers for users with VIP accounts.

Due to trouble in the past with failures that could not be reproduced IINA now has extensive logging in this area. If anyone encounters failures trying to download subtitles with a log file we can tell you exactly what happened.

**Comment by lhc70000** [comment] 2024-06-08 22:33
Closing as resolved.

With IINA 1.3.5, you may also try the plugin version with better user interface, customized search options and VIP server support:

- Enable the plugin system by running this command in terminal: `defaults write com.colliderli.iina iinaEnablePluginSystem -bool YES`, then restart IINA
- In Settings - Plugins, choose "Install from GitHub" and enter `iina/plugin-opensub`.
- After the plugin is installed, select "OpenSubtitles - OpenSubtitles" as the default subtitle downloader.

If you gave it a try and found issues or suggestions, please let us know. Any feedback would be appreciated.

**Closed as completed by lhc70000** 2024-06-08 22:33 UTC

**Comment by o7th** [comment] 2024-09-23 20:10
[iina.log](https://github.com/user-attachments/files/17103603/iina.log)
[mpv.log](https://github.com/user-attachments/files/17103604/mpv.log)

**Comment by o7th** [comment] 2024-09-23 20:14
[iina.log](https://github.com/user-attachments/files/17103687/iina.log)
[mpv.log](https://github.com/user-attachments/files/17103688/mpv.log)

**Comment by low-batt** [comment] 2024-09-23 20:37
@o7th Have you migrated your account from `opensubtitles.org` to `opensubtitles.com` as explained in [this comment](https://github.com/iina/iina/issues/3920#issuecomment-1774181503)?

I took a quick look at the IINA log file you posted. It is very short and does not show a file being opened or an attempt to download subtitles. Both logs look like what you might see if you just started IINA and grabbed the logs at that point. 

If you have migrated your account then it is expected that you can not log in. If that does not explain the problem then start IINA, open a file, try to download subtitles. Then quit IINA. The IINA log should be long and contain messages showing the attempt to conntect to Open Subtitles. Post that log file here and I will see what it tells us.
