### ISSUE TITLE
Wrong file loop UI indicator

### ISSUE THREAD

**Issue by huangyxi** [iina/iina#4591] opened 2023-08-17 08:11 UTC
- macOS 13.4.1
- IINA 1.3.3 Build 138

**Expected behavior:**
1. Open one file `A` (.mp3 file), and check the file loop mode (Playback -> File Loop)
2. Open another file `B` (also mp3 file), the playback file loop status could be either enabled (inherited from `A`) or disabled (by default). But whatever the file loop status of `B` is, the status should synchronize between the UI and actual behavior.

**Actual behavior:**
1. Quit IINA using `cmd+Q`
2. Open a mp3 file `A` music in IINA (from Finder)
3. Enable the file loop mode for `A`
4. Keep `A` in background
5. Open another mp3 file `B` in IINA (from Finder)
6. **Although the UI indicates that the file loop is enabled for B, it does not really loop back after playback completion**

**How often does this happen?**
Always

**Comment by low-batt** [comment] 2023-08-18 16:53
Thank you for reporting this problem. Extra thanks for taking the time to provide the really clear instructions for reproducing.

The root cause of the problem has to do with failing to locate the correct player associated with a mini-player window.  So the problem affects more than the status shown for file loop.

**Comment by huangyxi** [comment] 2023-08-21 02:43
Thank you very much for your commitment to this project. I am eagerly anticipating the release of the new version of IINA.

**Comment by low-batt** [comment] 2023-12-16 18:27
The fix for this issue has been merged into the IINA `develop` branch. GitHub [automatically closed](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue) the linked issue in reaction to the merge. I am reopening this issue until the fix is available in an official release of IINA so that users intending to report this problem can easily locate this existing report. Once the fix for this issue has been included in an official release this issue will be closed.

**Comment by low-batt** [comment] 2024-01-01 20:45
This has been fixed in IINA 1.3.4.

**Closed as completed by low-batt** 2024-01-01 20:45 UTC
Labels: bug, progress: fixed/implemented, priority: high
