### ISSUE TITLE
Subtitle blur option blurs text instead of background

### ISSUE THREAD

**Issue by agnesnutter** [iina/iina#4254] opened 2023-03-09 20:59 UTC
**System and IINA version:**

- macOS 13.2.1 (22D68)
- IINA 1.3.1 Build 133

**Expected behavior:**
The video behind the subtitles will become blurred.

**Actual behavior:**
The subtitle text becomes blurred.

**Steps to reproduce:**
1. Set **Settings… > Subtitle > Text Subtitles > Advanced > Blur** to a value > 0.
2. Play a video with subtitles.

**How often does this happen?**
100%

**Comment by low-batt** [comment] 2023-03-10 02:47
IINA relies upon a library from the  [mpv](https://mpv.io/) project for audio/video playback. Some subtitle features are provided directly by IINA, but rendering subtitles into the video, which is what this issue is about, is provided by mpv.

The IINA subtitles setting in question, `Blur` is tied to the mpv option [sub-blur](https://mpv.io/manual/stable/#options-sub-blur):
> **--sub-blur=<0..20.0>**
>    Gaussian blur factor. 0 means no blur applied (default).

A similar mpv option for non-text subtitles, [sub-gauss](https://mpv.io/manual/stable/#options-sub-gauss) says more:
> **--sub-gauss=<0.0-3.0>**
> Apply Gaussian blur to image subtitles (default: 0). This can help to make pixelated DVD/Vobsubs look nicer. 

Closed mpv issue https://github.com/mpv-player/mpv/issues/10784 contains pictures that show the expected behavior of this option which is to blur the subtitle text.

I believe this setting is working as intended.

To blur the video use a video filter. Here is an example using a FFmpeg [boxblur](https://ffmpeg.org/ffmpeg-filters.html#boxblur) filter.

Start IINA playing the video to blur. Select `Video Filters…` under the `Video` menu. In the `Video Filters` window click on `+`. In the pop-up select `Custom (FFmpeg)`. In `Filter name` enter `boxblur`. In `Filter value` enter `luma_radius=10:chroma_radius=10:luma_power=1`. Then click the `Add` button.
![issue-4254-filter](https://user-images.githubusercontent.com/86170219/224209764-51afb30b-6e44-420d-95eb-b07d55140343.jpg)

IINA may show a warning that hardware decoding must be turned off:

![issue-4254-warning](https://user-images.githubusercontent.com/86170219/224210074-3b2a1e6d-5816-4891-8f56-f1bd792ba330.jpg)

This will noticeably blur the video as seen here:

![issue-4254-blurry](https://user-images.githubusercontent.com/86170219/224210130-31bdc8f4-54e7-41da-a0ff-48211acae584.jpg)

**Comment by low-batt** [comment] 2023-03-29 21:37
Closing this issue as from the description the subtitle blur option is working as intended.

**Closed as completed by low-batt** 2023-03-29 21:37 UTC
