### ISSUE TITLE
Feature Request: Show video/music length.

### ISSUE THREAD

**Issue by Yrr0r** [iina/iina#1462] opened 2018-02-08 10:08 UTC
System and IINA version:
- macOS 10.13.2
- IINA 0.0.15

**Expected behavior:**

It would also be better to display video length instead than remaining time for some users in the touchbar. 
(This could be an option in customizing touchbar.)

**Comment by alejx** [comment] 2019-02-09 23:16
Duplicate of #1312

**Closed by alejx** 2019-02-09 23:16 UTC
Labels: feature: touch bar, type: feature request
