### ISSUE TITLE
Key Binding to "#" (Shift+3) fail upon IINA restarts

### ISSUE THREAD

**Issue by dav1k** [iina/iina#4267] opened 2023-03-13 15:21 UTC
- macOS Monterey 12.6.1
- IINA v1.3.1

**Expected behavior:**
Keybinds to "#" (+ any combination of modifiers) for any valid function, inserted either via IINA's Key Binding GUI or via input.conf editing, should properly save and thereby continue to function after restarting IINA.

**Actual behavior:**
Functions keybind to "#" fail to work after IINA is restarted. 
Keybinds for "#" are removed from IINA's Key Binding GUI list.

<details>
<summary><b>Crash report:</b></summary>

```
```
</details>

<br>

<details>
<summary><b>mpv log:</b></summary>

```
```
</details>

<br>

**Steps to reproduce:**
(Example)
Open Preferences, goto "Key Binding"
With a custom key bind set/file, use the "+" button to create a new Key Bind.
Record inputs "Shift+3"; "#" should appear in the recording.
Select action "Cycle", "Pause"

Test keybind with content.

Quit IINA.

Re-open IINA, resume playback.

Test "#" keybind again. Failure.
Open Preferences, goto "Key Binding"
Notice previously created keybind is gone.

- [x] MPV does not have this problem.

Note, MPV documentation for input.conf instructs users to use "SHARP" when creating keybinds for "#". Editing IINA's input.conf, attempting to use "SHARP" to create keybinds also fails.

**How often does this happen?**
Every time, highly reproducable.

**Thoughts**
It's interesting that when creating Key Bindings to "#" using the GUI, they do immediately work. Even checking the corresponding input.conf, a seemingly valid line for the newly created key bind does show up; the above example creates "# cycle pause". However, I do think there is an underlying issue parsing "#".

I suggest implementing MPV's workaround, and using "SHARP" to create robust input.conf files.

**Comment by low-batt** [comment] 2023-03-13 20:39
Reproduced. Thank you for the really clear detailed report.

The applicable section of the mpv manual is found under [input.conf syntax](https://mpv.io/manual/stable/#input-conf-syntax):
> Newlines always start a new binding. # starts a comment (outside of quoted string arguments). To bind commands to the # key, SHARP can be used.

As a test I bound `#` to the mpv command `quit`. The input file generated by IINA contains:
```text
# quit
```

When the input file is read that entry is correctly interpreted as a comment.

The mpv option [--input-keylist](https://mpv.io/manual/stable/#options-input-keylist) can be used to list the names of keys mpv recognizes:
<details>
<summary><b>Key Names:</b></summary>

```text
low-batt@gag ~$ mpv --input-keylist

SPACE
SHARP
IDEOGRAPHIC_SPACE
ENTER
TAB
BS
DEL
INS
HOME
END
PGUP
PGDWN
ESC
PRINT
RIGHT
LEFT
DOWN
UP
F1
F2
F3
F4
F5
F6
F7
F8
F9
F10
F11
F12
F13
F14
F15
F16
F17
F18
F19
F20
F21
F22
F23
F24
KP0
KP1
KP2
KP3
KP4
KP5
KP6
KP7
KP8
KP9
KP_DEL
KP_DEC
KP_INS
KP_ENTER
MBTN_LEFT
MBTN_MID
MBTN_RIGHT
WHEEL_UP
WHEEL_DOWN
WHEEL_LEFT
WHEEL_RIGHT
MBTN_BACK
MBTN_FORWARD
MBTN9
MBTN10
MBTN11
MBTN12
MBTN13
MBTN14
MBTN15
MBTN16
MBTN17
MBTN18
MBTN19
MBTN_LEFT_DBL
MBTN_MID_DBL
MBTN_RIGHT_DBL
GAMEPAD_ACTION_DOWN
GAMEPAD_ACTION_RIGHT
GAMEPAD_ACTION_LEFT
GAMEPAD_ACTION_UP
GAMEPAD_BACK
GAMEPAD_MENU
GAMEPAD_START
GAMEPAD_LEFT_SHOULDER
GAMEPAD_RIGHT_SHOULDER
GAMEPAD_LEFT_TRIGGER
GAMEPAD_RIGHT_TRIGGER
GAMEPAD_LEFT_STICK
GAMEPAD_RIGHT_STICK
GAMEPAD_DPAD_UP
GAMEPAD_DPAD_DOWN
GAMEPAD_DPAD_LEFT
GAMEPAD_DPAD_RIGHT
GAMEPAD_LEFT_STICK_UP
GAMEPAD_LEFT_STICK_DOWN
GAMEPAD_LEFT_STICK_LEFT
GAMEPAD_LEFT_STICK_RIGHT
GAMEPAD_RIGHT_STICK_UP
GAMEPAD_RIGHT_STICK_DOWN
GAMEPAD_RIGHT_STICK_LEFT
GAMEPAD_RIGHT_STICK_RIGHT
POWER
MENU
PLAY
PAUSE
PLAYPAUSE
STOP
FORWARD
REWIND
NEXT
PREV
VOLUME_UP
VOLUME_DOWN
MUTE
HOMEPAGE
WWW
MAIL
FAVORITES
SEARCH
SLEEP
CANCEL
RECORD
CHANNEL_UP
CHANNEL_DOWN
PLAYONLY
PAUSEONLY
XF86_PAUSE
XF86_STOP
XF86_PREV
XF86_NEXT
MOUSE_BTN0
MOUSE_BTN1
MOUSE_BTN2
MOUSE_BTN3
MOUSE_BTN4
MOUSE_BTN5
MOUSE_BTN6
MOUSE_BTN7
MOUSE_BTN8
MOUSE_BTN9
MOUSE_BTN10
MOUSE_BTN11
MOUSE_BTN12
MOUSE_BTN13
MOUSE_BTN14
MOUSE_BTN15
MOUSE_BTN16
MOUSE_BTN17
MOUSE_BTN18
MOUSE_BTN19
MOUSE_BTN0_DBL
MOUSE_BTN1_DBL
MOUSE_BTN2_DBL
AXIS_UP
AXIS_DOWN
AXIS_LEFT
AXIS_RIGHT
CLOSE_WIN
MOUSE_MOVE
MOUSE_LEAVE
MOUSE_ENTER
UNMAPPED
ANY_UNICODE
low-batt@gag ~$ 
```
</details>

IINA is aware of the `SHARP`  key mapping:
https://github.com/iina/iina/blob/21992670821f40c58c46ac322f815a2c03ac8409/iina/KeyCodeHelper.swift#L180

But something is going wrong.

@svobs, Do you want to take this one?

**Comment by svobs** [comment] 2023-03-13 21:00
@low-batt yeah I'll take it

**Comment by low-batt** [comment] 2023-03-13 22:02
Thanks!

**Comment by low-batt** [comment] 2023-05-13 20:00
The fix for this issue has been merged into the IINA `develop` branch. GitHub [automatically closed](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue) the linked issue in reaction to the merge. I am reopening this issue until the fix is available in an official release of IINA so that users intending to report this problem can easily locate this existing report. Once the fix for this issue has been included in an official release this issue will be closed.

Should you wish to confirm the fix is working and do not have the ability to build IINA from the sources in the `develop` branch, at some point a new _unsigned_ [nightly build](https://nightly.iina.io/) will be available for download. If you encounter a defect in a nightly build that has not been reported please enter an issue for it and be sure to indicate the problem was found in a nightly build.

The ability to disable this GitHub automatic closing action has been requested by GitHub users (discussions [#23476](https://github.com/orgs/community/discussions/23476) and [#17308](https://github.com/orgs/community/discussions/17308) for example), but so far GitHub has not implemented a way to control this behavior.

**Comment by low-batt** [comment] 2024-01-02 20:27
This is fixed in the released version of IINA.

**Closed as completed by low-batt** 2024-01-02 20:27 UTC
Labels: bug, progress: fixed/implemented
