### ISSUE TITLE
Source won't build in current Mac OS (Monterey) environment

### ISSUE THREAD

**Issue by Stokestack** [iina/iina#3748] opened 2022-05-18 23:05 UTC
- macOS 12.3.1 (Monterey) on Apple Silicon

- IINA  Building from source, so I don't know

**Expected behavior:**
Following the build instructions, using the ones under "Building mpv manually," (with the steps for Homebrew) the project builds.

**Actual behavior:**
The project fails to build. The initial failures are:

> /iina/iina/MPVController.swift:364:63: Extra argument 'extra_exts' in call

after removing the complained-about parameter, the build still fails with

> iina/deps/lib/libmujs.so: No such file or directory

This turns out to be an error in the instructions in step 6:

> Remove all of references to .dylib files from the Frameworks group in the sidebar and drag all the .dylib files in deps/lib to that group.

But it's not just dylibs; you must also remove the reference to libmujs.so.

Then you can build, but attempting to run results in a crash:

dyld[53806]: Library not loaded: @rpath/liblz4.1.dylib

This turns out to be another problem with the instructions: You can't just add these libs to the target under "Frameworks, Libraries, and Embedded Content." You have to tediously select "embed and sign" for every one of them (by default they are "do not embed").

After all that, you can run. Oddly it comes up with a message saying,

> Highlights in IINA v1.2.0
> Native Build for M1 Macs
> Now IINA is shipped with a universal binary that run natively on both Intel and M1-based Macs.

But there's no version 1.2 listed on the IINA site, not even in the nightly builds and betas.

**Comment by low-batt** [comment] 2022-05-19 02:37
I just tried the following as a test under a MacBook Pro with the M1 chip:
- I downloaded from GitHub a zip of the develop branch and unzipped
- In terminal I ran other/download_libs.sh to download the dependencies
- I double clicked on the project to bring up Xcode 13.3 
- I then ran a build
- It built fine
- It ran fine

Things get a lot harder if you build the dependencies yourself.

The 1.2.0 release can be found in GitHub [releases](https://github.com/iina/iina/releases).
I don't know why that release was not posted.

**Comment by Stokestack** [comment] 2022-05-19 04:19
"In terminal I ran other/download_libs.sh to download the dependencies"

But that's a problem for people who want to ensure that they're getting Apple Silicon-compiled binaries. The instructions should work as provided. If they don't, they should be corrected or taken down.

**Comment by HarukaMa** [comment] 2022-05-19 04:54
This line is potentially problematic:

https://github.com/iina/iina/blob/cbc7407ca697f94a81b6cdb86e146f00901c2788/other/change_lib_dependencies.rb#L103

For me at least, I have dependencies spanning across multiple directories:

```
...
	/usr/local/lib/libjack.0.1.0.dylib (compatibility version 0.1.0, current version 1.9.20)
	/opt/local/lib/libcaca.0.dylib (compatibility version 100.0.0, current version 100.19.0)
	/opt/local/lib/libjpeg.8.dylib (compatibility version 8.0.0, current version 8.2.2)
	/usr/local/lib/libshaderc_shared.1.dylib (compatibility version 1.0.0, current version 0.0.0)
...
```

(also `/opt/X11` as I've compiled mpv with X support but IINA doesn't really need it)

Is your `libmujs.so` in the prefix directory you've specified when running `change_lib_dependencies.rb`?

I'm not able to test the potentially new behavior in Xcode though as I'm still using macOS 10.15.7 and cannot build IINA locally. (Not really wanting to mess with the nightly build server)

**Comment by svobs** [comment] 2022-05-19 05:14
> /iina/iina/MPVController.swift:364:63: Extra argument 'extra_exts' in call

This looks like a new failure caused by a recent (unreleased) change in mpv's header files. The link to the header files in the README is not exactly correct. You should not be pulling the headers from the master branch; you should be matching it to the version which your `mpv-iina` cask is built against (0.34.1), so you should be using [the headers from the 0.34.1 tag](https://github.com/mpv-player/mpv/tree/v0.34.1/libmpv).

**Comment by Stokestack** [comment] 2022-05-19 07:26
I was able to get it building and running with the steps I outlined above. I would suggest changing the documentation accordingly. ¯\_(ツ)_/¯

**Comment by low-batt** [comment] 2022-05-19 12:46
> "In terminal I ran other/download_libs.sh to download the dependencies"
> 
>But that's a problem for people who want to ensure that they're getting Apple Silicon-compiled binaries.

The downloaded libraries are universal: 
```bash
low-batt@gag iina-develop$ lipo -archs deps/lib/libmujs.so
x86_64 arm64
```

No need to build them to get native Apple Silicon code.

With the universal libraries you can change the Xocde configuration to `My Mac (Rosetta)` and build an Intel version to test on an Intel Mac. Or of course build a native M1 app.

Now if you want to do something like test with upgraded dependencies, that gets "interesting".

I too noticed that the `parse_doc.rb` script downloads headers from mpv master. Since the generated swift files are checked into git I expect that script is intended to be used when you want to test the very latest headers. I am surprised there isn't an option to take a tag.

I would expect lots of trouble trying to build and run the master branch. Use develop.

**Comment by Stokestack** [comment] 2022-05-20 02:11
Thanks for the info about the libraries. But, not being sure of this (because it's not mentioned in the doc), some people will opt to build everything.

I'm not criticizing anyone's choices. But all choices presented in the documentation should work. Currently that's not the case. That's all.

**Comment by lhc70000** [comment] 2022-05-30 04:21
[Updated](https://github.com/iina/iina/commit/c141199fec8eaef3ff01df2dceb1f82054dcc7f8) the readme file with the build steps I'm currently using. IINA uses a custom build phase to copy the dylibs, and developers should add the imported dylibs to that phase to get them embedded.

The instructions were indeed incorrect. Thanks for reporting and sorry for the inconvenience.

**Closed by lhc70000** 2022-05-30 04:21 UTC

**Comment by Stokestack** [comment] 2022-05-30 08:51
No problem, and thanks for taking care of it! Keep up the good work.
