### ISSUE TITLE
[Regression] Album cover art disappears when entering / exiting music mode

### ISSUE THREAD

**Issue by MikeWang000000** [iina/iina#4245] opened 2023-03-02 18:58 UTC
**System and IINA version:**

- macOS  12.6 (21G115)
- IINA  1.3.1

**Expected behavior:** Display album art correctly.
<img width="412" alt="img" src="https://user-images.githubusercontent.com/11748152/222522758-4cc6d412-eb66-4b46-8b06-c589ddeb95b3.png">

**Actual behavior:**
<img width="412" alt="img" src="https://user-images.githubusercontent.com/11748152/222521904-4cf37321-72ca-45d2-a2f6-9a1353214928.png">

**Steps to reproduce:**
1. Open a music file with cover
2. Click 'Video' -> 'Music Mode'

**How often does this happen?**
- Always (IINA 1.3.1)
- Works normally (IINA 1.3.0)

**Comment by low-batt** [comment] 2023-03-02 22:28
Pretty certain this is a duplicate of issue #4055.

I keep getting pulled into other issues. I need to get back to that one and prepare a fix.

This is a priority to fix for the next release of IINA.

**Closed as not planned** 2023-03-02 23:43 UTC
