### ISSUE TITLE
Playlist search

### ISSUE THREAD

**Issue by alexbet** [iina/iina#4998] opened 2024-06-18 18:32 UTC
When I open an M3U playlist from IPTV which has 2000 channels, I would like to be able to search the channels by name to get to them quickly, instead of scrolling slowly and looking for the channel. VLC player has this feature, but I like IINA much better. It would be great if you can add this small feature. Thanks!

**Comment by low-batt** [comment] 2024-06-18 19:59
I'm going to close this issue as a duplicate of issue #4392. It is possible to search the playlist today. See my comment to that issue. There are requests to add a search box directly on the playlist panel. There is a PR outstanding.

**Closed as completed by low-batt** 2024-06-18 19:59 UTC
Labels: other: duplicate, type: feature request, feature: playlist
