### ISSUE TITLE
1.0.7-beta1 always resizes window

### ISSUE THREAD

**Issue by chucker** [iina/iina#2820] opened 2020-03-14 08:32 UTC
**System and IINA version:**

- macOS 10.15.3
- IINA 1.0.7-beta1 Build 115

**Expected behavior:**
In Preferences → UI → Window, I have **Resize the window to fit video size:** set to **Disabled**

As a result, opening a video should leave the window size to remain as-is.

**Actual behavior:**
The window resizes.

**Steps to reproduce:**
1. In Preferences → UI → Window, set **Resize the window to fit video size:** to **Disabled**
2. Open any video

**How often does this happen?**
This always happens in 1.0.7-beta.

This didn't happen to me in previous versions; 1.0.6 is not affected.

**Comment by lhc70000** [comment] 2020-03-15 16:32
Sorry, but I can't reproduce this issue in 1.0.7 beta 1. Do you have any other related settings enabled? Maybe a screenshot of the Settings - UI page would help.

**Comment by chucker** [comment] 2020-03-15 16:55
So here's the entire UI page:

<img width="913" alt="image" src="https://user-images.githubusercontent.com/20194/76706205-18095f00-66e6-11ea-81d9-d12a38f0b3c3.png">
<img width="572" alt="image" src="https://user-images.githubusercontent.com/20194/76706221-1f306d00-66e6-11ea-96ee-4466e6fb918c.png">

I just tried it again, with both versions installed. Open a video in 1.0.6, it behaves as expected. Open the same video in 1.0.7-beta1, the window shrinks.

**Comment by lhc70000** [comment] 2020-03-15 17:51
I tried to compare the two versions and found the difference.

In 1.0.6, it remembers the window position and size of the last played video (which can be a completely unrelated one). We think it's not reasonable. Therefore in 1.0.7, all windows open at the center of the screen with a fixed initial size 640x400 (this can only be changed at compile time).

With your settings, videos will resize nevertheless in 1.0.6 if you open another video with a different aspect ratio than the previous one, or if you open the first video in a fresh installation of IINA.

The main propose of the "disabled" option is to fix the window size after manually adjusting it. It's not the case when opening a completely new window because IINA needs to resize the window to fit the aspect ratio of the video.

However, based on the assumption that most videos are 16:9, I think it might be better if we change the initial size to 640x360 (16:9) so that in your case, it won't resize to fit the aspect ratio for most videos.

**Comment by chucker** [comment] 2020-03-15 18:31
>The main propose of the "disabled" option is to fix the window size after manually adjusting it.

Right. I _did_ manually adjust it, though. :)

**Comment by The19th** [comment] 2020-03-19 00:17
I mainly use the Initial window size Height=720 point, Initial window position=0,0 point+ left/top, and Resize the window to fit video size: Disabled options in the UI settings, which worked as expected in 1.0.6 (and earlier iirc).  New windows always opened in the upper left in a 1280x720 window.

1.0.7-beta1 completely ignores these settings, opening a 640x400 window dead center of the screen, which immediately self-resizes to 640x360.

Workarounds:
• in 1.0.7-beta1, drag window to upper left corner, press command-1 to get back to 720p size;
• in 1.0.7-beta1, enable Resize the window to fit video size to Always 1x, with a jarring "Resizing Animation" on open;
• Use 1.0.6, which correctly respects these settings.

**Comment by kazdegroot** [comment] 2020-04-03 21:54
The move to center and set to 640x400 also seems to apply when dragging a new file into an existing window (where I've already made explicit decisions wrt position and size).

While I don't have strong feelings about the position of new windows, I don't think opening a new file in an existing window should be treated in this way.

**Comment by lhc70000** [comment] 2020-06-04 17:02
> 1.0.7-beta1 completely ignores these settings, opening a 640x400 window dead center of the screen, which immediately self-resizes to 640x360.

> The move to center and set to 640x400 also seems to apply when dragging a new file into an existing window (where I've already made explicit decisions wrt position and size).

@alejx Please have a look. I think the "Disabled" option is still not working in beta 2.

**Closed** 2020-06-14 04:15 UTC
Labels: bug, progress: fixed/implemented

**Comment by mB-PiBox** [comment] 2022-09-12 16:46
Please fix this bug: What's the point of the option to disable window resizing if it doesn't actually disable it..

1.3.0 Build 132

I like having videos set to certain size on the screen, while multi tasking, and us a hotkey to skip to the next video.. however even with the resize window option set to disabled, the window resized when a new video in the playlist starts playing.

**Comment by n1kk** [comment] 2023-12-23 14:16
Please fix this. I've updated to the latest version recently and this started happening, it's very annoying, I've had to switch to VLC because of it.

**Comment by NotImportant1116** [comment] 2025-05-15 03:41
It's May 2025 and this issue still hasn't been fixed. I don't think I can keep using IINA anymore, this is a deal breaker. Shame

**Comment by mcbaer** [comment] 2025-05-15 05:24
> It's May 2025 and this issue still hasn't been fixed. I don't think I can keep using IINA anymore, this is a deal breaker. Shame

I would not hold your breath that this issue is fixed any time soon.. There has not been an update to this app for a year (May 20024)

**Comment by ellarsee** [comment] 2025-09-22 07:27
I just upgraded to 1.4.0 on a 2019 mac pro running 15.6.1 and this issue has shown up. Things used to be fine.
I have things set so that initial height of the the window is 25% of the display, this makes it convenient to play multiple videos at once. Until recently, going to the next video in a play list would not change the window size, all was good. As of this week, now when I go to the next video, even with adjust window size disabled, the window will change to whatever fraction of the nominal video size was set, before resizing was disabled.

If someone could just give me a clue what file in the source code to look in, at the least I could hack the test so that it doesn't happen on my machine.
