### ISSUE TITLE
The sliding list crashes when there are a lot of playlists

### ISSUE THREAD

**Issue by Choara** [iina/iina#2769] opened 2020-02-15 05:47 UTC
**System and IINA version:**

- macOS 10.15.3
- IINA 1.0.6

**Expected behavior:**
The sliding list crashes when there are a lot of playlists

**Actual behavior:**

<details>
<summary><b>Crash report:</b></summary>

```
```
</details>

<br>

<details>
<summary><b>mpv log:</b></summary>

```
```
</details>

<br>

**Steps to reproduce:**

When the number of playlists is large, the sliding list crashes, my playlist has 100 files, when I try 50, there is no problem

**How often does this happen?**
everytime

**Comment by alejx** [comment] 2020-02-15 07:28
Duplicate of #2745.

**Closed by alejx** 2020-02-15 07:28 UTC
