### ISSUE TITLE
1.3.1 An error window appears upon attempting to quit

### ISSUE THREAD

**Issue by luckyty** [iina/iina#4238] opened 2023-02-24 02:39 UTC
When I press Command+Q to quit, an error window pops up. Although I clicked "ignore" and haven't seen it again, I am concerned that there may be an underlying issue that needs to be addressed.

**Comment by low-batt** [comment] 2023-02-24 02:54
Thanks for reporting this failure. The error window is a macOS crash report. Clicking `ignore` is the correct choice. I don't think Apple wants to hear about IINA problems. 

You are correct about there being an underlying issue that needs to be addressed. Applications should never crash. This particular problem is timing related. That may be the reason you haven't seen it again. But as you suspected it is lurking. The problem is less likely to occur if the IINA setting `Use legacy full screen` is enabled.

This is the problem described in issue #4020. A fix has been coded and is waiting to be reviewed. This is considered a high priority problem and it will be fixed in the next IINA release. Marking this issue as a duplicate of #4020.

**Closed as completed** 2023-03-25 14:50 UTC
Labels: other: duplicate
