### ISSUE TITLE
A frame of last played video is flashed when opening a new video.

### ISSUE THREAD

**Issue by sherifabdlnaby** [iina/iina#2197] opened 2019-01-04 20:38 UTC
**System and IINA version:**

- macOS 10.13.6
- IINA 1.0.0

**Expected behavior:**
Open Video File, Window open and video starts to play.

**Actual behavior:**
Open Video file, Window Open **with a frame of the last played video** for sub 0.5 sec then opened video starts to play.

<br>

**Steps to reproduce:**
1- Open iina
2- Play a video file.
3- Close the video window **but not iina** ( dock still have dot beneath the app icon)
4- Play **another** video file

**How often does this happen?**
100%

**Comment by anohren** [comment] 2019-02-20 23:31
Having this issue as well. I start a video but unexpectedly see a completely different video that I've already watched, until I realize it's just displaying old garbage. It's about as annoying as if you'd pull out your earphones from your phone and it wouldn't pause what you're listening to. Unless you're exclusively watching movies alone, you'll just end up broadcasting some random video to the room because of stale data. 

I don't understand the labeling of issues here though. More than one issue that is clearly a bug are labeled as "enhancement". I suppose bug fixes are technically enhancements, but I just thought since there is a bug tag.

Is there a description of the labels somewhere?

**Comment by sherifabdlnaby** [comment] 2019-02-21 02:34
@anohren Exactly, this is a *bug*! and can potentially lead to awkward situations.

**Comment by shenghan97** [comment] 2019-04-24 10:14
I have already uninstalled IINA to avoid this unexpectedly mistake... This is a **SUPER MAJOR, MASSIVE, CRITICAL BUG** and should be fixed **immediately**!

**Comment by brycehammond** [comment] 2019-12-30 05:49
Forcing the layer to redraw on windowDidOpen seems to solve this, but it does seem a bit heavy handed. https://github.com/brycehammond/iina/commit/9a5530ac7fed89504cef937994e4af03cc5dd684

For now this is solving awkward moments

**Comment by anohren** [comment] 2019-12-30 13:52
I suspect it's an architectural problem that needs an architectural solution

**Comment by brycehammond** [comment] 2019-12-30 23:42
Agreed.  I looked into it for about 30 minutes to apply a fix  as the issue is annoying. I fixed it for my own sanity and found this issue already before trying to report.  Ultimately it comes down to the re-use of the PlayerCore and being able to clear and render the video layer when the loadfile command is sent to mpv.  I'm going to try to get more familiar with the project to give a better solution.

**Closed** 2020-06-14 04:15 UTC
Labels: feature: ui/ux, progress: fixed/implemented, type: enhancement
