### ISSUE TITLE
Audio delay units uses two lines in Hebrew

### ISSUE THREAD

**Issue by low-batt** [iina/iina#4895] opened 2024-04-26 21:51 UTC
**System and IINA version:**

- macOS 13.6.3
- IINA 1.3.4 + PR #4922

**Expected behavior:**
The `Audio delay` setting on the `AUDIO` tab of the quick settings panel is displayed as intended in languages other than English.

**Actual behavior:**
The `Audio delay` setting contains a text field after the slider that can be used to enter a value for the delay. After the text field is another text field giving the units of the value. In English this field shows `s`.  Currently IINA does not support any right to left languages. However PR #4922 enables Hebrew. If you build IINA with that pull request and set Hebrew as the language then the units (`שנ'`) do not fit:
![delay](https://github.com/iina/iina/assets/86170219/9151bbaa-b1af-4dea-8877-5622815887ed)

This problem was reported by @ShlomoCode in issue #4776. As that issue reports quite a few RTL related problems I have created this issue to focus just on this particular problem.

**Steps to reproduce:**
- Pull PR #4922
- Open the IINA project in Xcode 
- Under the `Product` menu open the `Scheme` menu and select `Edit Scheme…`  
- Click on the `Options` tab
- Scroll down to the `App Language` setting
- In the pull down select `Hebrew`
- Start IINA running under Xcode
- Start playing a video
- Press ⇧⌘A to show the audio panel
- Notice the units shown for `Audio delay` is wrapped into multiple lines  

- [x] MPV does not have this problem.

mpv does not support localization.

**How often does this happen?**
Every time.

**Comment by low-batt** [comment] 2024-04-27 01:33
### Analysis

My initial take was that  `s`. It is not a letter or an abbreviation, but an International System of Units (SI) symbol. From the US Metric Association [FAQ](https://usma.org/faq):
> SI unit symbols are the same in all languages, as you can see on this nutrition label from Japanese snack cakes.

That suggested the error was that IINA was presenting this label to translators instead of making it universal across all languages. _However_ as shown [here](https://github.com/iina/iina/issues/4776#issuecomment-2075890008) usage of SI symbols is not common practice in some locals. Therefore IINA should allow translators to specify the text to use in this case. Thus the layout problem needs to be corrected.

### Fixing

The solution is to change the `Line Break` attribute of the text field cell from `Word Wrap` to something else.

**Comment by low-batt** [comment] 2024-04-27 02:03
With the proposed fix the audio delay setting controls now look like:
![he-audio-delay-fixed](https://github.com/iina/iina/assets/86170219/0cc53728-de67-4015-a521-49fc57ff1f50)

**Comment by ShlomoCode** [comment] 2024-04-27 17:53
After further thought, the abbreviation "`שנ'`" is not commonly used in Hebrew, so it seems to me that it is better to translate it as "`שניות`". I consulted about this with some local colleagues who also thought so. After changing the translation there is a problem even with this PR:

![CleanShot 2024-04-27 at 22 44 38@2x](https://github.com/iina/iina/assets/78599753/187ffced-8a91-42e6-96bc-55ab12dddad2)

Can you fix it? Maybe you should narrow the width of the number input?

**Comment by low-batt** [comment] 2024-04-27 21:02
When I tested it the text field holding the number automatically reduced it's size. The results shown are unexpected. I will investigate.

**Comment by low-batt** [comment] 2024-04-28 00:09
Changing the units to be larger and setting the language to be `Right-to-Left Pseudolanguage` I see this:
![en-audio-delay-6](https://github.com/iina/iina/assets/86170219/6d873544-ebb1-4a3c-9906-2981aa993199)

The text field shrank to allow space for the units string. All seems to be working fine. But when I change the language to be Hebrew I see this:
![he-audio-delay-broken](https://github.com/iina/iina/assets/86170219/3fc8efe3-8c51-4598-bcb0-a4c58d20395b)

Not quite the same as the screenshot you posted, but something is clearly broken. Not obvious to me what is causing this. Will continue to investigate.

**Comment by ShlomoCode** [comment] 2024-04-28 00:29
The second image you uploaded looks pretty good, I don't understand how. I even tested on a clean MacOS VM and it looked like this:
![CleanShot 2024-04-28 at 03 26 52@2x](https://github.com/iina/iina/assets/78599753/ebe8e41b-8941-4ac6-8161-0a7f3a59176f)

**Comment by low-batt** [comment] 2024-04-30 20:15
I experimented a lot, but was unable to reproduce the behavior shown in your screenshot:
![he-audio-clip](https://github.com/iina/iina/assets/86170219/1f4c6728-1b22-48ee-912b-ead1c2e38432)

I did update the code to clip instead of truncate to match the behavior of the other labels. Make certain your `QuickSettingsViewController.xib` has the `lineBreakMode` set for `1VY-EN-1mi`:
```text
<textFieldCell key="cell" lineBreakMode="clipping" sendsActionOnEndEditing="YES" alignment="center" title="s" id="1VY-EN-1mi">
```

I found the `0s` (`kan-bp-QDi`) and `5s` (`Kt8-Kg-i2O`) labels have not been setup to be translated (missing from the en translations). I assume you had to add those directly to the he strings file? I believe these first have to be added to the en file, pushed to Crowdin and changed there. We will need to coordinate with @uiryuu on this.

I did confirm that some other languages also do not use the SI symbol:
<details>
<summary><b>Translations:</b></summary>

```text
low-batt@gag iina (he-audio-delay *$%=)$ grep -inr --include \*.strings '1VY-EN-1mi.title' *
iina/de.lproj/QuickSettingViewController.strings:5:"1VY-EN-1mi.title" = "s";
iina/ur.lproj/QuickSettingViewController.strings:5:"1VY-EN-1mi.title" = "s";
iina/he.lproj/QuickSettingViewController.strings:5:"1VY-EN-1mi.title" = "שנ'";
iina/ar.lproj/QuickSettingViewController.strings:5:"1VY-EN-1mi.title" = "ث";
iina/el.lproj/QuickSettingViewController.strings:5:"1VY-EN-1mi.title" = "s";
iina/zh-Hans.lproj/QuickSettingViewController.strings:5:"1VY-EN-1mi.title" = "秒";
iina/ja.lproj/QuickSettingViewController.strings:5:"1VY-EN-1mi.title" = "秒";
iina/fa.lproj/QuickSettingViewController.strings:5:"1VY-EN-1mi.title" = "ثانيه";
iina/mk.lproj/QuickSettingViewController.strings:5:"1VY-EN-1mi.title" = "s";
iina/eu.lproj/QuickSettingViewController.strings:5:"1VY-EN-1mi.title" = "s";
iina/en.lproj/QuickSettingViewController.strings:5:"1VY-EN-1mi.title" = "s";
iina/uk.lproj/QuickSettingViewController.strings:5:"1VY-EN-1mi.title" = " с";
iina/kn.lproj/QuickSettingViewController.strings:5:"1VY-EN-1mi.title" = "s";
iina/en-GB.lproj/QuickSettingViewController.strings:5:"1VY-EN-1mi.title" = "s";
iina/es.lproj/QuickSettingViewController.strings:5:"1VY-EN-1mi.title" = "s";
iina/is.lproj/QuickSettingViewController.strings:5:"1VY-EN-1mi.title" = "s";
iina/sl.lproj/QuickSettingViewController.strings:5:"1VY-EN-1mi.title" = "s";
iina/da.lproj/QuickSettingViewController.strings:5:"1VY-EN-1mi.title" = "s";
iina/it.lproj/QuickSettingViewController.strings:5:"1VY-EN-1mi.title" = "i";
iina/bg.lproj/QuickSettingViewController.strings:5:"1VY-EN-1mi.title" = "s";
iina/sk.lproj/QuickSettingViewController.strings:5:"1VY-EN-1mi.title" = "s";
iina/sr-Latn.lproj/QuickSettingViewController.strings:5:"1VY-EN-1mi.title" = "s";
iina/sr.lproj/QuickSettingViewController.strings:5:"1VY-EN-1mi.title" = "s";
iina/be.lproj/QuickSettingViewController.strings:5:"1VY-EN-1mi.title" = "s";
iina/ta.lproj/QuickSettingViewController.strings:5:"1VY-EN-1mi.title" = "s";
iina/ne.lproj/QuickSettingViewController.strings:5:"1VY-EN-1mi.title" = "s";
iina/ml.lproj/QuickSettingViewController.strings:5:"1VY-EN-1mi.title" = "s";
iina/sv.lproj/QuickSettingViewController.strings:5:"1VY-EN-1mi.title" = "sek";
iina/cs.lproj/QuickSettingViewController.strings:5:"1VY-EN-1mi.title" = "s";
iina/ko.lproj/QuickSettingViewController.strings:5:"1VY-EN-1mi.title" = "초";
iina/hy.lproj/QuickSettingViewController.strings:5:"1VY-EN-1mi.title" = "s";
iina/zh-Hant.lproj/QuickSettingViewController.strings:5:"1VY-EN-1mi.title" = "秒";
iina/no.lproj/QuickSettingViewController.strings:5:"1VY-EN-1mi.title" = "s";
iina/hu.lproj/QuickSettingViewController.strings:5:"1VY-EN-1mi.title" = "mp";
iina/tr.lproj/QuickSettingViewController.strings:5:"1VY-EN-1mi.title" = "sn";
iina/pl.lproj/QuickSettingViewController.strings:5:"1VY-EN-1mi.title" = "s";
iina/pt-BR.lproj/QuickSettingViewController.strings:5:"1VY-EN-1mi.title" = "s";
iina/vi.lproj/QuickSettingViewController.strings:5:"1VY-EN-1mi.title" = "g";
iina/lv.lproj/QuickSettingViewController.strings:5:"1VY-EN-1mi.title" = "sekundēm";
iina/ru.lproj/QuickSettingViewController.strings:5:"1VY-EN-1mi.title" = "с";
iina/af.lproj/QuickSettingViewController.strings:5:"1VY-EN-1mi.title" = "s";
iina/fr.lproj/QuickSettingViewController.strings:5:"1VY-EN-1mi.title" = "s";
iina/fi.lproj/QuickSettingViewController.strings:5:"1VY-EN-1mi.title" = "s";
iina/id.lproj/QuickSettingViewController.strings:5:"1VY-EN-1mi.title" = "dtk";
iina/nl.lproj/QuickSettingViewController.strings:5:"1VY-EN-1mi.title" = "sec";
iina/th.lproj/QuickSettingViewController.strings:5:"1VY-EN-1mi.title" = "s";
iina/pt.lproj/QuickSettingViewController.strings:5:"1VY-EN-1mi.title" = "s";
iina/bn.lproj/QuickSettingViewController.strings:5:"1VY-EN-1mi.title" = "s";
iina/ug.lproj/QuickSettingViewController.strings:5:"1VY-EN-1mi.title" = "s";
iina/ro.lproj/QuickSettingViewController.strings:5:"1VY-EN-1mi.title" = "s";
iina/hr.lproj/QuickSettingViewController.strings:5:"1VY-EN-1mi.title" = "s";
iina/hi.lproj/QuickSettingViewController.strings:5:"1VY-EN-1mi.title" = "सै.";
iina/ca.lproj/QuickSettingViewController.strings:5:"1VY-EN-1mi.title" = "s";
```
</details>

**Comment by ShlomoCode** [comment] 2024-04-30 21:02
Sorry, I just noticed that I took a image of "**subtitle** delay" and you only fixed "**audio** delay"...

Confirms that **audio** delay seems normal:
![CleanShot 2024-04-30 at 23 59 29@2x](https://github.com/iina/iina/assets/78599753/a14e325d-d3b8-42ac-a935-93c6b14eaed7)

But when I shrink the window it is not possible to see a decimal number:
![CleanShot 2024-05-01 at 00 00 36@2x](https://github.com/iina/iina/assets/78599753/1b14ac0e-b0f0-412c-a8a0-f67d20406eb4)
Do you have an idea how to solve this?

**Comment by low-batt** [comment] 2024-05-01 03:57
Yes. I will fix that. It will mean the label will get clipped instead of the box with the number when the window is really compressed.

**Comment by low-batt** [comment] 2024-05-03 02:45
I have fixed both the `AUDIO` and `SUBTITLES` tabs to not truncate the number when the panel is compressed. But I do not like that the units ends up right next to the field. Looks a bit ugly. However we have reached the limit of my GUI abilities. I will leave the PR as a draft. Will need one of the other developers to tweak this to look better when compressed.

**Comment by ShlomoCode** [comment] 2024-05-03 04:02
To clarify the progress in the meantime, this is how it is currently in a large window (it's perfect):
![CleanShot 2024-05-03 at 06 59 28@2x](https://github.com/iina/iina/assets/78599753/2b62299d-0627-419e-87dd-50e04fa4653d)

And this is in a quarter window (it's a little ugly but usable):
![CleanShot 2024-05-03 at 06 58 53@2x](https://github.com/iina/iina/assets/78599753/dd9da513-7c8c-4c5d-96c4-0262535d5aa3)


If there would be a way not to omit part of the label even in a quarter window, that would be perfect.

**Comment by low-batt** [comment] 2024-07-09 04:40
@ShlomoCode Where are we at with this one? I just rebased the PR and fixed the conflicts. I am no longer able to reproduce the problem shown above. The units are now back to שנ'?

**Comment by ShlomoCode** [comment] 2024-07-09 11:27
> The units are now back to שנ'?

Yes, but it looks like a bug in the sync bot:

![CleanShot 2024-07-09 at 14 24 39@2x](https://github.com/iina/iina/assets/78599753/4cb267ec-c5ab-436d-85ad-2ac937d85c39)
https://crowdin.com/editor/iina/65/en-he?view=comfortable#5323
https://crowdin.com/editor/iina/65/en-he?view=comfortable#5329

How did it happen? Did the bot disrupt more translations?

**Comment by uiryuu** [comment] 2024-07-09 11:51
I, too, got confused by the bot behaviors. I didn't initiate such an action but it sometimes do random behavior. I manually delete its translations for now.

**Comment by low-batt** [comment] 2024-07-09 12:40
I just pulled `develop` and still see שנ'?

**Comment by uiryuu** [comment] 2024-07-09 13:04
> I just pulled `develop` and still see שנ'?

I have to manually trigger a sync to pull the translation from crowd in. Hold on...

**Comment by uiryuu** [comment] 2024-07-09 13:38
@low-batt Done

**Comment by low-batt** [comment] 2024-07-09 14:11
@uiryuu I've rebased PR #4896 again. It now shows the issue. Normally the audio quick settings panel is short enough that a scroll bar is not needed. In that configuration the delay slider looks fine. If you reduce the height of the player window enough the quick settings panel adds a scroll bar, squishing the contents of the panel. At that point the space between the label and the text field disappears. It is that minor glitch that I could not figure out how to avoid. Please have a look when you get a chance.

**Comment by uiryuu** [comment] 2024-07-10 07:45
I still cannot reproduce the issue: first one is before the scroll bar is shown, and the second one is after the scroll bar is shown.
![image](https://github.com/iina/iina/assets/20237141/21dcd045-3407-47f7-9fc7-a3ab4cadd28a)
![image](https://github.com/iina/iina/assets/20237141/56bd7f8a-d15c-4c93-a246-8180ebe8247a)

**Comment by ShlomoCode** [comment] 2024-07-10 12:46
Yes, it looks fine now. interesting. Only one precision that needs to be done is to allow the number box to also display a decimal number
![CleanShot 2024-07-10 at 15 45 24@2x](https://github.com/iina/iina/assets/78599753/09977d10-efc2-4521-ada5-bab3138017f5)

**Comment by low-batt** [comment] 2024-07-10 19:25
@uiryuu Easier to debug this one if in `System Settings` -> `Appearance` -> `Show scroll bars` is set to `Always`.

Xcode is complaining about conflicting constraints, so there may have been some problems introduced when fixing conflicts during rebase.

I see multiple problems:
- The text field showing the current value of the slider must be able to hold `-2.5` without truncation
- The space between that text field and the units label must be maintained
- There must be no spaces between a plus/minus sign and the number (also broken in `develop`)
![compressed](https://github.com/iina/iina/assets/86170219/5d8dea77-19d9-482d-a9cc-60f65a6e008c)

The `SUBTITLES` tab is also messed up, likely more problems with resolving merge conflicts.

Probably best at this point to close PR #4896 and start fresh.

![sub-delay](https://github.com/iina/iina/assets/86170219/a5a15c13-4497-48b4-a8bd-b0233ffb0d6a)

**Comment by uiryuu** [comment] 2024-07-16 06:26
Can you wait after https://github.com/iina/iina/pull/5070 is merged, then create a new PR?

**Comment by low-batt** [comment] 2024-07-16 12:06
Will wait for #5070 to be merged.

**Comment by low-batt** [comment] 2024-07-30 01:17
Time to get back to this one. This shows what the `AUDIO` tab looks like now building the current `develop` branch. The text box for the delay is truncated. There is a space between a number and its sign in multiple places. Knobs are missing on the equalizer:
![now](https://github.com/user-attachments/assets/8af24c08-d9e2-4fab-82fe-9ee6b6a9d182)

**Comment by ShlomoCode** [comment] 2024-07-30 01:25
> There is a space between a number and its sign in multiple places.

It's a translation mistake. I will fix it
Edit: done

**Comment by ShlomoCode** [comment] 2024-07-30 01:31
These should be localized:
![CleanShot 2024-07-30 at 04 30 42@2x](https://github.com/user-attachments/assets/0d9d4baf-aeb9-4fef-933a-2877e4996775)

Looks like a bug.

**Comment by uiryuu** [comment] 2024-08-01 05:13
Tried to fix the issue in https://github.com/iina/iina/commit/ae5d2e3d1cd6d063793efb92812800769a97132e, please take a look
<img width="359" alt="image" src="https://github.com/user-attachments/assets/214fddcb-4ba8-4d6d-8a47-cd95f78b453d">

**Closed as completed** 2024-08-01 05:13 UTC
Labels: bug, progress: fixed/implemented, type: localization, priority: high, feature: preferences

**Comment by ShlomoCode** [comment] 2024-08-01 15:20
Yes it's fine now. The number field is a bit too wide but now that's just a UI issue, not a UX one.
