### ISSUE TITLE
IINA Interface Manipulation With AppleScript: GUI Scripting Is Slow

### ISSUE THREAD

**Issue by scrutinizer11** [iina/iina#4503] opened 2023-07-16 17:57 UTC
**System and IINA version:**

- macOS 10.14
- IINA 1.3.2

**Expected behavior:**

Fast and responsive GUI feedback. 

**Actual behavior:**

The lagging response to commands being sent to "System Events". The interval after the commands setting and getting the _frontmost_ property in the script below adds up to ~5 sec, which wasn't observed in **IINA 1.3.1**.

**Steps to reproduce:**
1. Start "IINA" and play a video in a non-fullscreen mode.
2. Run this AppleScript snippet in **Script Editor**:
```AppleScript
tell application "System Events"
	
	if my player_cpu("iina") > 1 then -- IINA is playing the file
		
		tell application process "IINA"
			repeat until frontmost is true
				set frontmost to true
				delay 0.1
			end repeat
			repeat until exists window 1
				delay 0.1
			end repeat
			if window 1's position is not {0, 0} then keystroke "f" using command down
			
		end tell
	end if
end tell


on player_cpu(_process)
	return (do shell script "ps -U `id -u` -o %cpu,comm | grep -i " & _process & " | awk -F'[. ]' '{if ( $2 ) print $2\",\"$3 ; else print $3\",\"$4;}'") as number
end player_cpu
```
**How often does this happen?**

Every time.

**Comment by low-batt** [comment] 2023-07-16 20:20
Thank you for reporting this.

My first attempt to reproduce this failed. I started IINA and then ran the script. The Script Editor reported this error:
```text
error "Can’t make \"0,0\" into type number." number -1700 from "0,0" to number
```

Did the script get changed when posting the issue?

I'm using a MacBookPro18,2 with the M1 chip running macOS 13.4.

![issue-4503](https://github.com/iina/iina/assets/86170219/cb2345cb-6132-4e3d-9a7e-d34a07dcbb16)

**Comment by low-batt** [comment] 2023-07-16 20:43
Ah. I see the script is trying to confirm IINA is actively consuming CPU and therefore actively playing the video? I had IINA paused. However with IINA playing I now get the error below. Maybe differences in the output of `ps` in macOS 13.4 compared to 10.14? I will debug some more.
```text
error "Can’t make \"2,/Applications/IINA\" into type number." number -1700 from "2,/Applications/IINA" to number
```

**Comment by scrutinizer11** [comment] 2023-07-16 21:00
If you see this error then it's most likely due to a long-standing annoying vacillation by Apple between sticking to a comma and period as a decimal point separator. It used to be the former, then it evolved (it's "Darwin OS", you know) to the latter. Now, from your screenshot, I see them playing to the old tempo.

In the bottommost handler, change the comma in the conditional expression of the _awk_ part to a period. Does it raise the error?

**Comment by low-batt** [comment] 2023-07-16 21:12
The commas in the two `print` statements? That gives me:
```text
error "Can’t make \"2./Applications/IINA\" into type number." number -1700 from "2./Applications/IINA" to number
```

I tested this on my old MacBook Air that is running macOS 10.15. Commenting out the initial if statement IINA still responds quickly and goes into full screen mode.

**Comment by low-batt** [comment] 2023-07-16 21:22
Of course for the issue at hand that initial if statement should not matter. I'm in the US, so it could be localization that is causing a problem. The heart of the issue is a slow response to the ⌘f keystroke, yes? So far that is not reproducing for me. I also can't think of what change in 1.3.2 could explain this delayed response you are experiencing.

**Comment by scrutinizer11** [comment] 2023-07-16 22:01
Evidence #1: real time action (took 40 sec overall to complete) https://streamable.com/hdxnn7
Evidence #2: Screenshot of the Log History with the area containing the actions in question being lightened ![](https://github.com/iina/iina/assets/45983734/a347cc20-d2ed-4b5e-8fa7-633378767457)

**Comment by scrutinizer11** [comment] 2023-07-16 22:17
I think I found the culprit. Turned out that was **Keyboard Maestro Engine** which has this bizarre misbehaviour, whereby  it makes the entire GUI state freeze. Once being reloaded, the GUI response recovers to the expected velocity. Sorry for disturbing.

**Comment by low-batt** [comment] 2023-07-16 22:28
After looking at the screen capture I was testing using multiple spaces to see if that reproduced the problem. Glad you traced it to Keyboard Maestro. Don't worry about entering an issue where it turns out the root cause is not due to IINA. IINA was not behaving as expected. Perfectly valid to report that.

Ok to close this issue?

**Comment by scrutinizer11** [comment] 2023-07-17 02:28
I think you can. Thank you for your consideration.

**Comment by low-batt** [comment] 2023-07-17 03:05
Closing as the unexpected behavior was traced to a 3<sup>rd</sup> party application.

**Closed as completed by low-batt** 2023-07-17 03:05 UTC
