### ISSUE TITLE
Can the primary subtitles and subtitles be placed below the video at the same time? -能否将主字幕与次字幕同时放置在影片的下方？

### ISSUE THREAD

**Issue by sgricky** [iina/iina#4670] opened 2023-10-24 16:46 UTC
For now the subtitles can only be placed at the bottom (primary subtitles) and above (secondary subtitles). Can the subtitles be allowed to be placed at the bottom of the screen at the same time in the next (or a certain) update?

当前字幕只能分别放置在下方（主字幕）与上方（次字幕），能否在下次（或者某次）更新时允许字幕同时都放置在画面的下方？

![Snipaste_2023-10-25_00-41-10](https://github.com/iina/iina/assets/10599751/e60c0af4-fa37-4450-b4c6-bcfe6c94c2f3)

**Comment by low-batt** [comment] 2023-10-24 19:52
This is effectively a duplicate of issue #4009. See that issue for a full explanation. For audio/video and subtitle rendering support IINA uses a library from the [mpv](https://github.com/mpv-player/mpv) project. IINA must wait for mpv to add the ability to position the secondary subtitles. That feature has been requested in mpv issue https://github.com/mpv-player/mpv/issues/3022.

这实际上是问题 #4009 的重复。请参阅该问题的完整解释。为了支持音频/视频和字幕渲染，IINA 使用了 [mpv](https://github.com/mpv-player/mpv) 项目中的一个库。IINA 必须等待 mpv 添加定位辅助字幕的功能。该功能已在 mpv 问题 https://github.com/mpv-player/mpv/issues/3022 中提出要求。

**Closed as not planned** 2024-06-24 13:19 UTC
Labels: other: duplicate
