### ISSUE TITLE
Volume Increment

### ISSUE THREAD

**Issue by ayushraina24** [iina/iina#3430] opened 2021-06-17 06:02 UTC
It would be very useful to users if they can increase the volume by more than 100% like VLC Media Player as the built-in volume controller in IINA sounds very less when the volume is 100%. I just want to say that why not users can choose to use their speaker in full capacity.

**Comment by vikegart** [comment] 2021-06-22 21:17
Duplicate of #3367

**Closed** 2021-06-22 22:06 UTC
