### ISSUE TITLE
The screen automatically dims when playing

### ISSUE THREAD

**Issue by HurstSi** [iina/iina#3880] opened 2022-07-19 00:53 UTC
**System and IINA version:** macOS 13.0 iina 1.3.0

**Expected behavior:**
The screen should keep its brightness level.

**Actual behavior:**
When playing HDR video, the screen automatically dims when the mouse stops moving.

**Steps to reproduce:**
Paly an HDR video on MacBook Pro 14 inch's screen.

**How often does this happen?**
everytime

**Comment by low-batt** [comment] 2022-07-19 01:19
You are experiencing this running the macOS Ventura (13.0) public beta?

If so, I suggest reporting this behavior to Apple. See this iMore article: [How to send feedback to Apple about macOS betas](https://www.imore.com/how-send-mac-os-public-beta-feedback)

**Comment by HurstSi** [comment] 2022-07-19 03:55
> You are experiencing this running the macOS Ventura (13.0) public beta?
> 
> If so, I suggest reporting this behavior to Apple. See this iMore article: [How to send feedback to Apple about macOS betas](https://www.imore.com/how-send-mac-os-public-beta-feedback)

Yes, that's happening on macOS Ventura. OK, I'll reporting to Apple. Thank you.

**Comment by low-batt** [comment] 2022-07-19 19:00
Thanks! Please let us know what Apple as to say.

One possibility is that this macOS feature is malfunctioning in Ventura:
[If the brightness is limited on your MacBook Pro with Liquid Retina XDR display or Apple Pro Display XDR](https://support.apple.com/en-us/HT212877)

Hopefully Apple will explain the behavior.

**Comment by poorest1212** [comment] 2022-07-31 03:29
beta2 still sucks... cannot watch HDR video in fullscreen, only works in window mode

**Comment by low-batt** [comment] 2022-08-01 19:04
Thank you for reporting this. It is helpful for the IINA project to know that there is trouble when running under the Ventura Public Beta. _However_ the point of macOS Beta releases is for _Apple_ to gather feedback. Have you reported this behavior to Apple as well? From [Apple Beta Software Program FAQ](https://beta.apple.com/sp/betaprogram/faq):
> **How do I provide my feedback to Apple?**
>
> The iOS, iPadOS and macOS public betas come with the built-in Feedback Assistant app, which can be opened from the Home screen on your iPhone or iPad or from the Dock on your Mac. The Feedback Assistant app is also available from the help menu of any app by selecting Send Feedback. If you’re running the tvOS, HomePod software or watchOS public beta, you can submit feedback through the Feedback Assistant app on an enrolled iPhone, iPad or Mac. When you experience an issue or something does not work as expected, send your feedback directly to Apple with [Feedback Assistant](https://beta.apple.com/sp/betaprogram/submitting).

Ventura Beta 2 was mentioned. Beta 4 is out. Definitely upgrade and see if Apple has fixed this. Apply may not have as I did not find anything that could explain this behavior in the [macOS 13 Ventura Beta 4 Release Notes](https://developer.apple.com/documentation/macos-release-notes/macos-13-release-notes).

What you are reporting seems to be slightly different from the first report which is reporting dimming when "when the mouse stops moving". Your report seems to have to do with "full screen"? Does dimming stop when in full screen and you move the mouse? Are you also using one of the new MacBook Pro's with the XDR display?

This is not my area of expertise, but here are some thoughts anyway...

First, watch out for IINA's HDR issue where it randomly fails to enable HDR. You can tell if IINA enabled HDR by looking at the `Quick Settings Panel` for video. This is expected to be fixed in the next release of IINA.

IINA has two forms of full screen. Under `Preferences...`, `General`, `Behavior` look for the checkbox `Use legacy full screen`. Does changing that preference change the dimming behavior?

Make certain this feature is not triggering: [If the brightness is limited on your MacBook Pro with Liquid Retina XDR display or Apple Pro Display XDR](https://support.apple.com/en-us/HT212877). Confirm you do not see the warning symbol shown in that article.

There are two macOS preferences that I know of which control screen brightness. At least that is how it is in Monterey. This preference: [Change your Mac display’s brightness](https://support.apple.com/guide/mac-help/change-your-displays-brightness-mchlp2704/mac). And this preference: [Change Battery preferences on a Mac notebook](https://support.apple.com/guide/mac-help/change-battery-preferences-mchlfc3b7879/mac). In Monterey this looks like:
![issue-3880-displays](https://user-images.githubusercontent.com/86170219/182224710-48ce01ca-562e-4c2b-83da-308a578e49d1.jpg)

And:
![issue-3880-battery](https://user-images.githubusercontent.com/86170219/182224735-b3f1e7ce-8373-44dc-ac0f-8ff3d766e4bd.jpg)

Does turning off these preferences make a difference in the case at hand?

**Comment by HurstSi** [comment] 2022-08-02 02:51
> Thank you for reporting this. It is helpful for the IINA project to know that there is trouble when running under the Ventura Public Beta. _However_ the point of macOS Beta releases is for _Apple_ to gather feedback. Have you reported this behavior to Apple as well? From [Apple Beta Software Program FAQ](https://beta.apple.com/sp/betaprogram/faq):
> 
> > **How do I provide my feedback to Apple?**
> > The iOS, iPadOS and macOS public betas come with the built-in Feedback Assistant app, which can be opened from the Home screen on your iPhone or iPad or from the Dock on your Mac. The Feedback Assistant app is also available from the help menu of any app by selecting Send Feedback. If you’re running the tvOS, HomePod software or watchOS public beta, you can submit feedback through the Feedback Assistant app on an enrolled iPhone, iPad or Mac. When you experience an issue or something does not work as expected, send your feedback directly to Apple with [Feedback Assistant](https://beta.apple.com/sp/betaprogram/submitting).
> 
> Ventura Beta 2 was mentioned. Beta 4 is out. Definitely upgrade and see if Apple has fixed this. Apply may not have as I did not find anything that could explain this behavior in the [macOS 13 Ventura Beta 4 Release Notes](https://developer.apple.com/documentation/macos-release-notes/macos-13-release-notes).
> 
> What you are reporting seems to be slightly different from the first report which is reporting dimming when "when the mouse stops moving". Your report seems to have to do with "full screen"? Does dimming stop when in full screen and you move the mouse? Are you also using one of the new MacBook Pro's with the XDR display?
> 
> This is not my area of expertise, but here are some thoughts anyway...
> 
> First, watch out for IINA's HDR issue where it randomly fails to enable HDR. You can tell if IINA enabled HDR by looking at the `Quick Settings Panel` for video. This is expected to be fixed in the next release of IINA.
> 
> IINA has two forms of full screen. Under `Preferences...`, `General`, `Behavior` look for the checkbox `Use legacy full screen`. Does changing that preference change the dimming behavior?
> 
> Make certain this feature is not triggering: [If the brightness is limited on your MacBook Pro with Liquid Retina XDR display or Apple Pro Display XDR](https://support.apple.com/en-us/HT212877). Confirm you do not see the warning symbol shown in that article.
> 
> There are two macOS preferences that I know of which control screen brightness. At least that is how it is in Monterey. This preference: [Change your Mac display’s brightness](https://support.apple.com/guide/mac-help/change-your-displays-brightness-mchlp2704/mac). And this preference: [Change Battery preferences on a Mac notebook](https://support.apple.com/guide/mac-help/change-battery-preferences-mchlfc3b7879/mac). In Monterey this looks like: ![issue-3880-displays](https://user-images.githubusercontent.com/86170219/182224710-48ce01ca-562e-4c2b-83da-308a578e49d1.jpg)
> 
> And: ![issue-3880-battery](https://user-images.githubusercontent.com/86170219/182224735-b3f1e7ce-8373-44dc-ac0f-8ff3d766e4bd.jpg)
> 
> Does turning off these preferences make a difference in the case at hand?

Yes. My situation is when I turn "full screen" and the mouse stops moving, the screen dims. And this problem only happens when I play the video, if I pause the HDR video, the screen does not dim.

Are you also using one of the new MacBook Pro's with the XDR display? Yes, my model is Macbook Pro 14 inch.

IINA has two forms of full screen. Under Preferences..., General, Behavior look for the checkbox Use legacy full screen. Does changing that preference change the dimming behavior? 
No, can not fix the problem.

Confirm you do not see the warning symbol shown in that article.
Also, not.

Automatically adjust brightness True Tone: Turning off these options does not fix the problem.

I try to feedback to Apple, but they do not give me any response.

**Comment by low-batt** [comment] 2022-08-02 20:42
@HurstSi Thanks for the update. Some of my questions were directed at @poorest1212 whose report did not mention the type of Mac and other details.

Good that you filed a report. The more an issue is reported the more likely it is that Apple will look into it.

The tests you ran ruled out a bunch of possibilities. Unfortunately that leaves us waiting to hear from Apple.

**Comment by cyoumatsu** [comment] 2022-08-04 02:18
I don't know English very well, but I found a solution in the iina settings and it doesn't affect the viewing experience.

Preferences--->User Interface--->OSD--->Display system time and battery in full screen.

Can solve the problem of sudden darkening of full-screen HDR video playback.

**Comment by low-batt** [comment] 2022-08-04 02:40
@CarterLi, any ideas on this issue?

**Comment by CarterLi** [comment] 2022-08-04 02:49
Seems to be a system bug. OSD should not affect HDR modes whatsoever

**Comment by yay** [comment] 2022-08-14 23:48
Same issue here. macOS 13.0 beta 5, iina 1.3.0, playing 8K HDR video on external monitor (Apple Studio Display).

**Comment by gorgepawns-0c** [comment] 2022-09-11 13:01
Found a solution under preferences>advanced>use mpv OSD. It helped.

**Comment by manancodes** [comment] 2022-09-21 14:40
I had a similar problem in MacOS Ventura and this solved the problem for me.

Go to Settings > Display > Advanced 
Disable _Slightly dim the display on battery_

<img width="468" alt="Screenshot 2022-09-21 at 8 08 07 PM" src="https://user-images.githubusercontent.com/54790263/191534261-a7cc5e65-9407-42b7-bd0f-5d6bc212f4bf.png">

This was under battery settings in the previous MacOS versions.

**Comment by prakashvis** [comment] 2022-10-26 03:00
This is issue still exist in Ventura stable build. Looks like Apple didn't fix it.

**Comment by shen04** [comment] 2022-10-26 14:30
Also having this issue. MacOS 13.0 (22A380).

**Comment by low-batt** [comment] 2022-10-26 21:46
I have upgraded to Ventura. The problem reproduced for me. Playing the same HDR test file that was working fine under Monterey results in an image that is so dark it is hard to see anything under Ventura.

Investigating...

**Closed** 2022-11-03 01:49 UTC
Labels: other: duplicate, feature: hdr, macOS Ventura

**Comment by sawtoothpuma** [comment] 2023-07-11 12:58
It doesn't matter if the source is HDR or SDR. When I viewing a image/video that gets to a dark scene or black background, the screen dims slowly, even with all the auto brightness settings turned off. It usually happens while I'm in fullscreen. I was able to recreate this by viewing a black background video on YouTube, and the only way to fix it was to decrease the brightness and then turn it back up. Shouldn't have to do this, it's really annoying!

Anyone found a fix for this yet? Thank you.
