### ISSUE TITLE
Playlist/Chapters no longer shows automatically in Music mode

### ISSUE THREAD

**Issue by Jimmni** [iina/iina#4088] opened 2022-11-19 14:22 UTC
I've become very accustomed to opening an M4B and having it display the chapters automatically. I don't remember if there was a setting or if it was just the default behviour, but since updating to 1.3.1 Build 133 it always opens with the playlist/chapters section hidden, and I have to manually click the button every time to reveal it. Is there a setting I missed somewhere that got changed with the update? Or is this the new default behaviour? Previously it would remember the previous state - if it was open when IINA closed, it would be open next time IINA opened. If it was closed when IINA was closed, it would be closed when IINA next opened. Hopefully this is a bug that can be fixed and not the new default behaviour. It may be a tiny thing to click a button each time, but it's surprisingly annoying :D Thanks for any help that can be provided here!

**Comment by low-batt** [comment] 2022-11-20 01:19
Reproduced. This is regression. Thanks for reporting.

I reproduced this using the M4B file [Mother Nature](https://librivox.org/mother-nature-by-george-macdonald/). I confirmed that IINA 1.3.0 starts with the playlist showing if the playlist was being displayed previously when IINA quit. This is the intended behavior.

Under IINA 1.3.1 the playlist is not displayed. If you click the toggle playlist button the playlist still does not display. This is because the code thinks it is already displaying the playlist. You must click a second time to get the playlist to display.

I see what is wrong. Need to think about how to properly fix this.

**Comment by Jimmni** [comment] 2022-11-20 16:33
I'll note that in my case, I'm not having to click the playlist button twice to get it to display. The behaviour I'm experiencing is:

Launch app by opening an M4B.
Click playlist button to re-open the playlist/chapters panel.
Click Chapters to get to where I'm needing.

Looking forward to it going back to remembering the state at last quit. For now I'll just roll back to 1.3.0. Thanks for confirming this issue!

**Comment by low-batt** [comment] 2022-11-20 19:20
I'm always concerned when what I reproduce does not exactly match up with what is being reported. It usually means I've missed something. Can you confirm this behavior with IINA 1.3.0:

> having it display the chapters automatically

I was not able to reproduce that. Older versions of IINA correctly opened the playlist, but did not select the `CHAPTERS` tab. I did not find code that would remember the playlist was showing the chapters tag. 

I'll keep an eye out for something that could explain why the behavior I'm seeing doesn't fully line up with what you are experiencing.

**Comment by Jimmni** [comment] 2022-11-20 20:57
Sorry, that was slightly lazy of me in my first message. It has never displayed the chapters automatically, I was just merging the playlists/chapter panel in my head and considering them as one. I should have said "I've become very accustomed to opening an M4B and having it display the playlists (and chapters) panel automatically." I use both the playlists and the chapters "tabs" so often I merged them in my mind when I wrote that first comment. My apologies for sending you on a bit of a wild goose chase there!

(I'd love if it did, based on context - mp3s etc. bringing up playlist, m4bs bringing up chapters.) 

Our experiences still don't seem to match, though, as I do NOT have to press the Playlists button twice, like you say here: "If you click the toggle playlist button the playlist still does not display."

Gif of how it works for me:
https://imgur.com/a/DwAR0dO

**Comment by low-batt** [comment] 2022-11-20 21:44
Thanks for clarifying.

I too have been thinking IINA should have the ability to remember and restore more aspects of the UI.

**Comment by low-batt** [comment] 2023-04-03 04:03
I have verified the fix in PR #4291 corrects the issue.

**Comment by low-batt** [comment] 2024-01-02 20:36
This is fixed in the released version of IINA.

**Closed as completed by low-batt** 2024-01-02 20:36 UTC
Labels: progress: fixed/implemented, priority: high, bug: regression
