### ISSUE TITLE
Video stretching vertically when switching to fullscreen mode

### ISSUE THREAD

**Issue by yashghelani** [iina/iina#566] opened 2017-04-09 15:52 UTC
**System and IINA version:**

- macOS 10.12.4
- IINA 0.0.7

**Expected behavior:**
It shouldn't stretch vertically. Instead, it should switch to fullscreen mode just like how Quicktime does it - seamlessly.

**Actual behavior:**
It stretched the video vertically first when switched to fullscreen and then goes back to normal.

**Comment by yashghelani** [comment] 2017-04-09 16:24
Also, this exact thing occurs when exiting the fullscreen mode.

**Comment by VKondakoff** [comment] 2017-06-07 08:24
This is a cosmetic issue, but personally I think it is very important for overall user experience while using IINA (reproducible on v0.0.11). I suggest assigning a higher priority label to this issue. Thank you!

**Comment by zhx1991** [comment] 2017-06-10 17:51
This is the only reason I am still using mpv. 

Please fix it :/

**Comment by Inderdeep29** [comment] 2017-07-08 07:17
I am loving IINA over vlc but this issue is driving me nuts. High priority please.

**Comment by skyline75489** [comment] 2017-07-08 13:13
@zhx1991 I'm kind of confused, cuz the original mpv doesn't even animate the video. It just go directly to the fullscreen size.

Guys I'd love this feature, too. But there's no easy way for mpv to be as smooth as QuickTime. I think this issue will remain low priority for now.

**Comment by lhc70000** [comment] 2017-07-08 13:16
No, I think it's not that hard (IINA has similar behavior before 0.0.4).

**Comment by skyline75489** [comment] 2017-07-08 13:28
Yeah, I doubt it could be as *seamlessly* as QuickTime. I'll respect any effort towards that goal, though.

**Comment by zhx1991** [comment] 2017-07-09 04:17
@skyline75489 It only needs to be as good as mpv.

**Comment by Inderdeep29** [comment] 2017-07-09 06:32
Hi,
I was looking into the code and in MainWindowController.swift, we have a function named windowDidResize which had the manual implementation of aspect ratio commented out. I uncommented that implementation and commented the next line "videoView.frame = NSRect(x: 0, y: 0, width: w.frame.width, height: w.frame.height)”.
Would like to know if there was any strong reason to remove that. This improved the current animation(though not as seamless as quicktime), but should do it for now. I don’t have much experience with Git so didn’t pushed commit or anything. Please look into this, the full screen transition experience is very jarring otherwise.

On 08-Jul-2017, at 6:43 PM, Chester Liu <notifications@github.com<mailto:notifications@github.com>> wrote:


@zhx1991<https://github.com/zhx1991> I'm kind of confused, cuz the original mpv doesn't even animate the video. It just go directly to the fullscreen size.

Guys I'd love this feature, too. But there's no easy way for mpv to be as smooth as QuickTime. I think this issue will remain low priority for now.

**Comment by lhc70000** [comment] 2017-07-09 18:17
If you are able to build IINA locally, please take a look on the following branches:

- `full-screen-improvements` uses custom full screen animation (the orthodox way) and has the closest behavior to QuickTime's, which keeps videos updating during the animation. However the picture has noticeable jarring issue (like resizing the window), limited by mpv and IINA's rendering method.
- `full-screen-improvements-2` reuses the code @Inderdeep29 mentioned but added even more evil tweaks to make it compatible with current version. I haven't test it thoroughly, but it seems to work as well as 0.0.4.

I personally prefer the latter one.

(@Inderdeep29: The reason removing it is that a lot of users want to display subtitles in letterboxes (black borders in full screen), so we must give control of the _whole screen_ to mpv. Thus the final size of `videoView` must be the same as the screen and not of video's aspect ratio. `full-screen-improvements-2` keeps `videoView`'s aspect ratio only during animation, and tries to update its size quietly after entering full screen.)

**Comment by sevenfourk** [comment] 2017-07-10 22:26
also was following this item, @lhc70000, I see that you merged full-screen-improvements-2 into develop already.  I was able to build IINA and animation was pretty good.  At least totally acceptable as for me. Thanks.

**Comment by MacDragon** [comment] 2018-08-27 18:48
Has there been some kind of regression? not observed how behaviour has been before, but noticing that if video is paused and full screened, the window resize works as expected, but if it's playing, it stretches it to full verticality.

**Comment by alejx** [comment] 2018-08-27 23:55
@MacDragon I've been constantly seeing this issue recently, but I found it was really difficult to debug. I'm not sure whether this is a regression since I even suspect it has never been fixed and was closed by accident. Reopen to track this again. Thank you to ping us here @MacDragon .

**Comment by yashghelani** [comment] 2018-08-28 03:28
I just tested this functionality on the latest version (v0.0.15.1 Build 69) and it’s not working smoothly. It does transition now from normal to fullscreen without stretching the video but it now pauses the video while doing it instead of stretching it.

**Closed** 2020-08-16 06:30 UTC
Labels: feature: ui/ux, type: enhancement
