### ISSUE TITLE
Ask for support moving the settings panel aside from the video window, rather than overlapping them

### ISSUE THREAD

**Issue by LingweiMeng** [iina/iina#3803] opened 2022-06-06 10:54 UTC
Thanks for developing and sharing such wonderful software.
Can you add a setting to support moving the settings panel aside from the video window, rather than overlapping them?

**Comment by low-batt** [comment] 2022-06-06 19:23
Duplicate of issue #42.

**Closed** 2024-06-24 13:47 UTC
Labels: other: duplicate, type: feature request
