### ISSUE TITLE
[ Important ] When connecting bluetooth headphones, the stepper will freeze a little.

### ISSUE THREAD

**Issue by Linhuihang** [iina/iina#4193] opened 2023-01-24 15:47 UTC
When using computer speakers, there is no problem with stepping. When connecting a bluetooth headset, every time I step forward or backward, it will freeze a little.

**Comment by low-batt** [comment] 2023-01-24 19:15
This is a duplicate of issue #3805. Although that issue is about AirPods, the problem occurs with Bluetooth audio devices. See that issue for details.

**Closed as completed** 2023-03-25 15:30 UTC
Labels: other: duplicate
