### ISSUE TITLE
Remember the selected subtitles

### ISSUE THREAD

**Issue by rainlycoris** [iina/iina#5143] opened 2024-08-17 07:24 UTC
**What you want IINA to do:**

Use the last selected record when reopen a closed video.

**What IINA does currently:**

Always select the default subtitles.

**Why you think this should be added:**

It's like recording where it was last played.
There should be no case where reopening the video will select a different subtitle.

**Examples of other projects that have something similar:**

**Comment by low-batt** [comment] 2024-08-18 00:32
This is effectively a duplicate of issue #4931. See [this comment](https://github.com/iina/iina/issues/4931#issuecomment-2121672366) for how to switch from IINA's subtitle loading to mpv's which will usually be able to restore the subtitle that was being used when the video was last played.

There are plans to add a UI in IINA's settings that would allow you to do this without having to use advanced settings.

**Comment by rainlycoris** [comment] 2024-08-18 03:23
Sorry for repeating the question. But I set sub-auto = fuzzy/all, and it didn't work, I guess because the video has a builtin subtitle. I look forward to iina solving this problem, thank you!

**Closed as completed** 2024-08-18 03:24 UTC
Labels: other: duplicate
