### ISSUE TITLE
Lags when skipping forward/backward while output is AirPods 

### ISSUE THREAD

**Issue by nguyenhimself** [iina/iina#3805] opened 2022-06-07 13:54 UTC
**System and IINA version:**

- macOS 12.4.
- IINA 1.3.0 Build 132.

**Expected behavior:**

- When skipping backward or forward, the user expect the video to be skipped smoothly to the desired point in time.

**Actual behavior:**
- When the sound output is a pair of AirPods/AirPods Pro, upon pressing the key to skip forward or backward, the video visibly lags for 0.5 - 1.0 second before resuming.
- This does not happen when the outpuit sound is the computer's speakers.

<details>
<summary><b>Crash report:</b></summary>

```
```
</details>

<br>

<details>
<summary><b>mpv log:</b></summary>

```
[mpv.log](https://github.com/iina/iina/files/8853753/mpv.log)

```
</details>

<br>

**Steps to reproduce:**
- Open a video.
- Set the sound output to a pair of AirPods/AirPods Pro.
- Play the video, then Skip forward or backward.

- [x] MPV DOES have this problem.

**How often does this happen?**
- Every single time I skip backward or forward while listening on my AirPods.

**Comment by kevin94wk** [comment] 2022-06-09 03:42
I have the same problem

**Comment by shbishal** [comment] 2022-11-07 19:37
Having the same issue
Pls fix 
Thanks in advance

**Comment by nachz314** [comment] 2022-11-11 21:26
same problem. However, if vlc is open at the same time, the issue disappears,

**Comment by nguyenhimself** [comment] 2022-12-28 01:52
I'm not aware if Iina's release schedule strictly follows mpv's, but I can confirm that [this pull request](https://github.com/mpv-player/mpv/pull/10953) does fix this same issue in mpv. We are currently waiting for mpv's maintainer to merge it into the mainline.

**Comment by low-batt** [comment] 2023-01-24 19:08
IINA's release schedule does not follow the release schedule of [mpv](https://mpv.io/), [FFmpeg](https://ffmpeg.org/) or other dependencies that IINA uses. When IINA is ready to prepare a release the status of dependencies is considered and IINA may or may not upgrade to the latest version. For example IINA did not upgrade to FFmpeg 5 for the latest release due to reports of regressions related to hardware decoding.

IINA does keep an eye on critical "upstream" defects. I've been keeping an eye on mpv issue [#10270](https://github.com/mpv-player/mpv/issues/10270) and noticed the pull request. That fix to mpv has now been merged. So we are now waiting on mpv to release [v0.35.1](https://github.com/mpv-player/mpv/issues/11111).

At least that is the perspective from a junior newbie contributor to IINA.

**Comment by sugarbun** [comment] 2023-03-27 05:40
I am also having this issue

**Comment by uiryuu** [comment] 2023-03-27 05:44
This issue has been fixed by https://github.com/mpv-player/mpv/issues/10270. The next version IINA will adopt mpv 0.35.1 which will solve this problem.

**Closed** 2024-06-26 04:49 UTC
Labels: upstream
