### ISSUE TITLE
4k hevc格式视频拉动进度条花屏Hevc video Pull Progress Bar come out blurred screen

### ISSUE THREAD

**Issue by joyousfish** [iina/iina#2349] opened 2019-03-05 16:06 UTC
**System and IINA version:**

- macOS Mojave10.14.3
- IINA 1.02

**Expected behavior:**

**Actual behavior:**
4k hevc格式视频拉动进度条会花屏 (4k hevc format video Pull Progress Bar come out blurred screen, and it returned to normalize after 1 second. h265 format video looks all right.)

<details>
<summary><b>Crash report:</b></summary>

```
```
</details>

<br>

<details>
<summary><b>mpv log:</b></summary>

```
```
</details>

<br>

**Steps to reproduce:**

- [ ] MPV does not have this problem.

**How often does this happen?**

**Comment by inflation** [comment] 2019-03-05 16:13
First, HEVC and H.265 are just different names to the same codec. Second, I have never encountered such problems. 

Can you attach any log when it happened?

**Comment by joyousfish** [comment] 2019-03-05 16:41
sorry, I mean h264 coded video looks all right.   And it is no problem to play the hevc coded video captured by the DJI UAV (shows hardware Encoder 'video toolbox' ). This only happens when I play hevc coded movie （shows no hardware Encoder）. By the way, where can I find the log when it happened?

**Comment by inflation** [comment] 2019-03-05 17:10
See [wiki](https://github.com/iina/iina/wiki/Enable-Logging-or-Find-Crash-Reports).

**Comment by joyousfish** [comment] 2019-03-05 17:18
iina.log

01:17:36.609 [iina][d] App will launch
01:17:36.837 [iina][d] App launched
01:17:36.844 [iina][d] Loading key bindings
01:17:36.850 [iina][d] Set key bindings
01:17:36.961 [iina][d] Setting up MediaPlayer integration
01:17:37.031 [player0][d] Set path to /Applications/IINA.app/Contents/MacOS:/usr/bin:/bin:/usr/sbin:/sbin
01:17:37.049 [player0][d] Track list changed
01:17:37.057 [player0][d] Track list changed

**Comment by joyousfish** [comment] 2019-03-05 17:19
mpv.log

[   0.014][v][cplayer] mpv 0.29.1 Copyright © 2000-2018 mpv/MPlayer/mplayer2 projects
[   0.014][v][cplayer]  built on Sat Nov 24 01:13:43 CST 2018
[   0.014][v][cplayer] ffmpeg library versions:
[   0.014][v][cplayer]    libavutil       56.22.100
[   0.014][v][cplayer]    libavcodec      58.35.100
[   0.014][v][cplayer]    libavformat     58.20.100
[   0.014][v][cplayer]    libswscale      5.3.100
[   0.014][v][cplayer]    libavfilter     7.40.101
[   0.014][v][cplayer]    libswresample   3.3.100
[   0.014][v][cplayer] ffmpeg version: 4.1
[   0.014][v][cplayer] 
[   0.014][v][cplayer] Configuration: ./waf configure --enable-javascript --enable-libmpv-shared --enable-lua --enable-libarchive --enable-libbluray --enable-dvdnav --enable-dvdread
[   0.014][v][cplayer] List of enabled features: 51deb apple-remote asm atomics bsd-fstatfs build-date cocoa coreaudio cplayer cplugins debug-build drmprime dvdnav dvdread dvdread-common fchmod ffmpeg gl gl-cocoa glob glob-posix gnuc gpl iconv javascript jpeg lcms2 libaf libarchive libass libass-osd libav-any libavcodec libavdevice libbluray libdl libm libmpv-shared lua macos-cocoa-cb macos-touchbar optimize osx-thread-name plain-gl posix posix-or-mingw posix-spawn posix-spawn-native pthreads stdatomic uchardet videotoolbox-gl videotoolbox-hwaccel zlib
[   0.014][v][cplayer] mpv 0.29.1 Copyright © 2000-2018 mpv/MPlayer/mplayer2 projects
[   0.014][v][cplayer]  built on Sat Nov 24 01:13:43 CST 2018
[   0.014][v][cplayer] ffmpeg library versions:
[   0.014][v][cplayer]    libavutil       56.22.100
[   0.014][v][cplayer]    libavcodec      58.35.100
[   0.014][v][cplayer]    libavformat     58.20.100
[   0.014][v][cplayer]    libswscale      5.3.100
[   0.014][v][cplayer]    libavfilter     7.40.101
[   0.014][v][cplayer]    libswresample   3.3.100
[   0.014][v][cplayer] ffmpeg version: 4.1
[   0.014][v][cplayer] 
[   0.014][v][cplayer] Configuration: ./waf configure --enable-javascript --enable-libmpv-shared --enable-lua --enable-libarchive --enable-libbluray --enable-dvdnav --enable-dvdread
[   0.014][v][cplayer] List of enabled features: 51deb apple-remote asm atomics bsd-fstatfs build-date cocoa coreaudio cplayer cplugins debug-build drmprime dvdnav dvdread dvdread-common fchmod ffmpeg gl gl-cocoa glob glob-posix gnuc gpl iconv javascript jpeg lcms2 libaf libarchive libass libass-osd libav-any libavcodec libavdevice libbluray libdl libm libmpv-shared lua macos-cocoa-cb macos-touchbar optimize osx-thread-name plain-gl posix posix-or-mingw posix-spawn posix-spawn-native pthreads stdatomic uchardet videotoolbox-gl videotoolbox-hwaccel zlib
[   0.017][v][ifo] Opening /Applications/IINA.app/Contents/Resources/config/iina-default-input.conf
[   0.017][v][ifo_dvdnav] Opening /Applications/IINA.app/Contents/Resources/config/iina-default-input.conf
[   0.017][v][bdmv/bluray] Opening /Applications/IINA.app/Contents/Resources/config/iina-default-input.conf
[   0.017][v][file] Opening /Applications/IINA.app/Contents/Resources/config/iina-default-input.conf
[   0.017][d][file] Stream opened successfully.
[   0.017][v][input] Parsing input config file /Applications/IINA.app/Contents/Resources/config/iina-default-input.conf
[   0.018][v][input] Input config file /Applications/IINA.app/Contents/Resources/config/iina-default-input.conf parsed: 83 binds
[   0.018][d][global] user path: '/Users/coffeeyu/Library/Logs/com.colliderli.iina/2019-03-06-01-17-36_q644dJ/mpv.log' -> '/Users/coffeeyu/Library/Logs/com.colliderli.iina/2019-03-06-01-17-36_q644dJ/mpv.log'
[   0.018][d][ytdl_hook] Loading lua script @ytdl_hook.lua...
[   0.018][d][stats] Loading lua script @stats.lua...
[   0.018][v][osx] Exiting...
[   0.018][v][cplayer] Set property: vo="libmpv" -> 1
[   0.018][v][cplayer] Set property: keepaspect="no" -> 1
[   0.018][v][cplayer] Set property: gpu-hwdec-interop="auto" -> 1
[   0.018][v][cplayer] Waiting for scripts...
[   0.018][d][ytdl_hook] loading mp.defaults
[   0.018][d][stats] loading mp.defaults
[   0.018][v][ao/coreaudio] selected audio output device: SPDIF-out (Orange Rear) (69)
[   0.020][d][stats] loading @stats.lua
[   0.020][d][ytdl_hook] loading @ytdl_hook.lua
[   0.023][d][ytdl_hook] reading options for ytdl_hook 
[   0.023][v][ytdl_hook] script-opts/ytdl_hook.conf not found. 
[   0.023][v][ytdl_hook] lua-settings/ytdl_hook.conf not found. 
[   0.023][d][stats] reading options for stats 
[   0.023][v][stats] script-opts/stats.conf not found. 
[   0.023][v][stats] lua-settings/stats.conf not found. 
[   0.025][d][cplayer] Run command: define-section, flags=0, args=[input_stats, i script-binding stats/display-stats
[   0.025][d][cplayer] , default]
[   0.025][d][cplayer] Run command: enable-section, flags=0, args=[input_stats, allow-hide-cursor+allow-vo-dragging]
[   0.025][d][cplayer] Run command: define-section, flags=0, args=[input_forced_stats, , force]
[   0.025][d][cplayer] Run command: enable-section, flags=0, args=[input_forced_stats, allow-hide-cursor+allow-vo-dragging]
[   0.025][d][cplayer] Run command: define-section, flags=0, args=[input_stats, I script-binding stats/display-stats-toggle
[   0.025][d][cplayer] i script-binding stats/display-stats
[   0.025][d][cplayer] , default]
[   0.025][d][cplayer] Run command: enable-section, flags=0, args=[input_stats, allow-hide-cursor+allow-vo-dragging]
[   0.025][d][cplayer] Run command: define-section, flags=0, args=[input_forced_stats, , force]
[   0.025][d][cplayer] Run command: enable-section, flags=0, args=[input_forced_stats, allow-hide-cursor+allow-vo-dragging]
[   0.026][d][cplayer] Run command: define-section, flags=0, args=[input_stats, i script-binding stats/display-stats
[   0.026][d][cplayer] I script-binding stats/display-stats-toggle
[   0.026][d][cplayer] , default]
[   0.026][d][cplayer] Run command: enable-section, flags=0, args=[input_stats, allow-hide-cursor+allow-vo-dragging]
[   0.026][d][cplayer] Run command: define-section, flags=0, args=[input_forced_stats, , force]
[   0.026][d][cplayer] Run command: enable-section, flags=0, args=[input_forced_stats, allow-hide-cursor+allow-vo-dragging]
[   0.026][d][cplayer] Run command: define-section, flags=0, args=[input_stats, i script-binding stats/display-stats
[   0.026][d][cplayer] I script-binding stats/display-stats-toggle
[   0.026][d][cplayer] , default]
[   0.026][d][cplayer] Run command: enable-section, flags=0, args=[input_stats, allow-hide-cursor+allow-vo-dragging]
[   0.026][d][cplayer] Run command: define-section, flags=0, args=[input_forced_stats, , force]
[   0.026][d][cplayer] Run command: enable-section, flags=0, args=[input_forced_stats, allow-hide-cursor+allow-vo-dragging]
[   0.026][v][cplayer] Done loading scripts.

**Comment by joyousfish** [comment] 2019-03-06 14:27
> See [wiki](https://github.com/iina/iina/wiki/Enable-Logging-or-Find-Crash-Reports).

Hi friend, any idea?

**Comment by bodayw** [comment] 2019-03-07 03:12
You should provide the log with which you reproduced the bug, i.e. seek the progress bar and when you see the corrupted image, and then save the log.

Nevertheless I guess it's most likely the FFmpeg bug I reported here: mpv-player/mpv#6218. If it's indeed the case, you will see FFmpeg report that it couldn't find I-frames when you seek the progress bar in the log. This bug has been addressed already, but we need to wait for the next FFmpeg release and then the next IINA release to incorporate the fix.

**Comment by joyousfish** [comment] 2019-03-07 15:10
> You should provide the log with which you reproduced the bug, i.e. seek the progress bar and when you see the corrupted image, and then save the log.
> 
> Nevertheless I guess it's most likely the FFmpeg bug I reported here: [mpv-player/mpv#6218](https://github.com/mpv-player/mpv/issues/6218). If it's indeed the case, you will see FFmpeg report that it couldn't find I-frames when you seek the progress bar in the log. This bug has been addressed already, but we need to wait for the next FFmpeg release and then the next IINA release to incorporate the fix.

Please take a look if these informations blew is useful.

mpv.log
-------------------------------
[ 246.235][d][cplayer] Run command: seek, flags=0, args=[56.037704, absolute-percent+exact, unused]
[ 246.235][v][lavf] queuing seek to 342.373603
[ 246.238][v][lavf] execute seek (to 8319.466936 flags 32)
[ 246.240][v][cplayer] hr-seek, skipping to 342.373603
[ 246.253][v][lavf] seek done
[ 246.254][e][ffmpeg/video] hevc: Could not find ref with POC 0
[ 246.254][w][ffmpeg/audio] truehd: Lossless check failed - expected 68, calculated f8.
[ 246.255][w][ad] Invalid audio PTS: 341.941667 -> 342.047500
[ 246.294][e][ffmpeg/video] hevc: Could not find ref with POC 3
[ 246.327][w][ffmpeg/demuxer] mpegts: Invalid timestamps stream=0, pts=748886692, dts=748890446, size=70755
[ 246.421][w][ffmpeg/demuxer] mpegts: Invalid timestamps stream=0, pts=748909215, dts=748912968, size=77179
[ 246.460][v][vd] Decoder format: 3840x2160 yuv420p10 bt.2020-ncl/bt.2020/pq/limited/auto SP=40.000000 CL=unknown (auto 0.000000/0.000000/0.000000)
[ 246.478][v][cplayer] first video frame after restart shown
[ 246.478][d][cplayer] Run command: seek, flags=0, args=[56.037704, absolute-percent+exact, unused]
[ 246.511][v][lavf] queuing seek to 342.373603
[ 246.513][v][lavf] execute seek (to 8319.466936 flags 32)
[ 246.518][v][lavf] seek done
[ 246.795][v][cplayer] hr-seek, skipping to 342.373603
[ 246.806][e][ffmpeg/video] hevc: Could not find ref with POC 0
[ 246.807][w][ffmpeg/audio] truehd: Lossless check failed - expected 68, calculated 7b.
[ 246.807][w][ad] Invalid audio PTS: 341.941667 -> 342.047500
[ 246.825][e][ffmpeg/video] hevc: Could not find ref with POC 3
[ 246.848][w][ffmpeg/demuxer] mpegts: Invalid timestamps stream=0, pts=748886692, dts=748890446, size=70755
[ 246.929][w][ffmpeg/demuxer] mpegts: Invalid timestamps stream=0, pts=748909215, dts=748912968, size=77179
[ 246.958][v][vd] Decoder format: 3840x2160 yuv420p10 bt.2020-ncl/bt.2020/pq/limited/auto SP=40.000000 CL=unknown (auto 0.000000/0.000000/0.000000)
[ 246.960][v][cplayer] first video frame after restart shown
[ 246.979][v][cplayer] starting audio playback
[ 246.980][v][cplayer] playback restart complete

iina.log
-------------------------------
23:05:10.125 [iina][w] mpv log: [ffmpeg/video] error: hevc: Could not find ref with POC 0
23:05:10.125 [iina][w] mpv log: [ffmpeg/audio] warn: truehd: Lossless check failed - expected 68, calculated f8.
23:05:10.125 [iina][w] mpv log: [ad] warn: Invalid audio PTS: 341.941667 -> 342.047500
23:05:10.164 [iina][w] mpv log: [ffmpeg/video] error: hevc: Could not find ref with POC 3
23:05:10.197 [iina][w] mpv log: [ffmpeg/demuxer] warn: mpegts: Invalid timestamps stream=0, pts=748886692, dts=748890446, size=70755
23:05:10.291 [iina][w] mpv log: [ffmpeg/demuxer] warn: mpegts: Invalid timestamps stream=0, pts=748909215, dts=748912968, size=77179

**Comment by joyousfish** [comment] 2019-03-07 15:12
Could not find ref with POC0/3, invalid timestamps stream.

**Comment by bodayw** [comment] 2019-03-07 22:15
Yes, so I think my guess is correct. Just wait for the next FFmpeg and IINA release and it will be fixed.

**Comment by joyousfish** [comment] 2019-03-08 16:07
> Yes, so I think my guess is correct. Just wait for the next FFmpeg and IINA release and it will be fixed.

Thank you very much.

**Comment by inflation** [comment] 2019-03-08 21:53
Close due to duplicate.

**Closed by inflation** 2019-03-08 21:53 UTC
Labels: other: duplicate, other: upstream

**Comment by joyousfish** [comment] 2019-03-09 03:51
> Close due to duplicate.

Sorry, I don't know where to close it.

**Comment by inflation** [comment] 2019-03-09 03:53
@joyousfish Don't worry. It's already closed. I got your back. 😊

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by joyousfish** [comment] 2019-03-09 11:34
Ok, so I need to wait for the next FFmpeg and IINA release. Thank you.
