### ISSUE TITLE
UI is blocked when step forward/backward in Music Mode

### ISSUE THREAD

**Issue by Cydiater** [iina/iina#3635] opened 2022-02-05 09:55 UTC
The UI is blocked when I want to control the playing progress with keyboard in Music Mode. If I hit the right arrow in the keyboard multiple times when the audio is playing, the progress and time indicator is updated only once. 

Like if I want to fast forward 20 seconds, the first hit of right arrow will step forward 5 seconds and the progress bar and time indicator works fine, but it's not updated for the subsequent 3 hits. It takes a while for the UI to catch up the progress. Note that this bug is not occurred when the audio is paused or not in Music Mode.

**System and IINA version:**

- macOS 12.1
- IINA 1.2.0

**Expected behavior:**

UI is sync with the control of playing progress

**Actual behavior:**

UI is blocked

**Steps to reproduce:**

1. open an audio file in Music Mode and play
2. hit right arrow multiple times to fast forward

As mentioned above

- [x] MPV does not have this problem.

**How often does this happen?**

Everytime

**Comment by low-batt** [comment] 2022-11-21 03:38
Hi Cydiater!
Noticed your post in issue #4049. You are correct, the behavior is similar, however issue #4049 is definitely due to a regression in 1.3.1. As this issue is reported against 1.2.0, there is some other problem problem causing the behavior you are experiencing.

I tried reproducing the problem and was able to use the right and left arrows to change the playback position while the audio was playing without experiencing lag. I tested IINA 1.2.0 and 1.3.0. I don't have a Mac running Monterey. My M1 machine is running macOS 13.0. The Intel Mac I tested on is running macOS 10.15.7.

IINA enables hardware decoding by default. Hardware decoding has been a source of problems and differs based on the macOS version and whether the CPU is Intel or Apple Silicon. Lets rule out an issue with hardware decoding.
- Start IINA
- Click on  `Preferences…` under the `IINA` menu
- The preferences panel appears
- On the left side of the panel click on `Video/Audio`
- Choose `Disabled` in the `Hardware decoder` pull-down button 

Test with IINA 1.3.0, not 1.3.1, since we know that one has a regression related to synchronizing the UI. Does disabling hardware decoding change the behavior?

If that does not change the behavior then we need to reproduce the problem with logging enabled and see if the log files shed some light on what might be going wrong.

Logging is disabled by default. To enabled logging follow these instructions:
- Start IINA
- Click on  `Preferences…` under the `IINA` menu
- The preference panel appears
- On the left side of the panel click on `Advanced`
- Slide the `Enable advanced settings` toggle button to be on (blue)
- Click on the checkbox `Enable logging` 
- Confirm the preferences panel looks like the screenshot below
- Click on `Open log directory`
- A new `Finder` window appears
- **Restart IINA** to activate logging
![issue-4091](https://user-images.githubusercontent.com/86170219/202960453-551a2ea9-d185-4b14-b386-ee54c56dd536.jpg)

Once IINA is restarted a new directory will appear in the `Finder` window. The directory contains two files, `iina.log` and `mpv.log` Each time IINA starts it creates a new directory to hold a fresh set of log files.

To attach the log files to this issue you can drag-n-drop them from the `Finder` window to the `Leave a comment` section below. Include both the `iina.log` and the `mpv.log`

The log files can also be accessed using [Terminal](https://support.apple.com/guide/terminal/welcome/mac) as shown here:
```bash
low-batt@gag com.colliderli.iina$ pwd
/Users/low-batt/Library/Logs/com.colliderli.iina
low-batt@gag com.colliderli.iina$ ls
2022-10-04-17-57-15_jVrbWy
low-batt@gag com.colliderli.iina$ cd 2022-10-04-17-57-15_jVrbWy
low-batt@gag 2022-10-04-17-57-15_jVrbWy$ ls
iina.log	mpv.log
low-batt@gag 2022-10-04-17-57-15_jVrbWy$ 
```

**DO NOT FORGET** to disable logging once you have obtained log files for the problem being investigated. IINA does not restrict the size of log files or delete old logs. If you leave logging enabled the logs will continue to accumulate.

**Comment by Cydiater** [comment] 2022-11-21 08:53
Thanks for your reply. The issue still exists with the hardware decoder disabled. Here are the log files. 
[iina.log](https://github.com/iina/iina/files/10054897/iina.log)
[mpv.log](https://github.com/iina/iina/files/10054898/mpv.log)

**Comment by low-batt** [comment] 2022-11-21 22:30
Still struggling to reproduce this one.  I'm testing on my MacBookPro18,2 with the M1 chip and testing with IINA 1.3.0 due to the regression in 1.3.1. I noticed one difference between the `mpv.log` posted above and the log from my testing. In my test mpv reports:
```text
[   0.257][v][ao/coreaudio] selected audio output device: MacBook Pro Speakers (67)
```
The log posted above shows:
```text
[   2.867][v][ao/coreaudio] selected audio output device:  (81)
```

What audio device are you using? Does the problem reproduce when using your Mac's builtin speakers?

**Comment by Cydiater** [comment] 2022-11-22 07:24
I was using AirPods Pro 2. The problem disappeared with built-in speakers.

**Comment by low-batt** [comment] 2022-11-22 21:25
IINA uses a library from [mpv](https://mpv.io/) for audio/video playback. This is the reason for the question in the issue template about whether the mpv player also exhibits the problem. If it is an audio or video playback issue it is likely that the root cause of the problem is in the library IINA embeds from the mpv project, or some library the mpv library depends upon. Such problems are referred to as "upstream" as they have to be fixed by another project and then IINA will need to pickup the fix once that project has released a new version.

I was focused on this being some sort of IINA UI problem as "MPV does not have this problem" is checked. I think we need to probe into that a little more as there is the open mpv issue [#10270](https://github.com/mpv-player/mpv/issues/10270) that reports lagging when using AirPods. That mpv issue sure sounds like what is being reported here, but I'm concerned that mpv worked for you. IINA 1.3.0/1.3.1 is using the mpv library from v0.34.1. The mpv project just released v0.35.0. As that mpv issue is still open I'm not expecting that release to have a fix for this issue. What version of mpv did you test with?

Once aspect that might be in play is when audio is switched from the internal speakers to the AirPods. Is IINA/mpv already running when the speakers are changed or is the Mac already using the AirPods when IINA/mpv is started.

When you tested the mpv player were you using AirPods?

**Comment by Cydiater** [comment] 2022-11-23 08:22
Sorry for the misinformation. I checked that option because I thought IINA UI could be updated first before sending forward/backward instructions to the decoder. I did not know it could be a bug in MPV.  

I generated these log files with IINA 1.3.0 and MPV 0.34.1. And the Mac was using the AirPods when IINA was started. I have checked with MPV now. It has the same problems. I think we can wait for MPV to fix these issues.

**Comment by low-batt** [comment] 2022-11-24 04:07
Not a problem at all. I really appreciate you reporting the problem and working with me to track it down. Thanks for your help! I've added mpv issue [#10270](https://github.com/mpv-player/mpv/issues/10270) to a list of mpv issues I'm tracking. For now we are waiting on the mpv project to provide a fix.

**Closed** 2024-06-26 04:47 UTC
Labels: upstream
