### ISSUE TITLE
[Feature Req] Minimize background iina window on Picture In Picture Mode

### ISSUE THREAD

**Issue by fullmetalsheep** [iina/iina#2014] opened 2018-10-02 11:59 UTC
**System and IINA version:**

- macOS 10.13.4
- IINA 0.0.15.1

**Expected behavior:**
Please ignore how I trigger the 'picture in picture' mode. I used bettertouchtool to setup that.
![2018-10-02 19 50 22](https://user-images.githubusercontent.com/23723926/46347111-f85eb200-c67c-11e8-8ef5-ed7495b10b47.gif)
When Entering Picture In Picture Mode, the floating player should pin to a corner, and **the background iina window should minimize**.

I think this should be the default behavior since we only use picture in picture mode to clear up the desktop and browse the web etc.

**Actual behavior:**
![2018-10-02 19 49 42](https://user-images.githubusercontent.com/23723926/46347180-3a87f380-c67d-11e8-9c8e-4404a77f4e2a.gif)

When Entering Picture In Picture mode, floating player pins to a corner, but the background iina window is left in the screen.

**Comment by alejx** [comment] 2018-10-02 18:29
Duplicate of #1442.

**Comment by fullmetalsheep** [comment] 2018-10-03 02:04
> Duplicate of #1442.

I don't believe its a duplicate (although our terms are similar). He's requesting an option to let the player enter pip mode when minimizing iina window, while I'm requesting that after entering the pip mode, the leftover window be minimised.

**Comment by alejx** [comment] 2018-10-03 02:08
Sorry, my bad. I did not read it carefully.

**Comment by rudeigerc** [comment] 2018-10-13 15:40
Hi, is there anyone working on this issue? Could I be assigned? :)

**Comment by MuntashirAkon** [comment] 2018-10-25 16:44
I like the idea very much. But it looks weird as the two animations take place nearly at the same time.

**Comment by saagarjha** [comment] 2019-05-29 13:41
Fixed by #2147, I believe.

**Closed by saagarjha** 2019-05-29 13:41 UTC
Labels: plugin, type: enhancement
