### ISSUE TITLE
Holding down mouse button to change speed

### ISSUE THREAD

**Issue by arvin-z** [iina/iina#4929] opened 2024-05-12 05:34 UTC
**What you want IINA to do:** Add an option to the Control settings for holding down the left (or right) mouse button to temporarily change the video speed. For example, holding down the left mouse button would change video playback to 2x speed. Upon letting go of the mouse button, the speed will return to the previous speed.

**What IINA does currently:** Holding down the mouse button currently triggers the single click action upon letting go.

**Why you think this should be added:** This feature would make situations where you want to speed up a small portion of a video much more convenient, as it would remove the need to manually change the speed once and then change it back again.

**Examples of other projects that have something similar:** This feature is available on YouTube. Hold down the left mouse button on any playing video and it will change to 2x speed until you let go.

**Comment by low-batt** [comment] 2024-05-13 02:00
I believe this is a duplicate of issue #4437. Does that feature request match the behavior you would like to see implemented?

**Comment by arvin-z** [comment] 2024-05-13 05:08
That indeed looks like the feature I’m looking for. My bad for the duplicate

**Comment by low-batt** [comment] 2024-05-13 13:07
Don't worry about entering a duplicate. I too have a hard time locating an existing issue when I'm preparing to enter one.

Release plans are never set in stone, but it is likely the next release of IINA will be a bug fix release. Quickly after that should be the first beta for a release that focuses on adding features. 

Closing this issue as a duplicate of #4437.

**Closed as completed by low-batt** 2024-05-13 13:07 UTC
Labels: other: duplicate
