### ISSUE TITLE
Time progress bar do not move in music playing.

### ISSUE THREAD

**Issue by wujx3433** [iina/iina#4402] opened 2023-05-09 06:01 UTC
When I playing music with IINA, the progress bar always freeze at the beginning of music, through the playing is normal.

Screenshot:
<img width="412" alt="image" src="https://user-images.githubusercontent.com/32533580/237006941-a4b3ff01-cf30-4e1f-85be-1289669e51db.png">
The music is already playing, but the progress bar is still at 8:39

IINA Version: 1.3.1 Build 133
OS Version: macOS Ventura 13.3.1(a)

This problem has appeared since I started using IINA, when the system version was Ventura 13.0

**Comment by wujx3433** [comment] 2023-05-09 06:03
I would like to add that mp3 files do not have this problem. Files with this problem are usually lossless music formats such as ALAC, FLAC, and APE.

**Comment by low-batt** [comment] 2023-05-09 15:05
There is a known regression in IINA 1.3.1 that causes the progress bar to stop while in music mode. That problem has been fixed in the development version of IINA. If you know how to deal with an _unsigned_ nightly build you can test and confirm this is fixed. Those builds can be found [here](https://nightly.iina.io/).

This troubles me:
> I would like to add that mp3 files do not have this problem.

The known problem has to do with being in music mode. A mp3 should also exhibit the problem. I just tried playing a mp3 with IINA 1.3.1 and the progress bar showed the problem. Worrying that it works in your case.

**Comment by wujx3433** [comment] 2023-05-09 15:12
Thanks, I'll try to build the dev version and test later. I'll keep reporting if there are still issues.

**Comment by wujx3433** [comment] 2023-05-09 15:18
Also, this issue reproduces strangely, most of the time the progress bar doesn't move, but after I play a few songs, it moves again. Not 100% will appear, it will appear with probability, the probability is unknown. I suspect that the "mp3 files do not have this problem" I said earlier is because this problem does not happen.

**Comment by wujx3433** [comment] 2023-05-09 17:07
OK, a good news. I tried the build with commit [b869aad](https://github.com/iina/iina/commit/b869aad).

I tested with some kinds of music, include ALAC, FLAC, APE, WAV, MP3, some of them are with ``.cue`` file.

After half an hour of testing, this problem did **NOT** appear. 

I decided to use this build daily for a while to track down this problem.

**Comment by low-batt** [comment] 2023-05-09 17:13
Thank you very much for testing the `develop` branch and reporting the results. We are very close to the next release. If you find regressions, please let us know ASAP.

One of the areas that is being worked is to reduce needless energy use. IINA should not be updating UI components when they are hidden. The offending change in 1.3.1 shutdown the background task responsible for updating the playback position when the OSC was hidden. That failed to take into account music mode where the OSC is always visible.

That the progress bar sometimes works in music mode is likely due to the code that stops the background task missing some cases. That needs to be explored, however this next release is focused on upgrading dependencies and fixing regressions.

**Comment by wujx3433** [comment] 2023-05-11 13:08
Through this period of use, this problem did not appear.

Congratulations!🎉

I think this version can be used as a new release.

If you have no other questions, you can close this issue. If there is any problem, I will contact you again. Thanks for your hard work!💕

**Comment by low-batt** [comment] 2023-05-11 19:45
Thank you again for testing and reporting back.

We are close to a release. You can see the work remaining in the pinned issue. The main blocker right now is that the updated `libmpv` library causes IINA to prevent sleep when playback is paused. That is a regression that we believe must be fixed before a release can be generated. A fix is currently in review.

Another bad aspect of that problem is that `coreaudiod` continues to consume CPU time while playback is paused. The proposed fix addresses both of these problems.

I will go ahead and close this issue.

**Closed as completed by low-batt** 2023-05-11 19:45 UTC
