### ISSUE TITLE
Prompt not showing when adjusting the playback speed

### ISSUE THREAD

**Issue by zhang13music** [iina/iina#2206] opened 2019-01-07 20:00 UTC
**System and IINA version:**

- macOS Mojave 10.14.2
- IINA 1.0.0 build 100

**Expected behavior:**
The prompt should be showing when changing the playback speed.

**Actual behavior:** The prompt will not be showed most of the time when changing the playback speed.

<details>
<summary><b>Crash report:</b></summary>

```
```
</details>

<br>

<details>
<summary><b>mpv log:</b></summary>

```
```
</details>

<br>

**Steps to reproduce:**

- [ ] MPV does not have this problem.

**How often does this happen?** Quite often, more than half of the times when I adjust the speed.

**Comment by johan456789** [comment] 2019-02-02 13:18
How did you change the speed, via shortcut? what kind of adjustment is it? I have the same problem for "multiply speed by x" but not for "add speed x". Same in IINA v1.0.1 (103)

**Comment by zhang13music** [comment] 2019-02-05 04:37
> How did you change the speed, via shortcut? what kind of adjustment is it? I have the same problem for "multiply speed by x" but not for "add speed x". Same in IINA v1.0.1 (103)

This was happening when using the keyboard shortcut. They were indeed "multiply speed by x", I haven't tested on "add speed x".

**Comment by alejx** [comment] 2019-02-07 04:20
I'm pretty sure that I have noticed this issue, but I cannot reproduce it now. Can you guys provide more details on how to reproduce this issue?

**Comment by zhang13music** [comment] 2019-02-07 04:30
It occurred pretty randomly on my mac so I haven't figured out a fixed pattern for this problem to show up itself.
Happened mostly to me when playing movies that are over an hour long with subtitles on, if that helps in any way?

**Comment by alejx** [comment] 2019-02-07 04:33
Are you sure you can still reproduce it now? I remember it seems broken *completely* around before 1.0.0 was released, so I'm not sure whether it was mpv improved this.

**Comment by johan456789** [comment] 2019-02-07 05:04
If there is calculation in mpv command (e.g. multiply speed by 1/1.25) it won't show the prompt but will have the correct speed adjustment. Another strange behavior to note is that, let's say + is multiply speed by 1.25, - is multiply speed by 1/1.25, if you run +-+, the final speed will be 1.25^2, which is incorrect and should be 1.25 

I made a video to demo: https://drive.google.com/open?id=1ikx-TFgbSgb_ob6FYIXJ2oNLZHlAqnpq
This works every time in IINA v1.0.1 (103)

**Comment by alejx** [comment] 2019-02-07 06:13
@johan456789 Thanks for your information. I dug into this issue, just write what I found here, in case of I'll forgot otherwise.

IINA changes the speed in two ways by using two mpv APIs:
```c
// You can pass some thing like "multiply speed 0.7" as `args` to change speed
int mpv_command_string(mpv_handle *ctx, const char *args);
// and
int mpv_set_property(mpv_handle *ctx, const char *name, mpv_format format,
                     void *data);
```
The first one is more general. Most of the keybindings that *users* create would call this function to get things done. However some of the keybindings that IINA defines call the second one (by setting those keybindings in the menu).

IINA does some tricky things here to make this issue seems like happen randomly. IINA picks two appropriate speed change actions from the keybinding configuration, form top to bottom. "Appropriate" means the speed change is within a pre-defined range, so that it would be ok to displayed in the menu.

The problem is that currently if we change the speed by calling the first function, mpv will **not** notify IINA by sending property change messages, like what the first function does. I'm not sure whether it is designed like this deliberately or is a bug in mpv. If the former, we should change our design to make sure we can always get notified when mpv have a property change.

**Comment by alejx** [comment] 2019-02-07 06:19
> Another strange behavior to note is that, let's say + is multiply speed by 1.25, - is multiply speed by 1/1.25, if you run +-+, the final speed will be 1.25^2, which is incorrect and should be 1.25

mpv does not recognize "1/1.25", if you change it into "0.8" everything will be fine. Though I think a syntax check for mpv commands (like only allow numbers and dot for this case) is viable.

**Comment by alejx** [comment] 2019-05-29 11:14
mpv-player/mpv#6349 has already been merged, mpv should ship this fix in their next release.

**Closed** 2020-08-16 07:14 UTC
Labels: bug, other: upstream, progress: fixed/implemented
