### ISSUE TITLE
Pressing arrow keys to move the cursor in some input fields affects playback

### ISSUE THREAD

**Issue by rasitayaz** [iina/iina#4583] opened 2023-08-14 16:06 UTC
In "save downloaded subtitle" dialog, pressing arrow keys to move the cursor in filename input affects playback.

**System and IINA version:**

- macOS Ventura 13.4
- IINA 1.3.3 Build 138

**Expected behavior:**

Video duration to stay the same

**Actual behavior:**

Video rewinds when pressed left arrow key to move the cursor inside input field, fast forwards when pressed right arrow key, just like they normally do in playback window.

**Steps to reproduce:**

Download an online subtitle, open "save download subtitle" dialog, try to move the cursor in filename field with arrow keys.

**How often does this happen?**

All the time

**Comment by rasitayaz** [comment] 2023-08-14 16:08
Seems like this issue is not just related to "save downloaded subtitle" screen: #3206, #3039

**Comment by low-batt** [comment] 2023-08-14 20:07
Thank you for reporting this. Extra thanks for pointing out there are similar problems with other input fields as reported in the cited issues.

@svobs Another issue related to processing key strokes. This one is not a recent regression.

**Comment by svobs** [comment] 2023-08-17 00:15
I already found a partial fix. See #4587, which should address the Quick Settings fields.

Unfortunately it looks like a separate fix will be required for Open/Save dialogs.

**Comment by svobs** [comment] 2023-10-09 22:07
The PR for this fix may is no longer necessary. Apple has fixed this problem from their end.

From the [Sonoma release notes](https://developer.apple.com/documentation/macos-release-notes/appkit-release-notes-for-macos-14#NSSavePanel-NSOpenPanel):

> Modeless and application modal open and save panels are now main windows. (14623155, 103038843)  This fixes a problem where menu items that weren’t applicable to the open or save panel remained enabled. Open and save panels that are displayed as sheets are unchanged.

I downloaded and ran the latest nightly build, which confirmed this - at least for Sonoma.

**Comment by low-batt** [comment] 2023-10-09 22:18
Not sure how much that helps? We still need to fix this for older macOS versions. Even though I find it annoying the change that ties the sheet to the window is probably correct as it matching up with how save dialogs for Apple applications work.

**Comment by svobs** [comment] 2023-10-09 22:32
> Not sure how much that helps? We still need to fix this for older macOS versions. Even though I find it annoying the change that ties the sheet to the window is probably correct as it matching up with how save dialogs for Apple applications work.

That is a fair point... and the modal nature of the sheet does clean up the control flow by preventing the user from altering any of the state on which the dialog relies. I won't close the PR.

**Comment by low-batt** [comment] 2023-10-10 17:33
Sounds good. We will see what the other developers opinion is on this. I'm hoping they will free up in another week and be able to review and merge some of these PRs.

**Comment by low-batt** [comment] 2024-01-02 20:46
The fix for this issue has been merged into the IINA `develop` branch. GitHub [automatically closed](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue) the linked issue in reaction to the merge. I am reopening this issue until the fix is available in an official release of IINA so that users intending to report this problem can easily locate this existing report. Once the fix for this issue has been included in an official release this issue will be closed.

**Comment by low-batt** [comment] 2024-06-09 02:42
This was fixed in IINA 1.3.5.

**Closed as completed by low-batt** 2024-06-09 02:42 UTC
Labels: bug, progress: fixed/implemented
