### ISSUE TITLE
When wearing airpodspro headphones, the positioning progress bar will get stuck.

### ISSUE THREAD

**Issue by Xingxyc** [iina/iina#4209] opened 2023-02-04 09:09 UTC
When wearing airpodspro headphones, the positioning progress bar will get stuck.
But when using other players, there will be no jam.
When I disconnect the earphone, it will return to normal.

- macOS 
- IINA

**Comment by low-batt** [comment] 2023-02-07 01:56
Based on the indication that the progress bar functions normally when the AirPods are disconnected I believe this is a duplicate of issue #3805. See that issue for details.

**Closed as completed** 2023-03-25 15:27 UTC
Labels: other: duplicate
