### ISSUE TITLE
"Show Quick Settings Panel" menu item should toggle to "Hide Quick Settings Panel"

### ISSUE THREAD

**Issue by thoran** [iina/iina#3853] opened 2022-06-26 01:54 UTC
**System and IINA version:**
- macOS 12.4
- IINA 1.3.0 Build 132

**Expected behavior:**
After having selected the "Show Quick Settings Panel" menu option under "Subtitles" it should show "Hide Quick Settings Panel".

**Actual behavior:**
After having selected the "Show Quick Settings Panel" menu option under "Subtitles" it continues to show "Show Quick Settings Panel".

**Steps to reproduce:**
As per above.

**How often does this happen?**
Every time. At least its consistent!

**Comment by svobs** [comment] 2022-06-26 02:15
Will work on fixing this

**Comment by low-batt** [comment] 2022-06-27 18:08
This is a duplicate of issue #3116.

A partial fix can be found in PR #3474. I say partial, because this issue extends beyond menus, buttons must also change to indicate the state of a toggle. The fix in PR #3474 only addresses menu items.

That fix was originally on the list of planned fixes for 1.3.0, but that PR along with a number of other PRs were postponed in order to get 1.3.0 released earlier.

See issue #3116 for a full discussion.

**Comment by svobs** [comment] 2022-07-01 07:42
@low-batt thanks for pointing this out before I did duplicate work! 

> A partial fix can be found in PR https://github.com/iina/iina/pull/3474. I say partial, because this issue extends beyond menus, buttons must also change to indicate the state of a toggle. The fix in PR https://github.com/iina/iina/pull/3474 only addresses menu items.

It looks like in IINA 1.3.0, the PIP icon actually does change correctly when toggled - at least in El Capitan. 

Maybe an icon for "toggle fullscreen" when in fullscreen could be added, similar to these from SF Symbols:
![Toggle-fs](https://user-images.githubusercontent.com/2213815/176848143-efbbced5-510f-4add-9354-d0ad8d6cf537.png)

What other toolbar icons need changing?

**Comment by low-batt** [comment] 2022-07-01 22:41
I did not look closely into the issue with toggle buttons for two reasons...

Mostly because I lack any experience with creating icons and given the concerns in issue https://github.com/iina/iina/issues/3158 it seemed best to leave this for someone skilled in icon creation.

But there is also issue https://github.com/iina/iina/issues/3387 which is proposing an alternative design for these small icons. I believe that issue needs to be considered when designing new icons to represent the toggle state. I'm expecting the simpler icon style proposed in that issue would make it easier for users to distinguish between two icons representing the toggle state. However such a change must be run past the developers...

**Comment by low-batt** [comment] 2024-01-02 20:38
This is fixed in the released version of IINA.

**Closed by low-batt** 2024-01-02 20:38 UTC
Labels: other: duplicate, progress: fixed/implemented
