### ISSUE TITLE
Black screen but normal sound

### ISSUE THREAD

**Issue by tlerbao** [iina/iina#4102] opened 2022-11-27 13:18 UTC
<img width="692" alt="image" src="https://user-images.githubusercontent.com/20442232/204137328-b0e473b2-1ac1-4caa-a436-ab52f3066d20.png">

**Comment by low-batt** [comment] 2022-11-27 14:24
I will be closing this issue as a duplicate of issue #4101. Please post any additional information in that issue.

**Closed as completed** 2022-11-30 02:33 UTC
Labels: other: duplicate
