### ISSUE TITLE
Cursor remains visible after resuming playback with the touchpad using secondary click

### ISSUE THREAD

**Issue by michelklaasen** [iina/iina#4183] opened 2023-01-19 17:36 UTC
**System and IINA version:**

- macOS: Version 13.1 (22C65)
- IINA: 1.3.1 Build 133

**Expected behavior:**
After resuming playback of a video file with secondary click (two finger click by default on macbook) the UI & cursor should become invisible after a short period of time.

**Actual behavior:**
After resuming playback of a video file with secondary click the UI becomes invisible but the cursor remains visible.

**Steps to reproduce:**
* Open a video file
* Pause the video
* Wait a couple seconds
* Resume the playback using secondary click on the touchpad

Note: I think you need to wait a couple seconds otherwise the system will make the cursor go invisible based on the action before that…?

I don't know what MPV is so I can't say whether it's a bug of MPV.

**How often does this happen?**
Consistently. As long as you wait a couple seconds.

**Comment by low-batt** [comment] 2023-01-20 06:09
Reproduced for me under macOS Ventura 13.1 following instructions given in the issue using both IINA 1.3.1 and 1.2.0. **Did not** reproduce for me under macOS Catalina 10.15.7.

A secondary click is not required to reproduce this problem. Start playing a video. Wait for IINA to hide the OSC and cursor. Very carefully click the primary mouse button without moving the mouse. The OSC should remain hidden. Under macOS 13.1 the cursor appears and does not disappear until the mouse is moved, the OSC appears and then when the OSC is hidden again the cursor will be hidden again.

When IINA hides the OSC it calls the macOS AppKit method [NSCursor.setHiddenUntilMouseMoves](https://developer.apple.com/documentation/appkit/nscursor/1534665-sethiddenuntilmousemoves). Given that method's name and that the mouse is not being moved in the sequence that demonstrates the problem this seems to me to be a regression in macOS. 

From a quick search I did not find anyone discussing this on the net. I need to code up a simple test to double check the behavior of `setHiddenUntilMouseMoves`.

We might have to put in a workaround for this and call `setHiddenUntilMouseMoves` when the mouse is clicked. Something like that. Late here. Need to think about this when I'm awake.

On this:
> I don't know what MPV is so I can't say whether it's a bug of MPV.

I started working on a "submitting issues" document that would explain more about what the issue template is asking. Still needs work.

The reason for this question is that like a lot of applications IINA is built on top of code from many other projects. When investigating problems developers need to determine if the root cause of the problem resides in code the project controls or if the offending code belongs to another project. IINA refers to problem that reside in code IINA obtained from other projects as "upstream" issues. Such problems need to be reported to the appropriate project. Fixed by that project. Released by that project. And then IINA will need to update to the fixed version of the code.

IINA asks if a problem is reproducible using the [mpv player](https://mpv.io/) because IINA uses a library from that project for audio/video playback. So for problems related to playback it is desirable for IINA to know if the problem can be reproduced using mpv. This does not apply to the issue at hand.

**Comment by michelklaasen** [comment] 2023-01-21 20:31
Wow, thanks for the high quality reply. Seems like I was onto something :D

> seems to me to be a regression in macOS

Huh interesting. 

One thing that's notable is that the cursor _does_ hide after moving, just not after clicking. If the same function is used it shouldn't be a problem with the function, would it?

I see that there's also a hide() and unhide() function. I'm guessing you could take a more manual approach using these instead. 

As for MPV, I had a feeling it was the way you described, but I hadn't heard of it. I also wouldn't really feel like installing & testing it for a bug report though :/

**Comment by low-batt** [comment] 2023-01-23 23:28
Thank you very much for taking the time to report this IINA behavior. IINA is definitely not behaving as intended.

On this:
> One thing that's notable is that the cursor does hide after moving, just not after clicking. If the same function is used it shouldn't be a problem with the function, would it?

Good question.

The documentation for the macOS AppKit method [NSCursor.setHiddenUntilMouseMoves](https://developer.apple.com/documentation/appkit/nscursor/1534665-sethiddenuntilmousemoves) says:
> …hide the cursor until one of the following occurs:
>
>  - The mouse moves.
>
>  - You invoke the method again, with flag set to false.

From that documentation as well as the name of the method programmers should be able to assume the cursor remains hidden until the application receives a mouse moved event.

I have now coded a tiny application which tests this method. Running under macOS Catalina the method behaves as documented. The cursor remains hidden until the mouse moves. Clicking a button without moving the mouse does not cause the cursor to become visible. Under macOS Ventura the cursor becomes visible upon clicking a mouse button without the mouse moving. I confirmed the test program is not receiving a mouse moved event when this happens.

As Catalina works as expected it is my contention that the macOS Ventura AppKit behavior is erroneous. I asked IINA users in the [Telegram Group](https://t.me/IINAUsers) about this problem and have heard it is reproducible under macOS Monterey. I tested an older version of macOS Big Sur and it reproduced under that macOS version as well.

I have reported this faulty behavior to Apple.

IINA could try using the `NSCursor` [hide](https://developer.apple.com/documentation/appkit/nscursor/1527345-hide) and [unhide](https://developer.apple.com/documentation/appkit/nscursor/1532996-unhide) methods, but I would prefer to add a simple workaround for the broken macOS versions expecting Apple will fix this and IINA can then go back to the implementation that was working fine before the regression in `setHiddenUntilMouseMoves`.

I will shortly be postly such a workaround. When running under the broken versions of macOS, IINA will now call `setHiddenUntilMouseMoves` to hide the cursor again when a button is clicked while the cursor is hidden.

**Comment by michelklaasen** [comment] 2023-01-24 22:16
Sure, sounds good!

So how does the updating work? Will it be part of the next IINA update? If so, it may take some time before it is applied, right? Or can small issues be updated on the fly?

**Comment by low-batt** [comment] 2023-01-24 22:56
I'm a junior newbie contributor to IINA. So the next step is for others to review PR #4191 and either ask for changes, or approve it and merge the changes into the develop branch. Once the changes are in the develop branch it is nearly guaranteed that it will be in the next release of IINA. It helps that the changes are small and straight forward. That makes it more likely the changes will be reviewed soon. This is also a regression which makes it a priority to fix for the next release.

As for when the next IINA release will be. There are a number of regressions in 1.3.1 that really need to be fixed. And some of the projects IINA is dependent upon have released new versions. At the moment pull requests are piling up. So it is going to depend upon developers having time to review and merge fixes.

**Comment by destroyer11687** [comment] 2023-03-03 09:41
> I'm a junior newbie contributor to IINA. So the next step is for others to review PR #4191 and either ask for changes, or approve it and merge the changes into the develop branch. Once the changes are in the develop branch it is nearly guaranteed that it will be in the next release of IINA. It helps that the changes are small and straight forward. That makes it more likely the changes will be reviewed soon. This is also a regression which makes it a priority to fix for the next release.
> 
> 
> 
> As for when the next IINA release will be. There are a number of regressions in 1.3.1 that really need to be fixed. And some of the projects IINA is dependent upon have released new versions. At the moment pull requests are piling up. So it is going to depend upon developers having time to review and merge fixes.

I'm glad I saw this post. I really hope your fix can be implemented soon. I love IINA, but this issue has been persistent in it for at least 6 months and it's certainly a bit annoying.

**Comment by low-batt** [comment] 2023-04-29 03:55
The fix for this issue has been merged into the IINA `develop` branch. GitHub [automatically closed](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue) the linked issue in reaction to the merge. I am reopening this issue until the fix is available in an official release of IINA so that users intending to report this problem can easily locate this existing report. Once the fix for this issue has been included in an official release this issue will be closed.

**Comment by low-batt** [comment] 2023-07-14 03:23
IINA 1.3.2 contains the fix for this issue.

**Closed as completed by low-batt** 2023-07-14 03:23 UTC
Labels: progress: fixed/implemented, bug: regression

**Comment by michelklaasen** [comment] 2023-07-16 16:03
Fuck yeah. Thanks a ton.
