### ISSUE TITLE
Expose currently playing data to applescript

### ISSUE THREAD

**Issue by imaverage** [iina/iina#4337] opened 2023-04-10 04:42 UTC
**What you want IINA to do:**
I would like IINA to be able to expose some API such that certain data is queryable, such as -- specifically for this issue -- the time into the video.

Imagine the follow (working) code, but for IINA to get the currently playing spot in the move duration (where in the video we are).

```
tell application "Google Chrome"
    get URL of active tab of front window
end tell
```

Note: see the native "Script Editor" app and its "Open dictionary" functionality for context.

**What IINA does currently:**
nothing; this data is not accessible at all afaik

**Why you think this should be added:**
With the proliferation of LLMs everywhere (bard, chatgpt), this functionality will allow making this app accessible to the new world. What I am actually seeking, is to integrate this with such AI bots, so I can chat with it about the movie and it will be able to access the current context (such as by getting the currently playing time, cross reference that with the subtitles or closed captioning, gather the textual context of what speech was just said, and include that with the query to the AI so it has context for the topic).

Example use case:
* *am watching iron man*
* *wow i wonder what she meant by that thing she just said*
* press a button to bring up my chatbot, so I can ask it. it knows the time in the movie, and the conversation that was happening in the movie, and can answer my question when i ask "what did she mean by that?"
* AI: "in this scene in the movie Iron man, pepper potts proposes an idea where by.... *explanation*"

**Examples of other projects that have something similar:**
Chrome, and tons of mac apps (see example code above)
Looks like VLC might support this already [src](https://apple.stackexchange.com/questions/127329/applescript-to-manipulate-vlc)

**Comment by low-batt** [comment] 2023-04-10 12:54
See the extensive discussion in issue #3370 on how to query IINA for the currently playing position and other information.

A plugin system and support for AppleScript are planned for the next feature release.

I am labeling this as a duplicate of issue #316.

**Closed as not planned** 2024-06-24 13:44 UTC
Labels: other: duplicate
