### ISSUE TITLE
Missing Padding in PlaylistViewController

### ISSUE THREAD

**Issue by avenius** [iina/iina#3585] opened 2021-12-20 20:37 UTC
The Playlist/Chapter slide is missing a padding to the left.

<img width="756" alt="Bildschirmfoto 2021-12-20 um 19 15 50" src="https://user-images.githubusercontent.com/643312/146828907-8e4034cc-5bbf-4736-a028-b1a590d2edc1.png">

I tried to fix this layout problem, adding a padding and wrap the buttons in a StackView for better layout.

<img width="700" alt="Bildschirmfoto 2021-12-20 um 21 29 00" src="https://user-images.githubusercontent.com/643312/146829217-684aa547-0847-4a44-b5e8-911ce2ce46a0.png">

**Comment by svobs** [comment] 2023-07-19 03:49
Confirmed that this is still a valid problem in IINA 1.3.2, and in addition, that @avenius's PR fixes it effectively (after cherry-picking it and resolving some minor conflicts). Some more explanation might be helpful.

The current solution lays out the tab buttons by dividing the available width in half, then giving each button half the space.

The German word for "Playlist" (pictured in the issue description) is so long that when the sidebar is at its minimum width, it is longer than the 50% it is given. But because it is a button, Cocoa tries hard not to truncate it, and it sees that the other button has extra space which it isn't using and lets it take just enough to fit. But it runs against the edge, which looks ugly.

I don't think I can add commits to his PR, so I'll post another one which builds on top of it.

**Closed** 2023-07-23 03:09 UTC
