### ISSUE TITLE
[UI]Playback/Timebar freezes at the start while playing any audio file

### ISSUE THREAD

**Issue by singh-jagjot** [iina/iina#4051] opened 2022-11-08 10:08 UTC
**System and IINA version:**

- macOS 13
- IINA 1.3.1 Build 133

**Expected behavior:**
Playback/Timebar should display the correct played time for audio files in audio player mode. 

**Actual behavior:**
Playback/Timebar freezes at the start while playing any audio file in audio player mode, but the audio keeps playing as expected.

<br>

**Steps to reproduce:**
Just play any MP3/FLAC file in audio player mode.

- [x] MPV does not have this problem.

**How often does this happen?**
At Random

**Comment by low-batt** [comment] 2022-11-08 16:29
I reproduced this same behavior when investigating issue #4049.

**Comment by birdjumper** [comment] 2023-01-26 10:41
As a temporary workaround, I've noticed that stopping playback, then restarting coaxes the playback time to show correctly.

**Comment by low-batt** [comment] 2023-03-22 15:46
The fix for this issue has been merged into the IINA `develop` branch. GitHub [automatically closed](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue) the linked issue in reaction to the merge. I am reopening this issue until the fix is available in an official release of IINA so that users intending to report this problem can easily locate this existing report. Once the fix for this issue has been included in an official release this issue will be closed.

Should you wish to confirm the fix is working and do not have the ability to build IINA from the sources in the `develop` branch, at some point a new unsigned [nightly build](https://nightly.iina.io/) will be available for download. If you encounter a defect in a nightly build that has not been reported please enter an issue for it and be sure to indicate the problem was found in a nightly build.

The ability to disable this GitHub automatic closing action has been requested by GitHub users (discussions [#23476](https://github.com/orgs/community/discussions/23476) and [#17308](https://github.com/orgs/community/discussions/17308) for example), but so far GitHub has not implemented a way to control this behavior.

**Comment by low-batt** [comment] 2023-07-14 03:37
IINA 1.3.2 contains the fix for this issue.

**Closed as completed by low-batt** 2023-07-14 03:37 UTC
Labels: progress: fixed/implemented, priority: high, bug: regression
