### ISSUE TITLE
Extreme Saturation of Colors

### ISSUE THREAD

**Issue by sovon** [iina/iina#1673] opened 2018-05-05 16:09 UTC
The reds and blues seems to be over saturated to a level where it feels unnatural and bad. Specially reds.

![screen shot 2018-05-05 at 7 36 50 pm](https://user-images.githubusercontent.com/18725800/39665088-096fafb4-50ac-11e8-96f7-24c4d80e8eac.jpg)
<img width="1440" alt="screen shot 2018-05-05 at 7 37 15 pm" src="https://user-images.githubusercontent.com/18725800/39665089-099eae9a-50ac-11e8-89aa-cfcb268f231f.png">

**System and IINA version:**

- macOS 10.13.4
- IINA 1.0.0 beta1 71

**Expected behavior:**

**Actual behavior:**

- Crash report:
```

```

- MPV log:
```

```

**Steps to reproduce:**
The media file is the remux of Planet Earth II PE_II_EP01_ISLANDS_BD_UHD_HDR_REMUX-BLUEBIRD available on rutracker. Here is the mediainfo of the file I've played.

[MediaInfo.txt](https://github.com/lhc70000/iina/files/1976836/MediaInfo.txt)

- [x] MPV does not have this problem.

**How often does this happen?**

**Comment by ErikMinekus** [comment] 2018-05-05 18:02
Duplicate of #1424?

**Comment by sovon** [comment] 2018-05-05 19:39
This is 0.28.2 mpv

<img width="1440" alt="screen shot 2018-05-06 at 1 08 21 am" src="https://user-images.githubusercontent.com/18725800/39666963-0d8fd27c-50ca-11e8-86e9-a7285df589d9.png">
<img width="1440" alt="screen shot 2018-05-06 at 1 07 38 am" src="https://user-images.githubusercontent.com/18725800/39666964-0dc484b8-50ca-11e8-978d-6a7c4b44e557.png">

**Comment by sovon** [comment] 2018-05-05 19:53
And this is VLC Vetinari 3.0.2

Lot less brighter but beautiful to look at. Feels natural with no issues.

<img width="1440" alt="screen shot 2018-05-06 at 1 18 58 am" src="https://user-images.githubusercontent.com/18725800/39667079-f387bc80-50cb-11e8-871e-817a92f857f4.png">
<img width="1440" alt="screen shot 2018-05-06 at 1 17 37 am" src="https://user-images.githubusercontent.com/18725800/39667080-f3bc7c72-50cb-11e8-878d-1d8d924fedba.png">

**Comment by bodayw** [comment] 2018-05-05 22:33
Are you using any color management related options in mpv or IINA, like ``--icc-profile``, ``--icc-profile-auto``, ``--target-prim``? If not, I'm actually confused now to see the results of mpv and IINA being different.

Also, which Mac model are you using if you're using the built-in display, or if not, what monitor model are you using?

**Comment by sovon** [comment] 2018-05-06 08:34
I'm not using any color management related options anywhere at all.

I'm on my MacBook Pro 2017 13" TouchBar model. NO external display. Laptop display only. Brightness around 50-60%.

**Comment by bodayw** [comment] 2018-05-07 23:17
On my late 2013 MacBook Pro 15-inch running macOS 10.13.4, I get identical colors in mpv and IINA with default settings. Although I can see obvious banding in IINA while in mpv it appears to be smooth. I thought this banding issue is related to mpv-player/mpv#4976, but given the banding also appears in bright areas, it could be another issue entirely.

Right now I can't think of a reason why you have different colors in mpv and IINA, but anyway, try go to Preferences - Advanced in IINA, add an entry in ``Additional MPV options``, with ``Name`` being ``icc-profile`` and ``Value`` being the path to the icc profile of your monitor. Your can find the path to the icc profile in macOS Settings - Display - Color by hover the mouse pointer on the profile. In mpv you can also add a line ``icc-profile-auto`` in ``mpv.conf``. Try this and see it there's still difference between IINA and mpv, as well as VLC.

BTW the screenshots of VLC above look very dim to me, so I guess VLC is not doing luma tone mapping for HDR videos like in mpv and IINA by default. HDR videos need to be tone mapped to be viewed on an SDR screen.

**Comment by ShikiSuen** [comment] 2018-05-08 01:41
@bodayw If you want to reveal this issue, you MUST use a Mac that utilizes a wide-color panel in lieu of an SRGB one. You could find either a 4K / 5K iMac or any MacBook Pro model later than October 2016, as they all use Display P3 panels.

I made a video through Final Cut Pro X. Its color looks normal in QuickTime 7, QuickTime X and Movist but oversaturated in the current release of IINA. Due to confidential concerns I couldn't provide related screenshots but I am using a 2017 model of MacBook Pro. I tested this issue with an SRGB monitor and found that such monitor won't show you such issue.

**Comment by ShikiSuen** [comment] 2018-05-08 01:42
Also, my tested video generated by FCPX is in H264, not H265.

**Comment by sovon** [comment] 2018-05-08 20:50
@bodayw Hey man.

Did check everything as you've told. I found the ICC profile within the root user, not in my account. 

<img width="780" alt="screen shot 2018-05-09 at 1 36 51 am" src="https://user-images.githubusercontent.com/18725800/39782144-ff374310-532e-11e8-9c76-7195418010d3.png">

I literally took about 50 screenshots to get the exact same frame across MPV - IINA test on - ICC auto vs no ICC (hwdec only). This is it. No change from my initial report. One thing I've noticed is that, with ICC auto in mov and ICC path linked in IINA, the image is ever so slightly more contrasty.

<img width="1500" alt="iina-nothing" src="https://user-images.githubusercontent.com/18725800/39782349-8abde3a8-532f-11e8-9cfc-bc8be606803c.png">

**Comment by sovon** [comment] 2018-05-09 07:28
In 2017 I opened up an issue for the banding explicitly here https://github.com/lhc70000/iina/issues/1204

The software decode is fine but it swallows battery life like a black hole and laptop becomes so hot that it can't be kept on lap. Some API limitation with videotoolbox - it's been an ongoing issue for quite some time. I wonder if it's ever going to get fixed.

Right now I'm in office looking at the image I posted last night on a 2011 iMac 1080p 21.5" and the thing I mentioned "with ICC auto in mpv and ICC path linked in IINA, the image is ever so slightly more contrasty." - I can't distinguish the difference in this screen.

And as for this over saturation issue, I hope the developers of IINA figure it out. Over at macrumors lot of people reported this oversaturation issue for the better half of 2017. It's not an upstream issue cause MPV doesn't seem to have it.

**Comment by ShikiSuen** [comment] 2018-05-09 22:03
@bodayw Could you please tell me how to enable "--icc-profile-auto" in the IINA? I tried setting it as the follows but it doesn't work:
<img width="492" alt="image" src="https://user-images.githubusercontent.com/3164826/39842111-7c9313de-53a2-11e8-9cbf-c401152fa11a.png">

<img width="408" alt="image" src="https://user-images.githubusercontent.com/3164826/39842102-75d45be8-53a2-11e8-8a1e-e044f12e6f89.png">

**Comment by ShikiSuen** [comment] 2018-05-09 22:05
(I set this value to "yes" and IINA stop warning the "-7" error. However the color management still doesn't work.)

**Comment by bodayw** [comment] 2018-05-09 22:11
@ShikiSuen 

``icc-profile-auto`` doesn't work IINA.
See https://github.com/lhc70000/iina/issues/1424#issuecomment-363923302

**Comment by bodayw** [comment] 2018-05-18 22:36
So mpv converts videos encoded in wide color gamut to BT.709 by default, see above referenced mpv issue and updated mpv manpage.

I still don't know why the result in mpv doesn't look oversaturated in @sovon's screenshots. Oversaturation in IINA here is expected, as the BT.2020 colorspace of 4K videos is hard coded to be converted to BT.709, which is narrower than DCI-P3 on recent Macs.

Also I still don't know why setting ``icc-profile`` with the system built-in icc profile didn't solve the issue for @sovon. Is there any chance that this profile is not the original one comes with the pre-installed OS? Anyway you can still try ``target-prim=dci-p3``. This should solve the oversaturation issue, and should bring you to close to correct colors (assuming Apple made your screen close enough to DCI-P3 D65).

**Comment by ValZapod** [comment] 2021-05-07 14:25
> 4K videos is hard coded to be converted to BT.709, which is narrower than DCI-P3 on recent Macs

And so what? MacOS is auto color managed. If you are outputing BT.709 surface it will be color managed to DCI-P3.

**Comment by bodayw** [comment] 2021-05-07 14:57
> 
> 
> > 4K videos is hard coded to be converted to BT.709, which is narrower than DCI-P3 on recent Macs
> 
> And so what? MacOS is auto color managed. If you are outputing BT.709 surface it will be color managed to DCI-P3.

Not always. Video players like IINA (mpv), in particular, have to take care of color management on their own because of performance concerns.

**Comment by ValZapod** [comment] 2021-05-07 15:01
> Video players like IINA (mpv), in particular, have to take care of color management on their own because of performance concerns.

But it is flowed? Because upstream (Little-CMS) is flowed. See https://github.com/mm2/Little-CMS/pull/69

**Comment by bodayw** [comment] 2021-05-07 15:24
> 
> 
> > Video players like IINA (mpv), in particular, have to take care of color management on their own because of performance concerns.
> 
> But it is flowed? Because upstream (Little-CMS) is flowed. See [mm2/Little-CMS#69](https://github.com/mm2/Little-CMS/pull/69)

Oh, I meant that video players like IINA or mpv do not use ColorSync, thus not "auto color managed by macOS".

mpv does use Little-CMS in its rendering process for color conversion, and this is controlled by mpv itself. The final output won't be modified by any other mechanisms.

**Closed** 2024-06-25 05:38 UTC
Labels: type: feature request
