### ISSUE TITLE
Resume last playback position doesnt work with 1.0.6?

### ISSUE THREAD

**Issue by telepati** [iina/iina#2757] opened 2020-02-08 11:21 UTC
First I thought this is avi format problem then I tried with many different format videos it always starts from the beginning. I back to v1.0.4 this version is much stable than the last two versions.

**Comment by megadr01d** [comment] 2020-02-11 21:46
Dupe of https://github.com/iina/iina/issues/2736. Close this one and follow that one instead, please.

**Closed** 2020-02-11 22:47 UTC
