### ISSUE TITLE
Plugin system: crash in EventController.addListener()

### ISSUE THREAD

**Issue by svobs** [iina/iina#3986] opened 2022-10-14 20:32 UTC
**System and IINA version:** 

- macOS 12.6
- IINA fork of the `develop` branch: most recent commit `42b19d59022ba6a2206806f26145ccece842155f` - but no changes to the code in the stack trace.
- Running with plugin system enabled, and 1 plugin installed: `io.iina.demo`

I was interested in testing another issue, so not sure if I was exiting IINA or launching it when this happened. I was *probably* launching it by double-clicking a video file in the Finder.

Here's the problem report:
[IINA-crash.log](https://github.com/iina/iina/files/9789858/IINA-crash.log)

This looks like a race condition in EventController - probably a concurrent modification to its `listeners` dictionary. Looks like the crashed thread was not running on the main queue. This was the only time this happened in maybe 10 launches.

**Comment by low-batt** [comment] 2022-10-15 03:21
TSan flagged this data race. I hadn't had a chance to add an issue for it. Data races with Swift dictionaries can definitely trigger a crash. Unless you want to take this one, I'll code up a fix. Let me know.

**Comment by svobs** [comment] 2022-10-15 06:38
@low-batt Be my guest! Seems like it should be relatively straightforward one

**Comment by low-batt** [comment] 2022-10-15 20:49
### Analysis

The crash report shows the crashing thread is from the dispatch queue `com.colliderli.iina.controller` owned by `MPVController`. The thread crashed checking to see if a plugin has established a listener for the mpv property that changed:
```text
Thread 8 Crashed::  Dispatch queue: com.colliderli.iina.controller
0   IINA                          	       0x104c80a04 $sSDyq_Sgxcig4IINA15EventControllerC4NameV_SDySSAB0B8Callable_pGTg5 + 0 [inlined]
1   IINA                          	       0x104c80a04 $s4IINA15EventControllerC11hasListener3forSbAC4NameV_tF + 24 (EventController.swift:57) [inlined]
2   IINA                          	       0x104c80a04 MPVController.handlePropertyChange(_:) + 916 (MPVController.swift:1300)
```

The crash report also shows the main thread was in the process of establishing a listener:
```text
19  IINA                          	       0x104a878e8 specialized EventController.addListener(_:for:) + 248 (EventController.swift:62)
20  IINA                          	       0x104a84fd0 $s4IINA15EventControllerC11addListener_3forSSAA0B8Callable_p_AC4NameVtF + 20 [inlined]
21  IINA                          	       0x104a84fd0 JavascriptAPIEvent.on(_:_:) + 1040 (JavascriptAPIEvent.swift:41)
```

The behavior of accessing a Swift dictionary concurrently from multiple threads is undefined and can result in crashes. This data race is also being detected by the thread sanitizer as seen here:

<details>
<summary><b>Xcode Console:</b></summary>

```text
19:51:33.585 [player0][d] Track list changed
==================
WARNING: ThreadSanitizer: Swift access race (pid=67020)
  Modifying access of Swift variable at 0x00010ec35f50 by main thread:
    #0 EventController.listeners.modify <compiler-generated> (IINA:arm64+0x1002df7ac)
    #1 EventController.addListener(_:for:) EventController.swift:62 (IINA:arm64+0x1002dfc44)
    #2 JavascriptAPIEvent.on(_:_:) JavascriptAPIEvent.swift:41 (IINA:arm64+0x10000e1fc)
    #3 @objc JavascriptAPIEvent.on(_:_:) <compiler-generated> (IINA:arm64+0x10000eae0)
    #4 __invoking___ <null>:95860036 (CoreFoundation:arm64e+0x65db0)
    #5 closure #5 in JavascriptPolyfill.register(inContext:) JavascriptPolyfill.swift:76 (IINA:arm64+0x1000bad3c)
    #6 partial apply for closure #5 in JavascriptPolyfill.register(inContext:) <compiler-generated> (IINA:arm64+0x1000bb028)
    #7 thunk for @escaping @callee_guaranteed (@guaranteed String) -> (@out Any?) <compiler-generated> (IINA:arm64+0x1000bb0e0)
    #8 __invoking___ <null>:95860036 (CoreFoundation:arm64e+0x65db0)
    #9 JavascriptPluginInstance.init(player:plugin:) JavascriptPluginInstance.swift:61 (IINA:arm64+0x10062bbc0)
    #10 JavascriptPluginInstance.__allocating_init(player:plugin:) JavascriptPluginInstance.swift (IINA:arm64+0x10062b670)
    #11 closure #1 in PlayerCore.loadPlugins() PlayerCore.swift:175 (IINA:arm64+0x10063dfc8)
    #12 partial apply for closure #1 in PlayerCore.loadPlugins() <compiler-generated> (IINA:arm64+0x10063e124)
    #13 thunk for @callee_guaranteed (@guaranteed JavascriptPlugin) -> (@owned JavascriptPluginInstance?, @error @owned Error) <compiler-generated> (IINA:arm64+0x10063e1a0)
    #14 partial apply for thunk for @callee_guaranteed (@guaranteed JavascriptPlugin) -> (@owned JavascriptPluginInstance?, @error @owned Error) <compiler-generated> (IINA:arm64+0x10063e27c)
    #15 Sequence.compactMap<A>(_:) <null>:95860036 (libswiftCore.dylib:arm64e+0x1b6268)
    #16 static PlayerCore.createPlayerCore() PlayerCore.swift:68 (IINA:arm64+0x100631d74)
    #17 one-time initialization function for first PlayerCore.swift:16 (IINA:arm64+0x1006319ac)
    #18 dispatch_once <null>:95860036 (libclang_rt.tsan_osx_dynamic.dylib:arm64e+0x7d708)
    #19 dispatch_once_f <null>:95860036 (libclang_rt.tsan_osx_dynamic.dylib:arm64e+0x7d818)
    #20 PlayerCore.first.unsafeMutableAddressor PlayerCore.swift:16 (IINA:arm64+0x100631e98)
    #21 AppDelegate.applicationDidFinishLaunching(_:) AppDelegate.swift:203 (IINA:arm64+0x100345cd0)
    #22 @objc AppDelegate.applicationDidFinishLaunching(_:) <compiler-generated> (IINA:arm64+0x100348db0)
    #23 __CFNOTIFICATIONCENTER_IS_CALLING_OUT_TO_AN_OBSERVER__ <null>:95860036 (CoreFoundation:arm64e+0x79508)
    #24 start <null>:95860036 (dyld:arm64e+0x5088)

  Previous read of size 8 at 0x00010ec35f50 by thread T2:
    #0 EventController.listeners.getter <compiler-generated> (IINA:arm64+0x1002df6a0)
    #1 EventController.hasListener(for:) EventController.swift:57 (IINA:arm64+0x1002df8cc)
    #2 MPVController.handlePropertyChange(_:_:) MPVController.swift:1186 (IINA:arm64+0x1006eb880)
    #3 MPVController.handleEvent(_:) MPVController.swift:801 (IINA:arm64+0x1006de118)
    #4 closure #1 in MPVController.readEvents() MPVController.swift:758 (IINA:arm64+0x1006dcba4)
    #5 partial apply for closure #1 in MPVController.readEvents() <compiler-generated> (IINA:arm64+0x1006f8b34)
    #6 thunk for @escaping @callee_guaranteed () -> () <compiler-generated> (IINA:arm64+0x100044740)
    #7 __tsan::invoke_and_release_block(void*) <null>:95860036 (libclang_rt.tsan_osx_dynamic.dylib:arm64e+0x7c808)
    #8 _dispatch_client_callout <null>:95860036 (libdispatch.dylib:arm64e+0x63a4)

  Location is heap block of size 24 at 0x00010ec35f40 allocated by main thread:
    #0 __sanitizer_mz_malloc <null>:95860036 (libclang_rt.tsan_osx_dynamic.dylib:arm64e+0x59814)
    #1 _malloc_zone_malloc <null>:95860036 (libsystem_malloc.dylib:arm64e+0x1e744)
    #2 PlayerCore.init() PlayerCore.swift:121 (IINA:arm64+0x10063caac)
    #3 @objc PlayerCore.init() <compiler-generated> (IINA:arm64+0x10063d52c)
    #4 PlayerCore.__allocating_init() PlayerCore.swift (IINA:arm64+0x1006332dc)
    #5 static PlayerCore.createPlayerCore() PlayerCore.swift:64 (IINA:arm64+0x100631a70)
    #6 one-time initialization function for first PlayerCore.swift:16 (IINA:arm64+0x1006319ac)
    #7 dispatch_once <null>:95860036 (libclang_rt.tsan_osx_dynamic.dylib:arm64e+0x7d708)
    #8 dispatch_once_f <null>:95860036 (libclang_rt.tsan_osx_dynamic.dylib:arm64e+0x7d818)
    #9 PlayerCore.first.unsafeMutableAddressor PlayerCore.swift:16 (IINA:arm64+0x100631e98)
    #10 AppDelegate.applicationDidFinishLaunching(_:) AppDelegate.swift:203 (IINA:arm64+0x100345cd0)
    #11 @objc AppDelegate.applicationDidFinishLaunching(_:) <compiler-generated> (IINA:arm64+0x100348db0)
    #12 __CFNOTIFICATIONCENTER_IS_CALLING_OUT_TO_AN_OBSERVER__ <null>:95860036 (CoreFoundation:arm64e+0x79508)
    #13 start <null>:95860036 (dyld:arm64e+0x5088)

  Thread T2 (tid=4068998, running) is a GCD worker thread

SUMMARY: ThreadSanitizer: Swift access race <compiler-generated> in EventController.listeners.modify
==================
```
</details>

But wait, there's more!

This is the code in `MPVController.handlePropertyChange` that is handling listeners established by plugins:
<details>
<summary><b>handlePropertyChange:</b></summary>

```swift
    let eventName = EventController.Name("mpv.\(name).changed")
    if player.events.hasListener(for: eventName) {
      // FIXME: better convert to JSValue before passing to call()
      let data: Any
      switch property.format {
      case MPV_FORMAT_FLAG:
        data = property.data.bindMemory(to: Bool.self, capacity: 1).pointee
      case MPV_FORMAT_INT64:
        data = property.data.bindMemory(to: Int64.self, capacity: 1).pointee
      case MPV_FORMAT_DOUBLE:
        data = property.data.bindMemory(to: Double.self, capacity: 1).pointee
      case MPV_FORMAT_STRING:
        data = property.data.bindMemory(to: String.self, capacity: 1).pointee
      default:
        data = 0
      }
      player.events.emit(eventName, data: data)
    }
```
</details>

The `EventControllert` method being called is this:
<details>
<summary><b>EventController.emit:</b></summary>

```swift
  func emit(_ eventName: Name, data: Any...) {
    guard let listeners = listeners[eventName] else { return }
    for listener in listeners.values {
      listener.call(withArguments: data)
    }
  }
```
</details>

The `listener.call` statement is calling into the Java VM. That means the  dispatch queue `com.colliderli.iina.controller` that `MPVController` uses to process events from mpv is running plugin code.

### Fixing

There is more than one way to fix this. Two of the choices are:
- Restrict dictionary access to a single serial dispatch queue
- Single thread access to the dictionary using locks

Unless there is a good justification for accessing the data from multiple dispatch queues it is preferable to standardize access from a single serial dispatch queue and avoid using locks.

This is not the only data race caused by `MPVController` accessing data used by the main thread in tasks executed by its `com.colliderli.iina.controller` dispatch queue. Properties in `PlaybackInfo`  are being accessed that are also referenced by the main thread.

When possible it is desirable to encapsulate and decouple classes, especially lower level classes. The primary role of `MPVController` is to serve as IINA's interface to mpv. That makes it a low level class. If we were striving for decoupling then `MPVController` would post notifications rather than directly call the higher level classes. `PlayerCore` and `EventController` would register observers for the notifications from `MPVController` that might concern them. `MPVController` would not contain any references to these higher level classes. In such a scenario `MPVController` would definitely not use its own dispatch queue when posting notifications as it could not be assured that the observer does not do something that takes too long and interferes with processing events from mpv. `MPVController` would post the notification using the main thread. If the observer needs background processing then it would be up to that class to queue the work accordingly.

I'm not proposing doing such refactoring now. This is part of the justification for changing `MPVController` to queue more work to the main thread rather than adding locks to coordinate data access. The proposed fix I will be posting will take this approach rather than adding locks.

**Comment by low-batt** [comment] 2023-07-14 03:40
IINA 1.3.2 contains the fix for this issue.

**Closed by low-batt** 2023-07-14 03:40 UTC
Labels: progress: fixed/implemented, bug: crash, feature: plugin
