### ISSUE TITLE
play mov can't fast forward

### ISSUE THREAD

**Issue by songyizhang** [iina/iina#4620] opened 2023-09-19 06:54 UTC
**System and IINA version:**
- macOS 11.7.1
- IINA 1.3.3

**Expected behavior:**
Playing mov can fast forward normally.

**Actual behavior:**
Playing mov can't fast forward normally.

**Steps to reproduce:**
When play mov, press → and the video will play from the beginning.

**Comment by low-batt** [comment] 2023-09-19 18:07
Was the video that exhibits the problem taken on an iPhone? If so then I suspect this is a duplicate of issue #4502. Issue #4502 reports a problem where attempting to seek 5 seconds forwards ends up seeking backwards. This is a regression and a priority to fix, however the root cause of the problem is not in IINA code. IINA is waiting for the mpv project to provide a fix.

Does the behavior described in issue #4502 match the behavior you are experiencing?

**Comment by songyizhang** [comment] 2023-09-20 03:55
Yes. And I realize if I use exact seek, this condition will not happen.

**Comment by low-batt** [comment] 2023-09-20 22:16
The mpv defect has to do with relative seeking. That it works with an exact seek aligns with the known behavior of the mpv regression.

**Comment by uiryuu** [comment] 2024-06-22 00:31
Please track in #4502

**Closed as not planned** 2024-06-22 00:31 UTC
Labels: other: duplicate, upstream: mpv
