### ISSUE TITLE
Filter names truncated when adding filter

### ISSUE THREAD

**Issue by low-batt** [iina/iina#4894] opened 2024-04-26 20:36 UTC
**System and IINA version:**

- macOS 13.6.3
- IINA 1.3.4 + PR #4922

**Expected behavior:**
Filter names are not truncated.

**Actual behavior:**
PR #4922 enables Hebrew. If you build IINA with that pull request and set Hebrew as the language then the filter name for a custom FFmpeg filter is truncated in the sheet for adding a filter:
![he-filter](https://github.com/iina/iina/assets/86170219/9edd66c6-81a5-4d57-affe-d6d0f39d6823)

The table of filters should be automatically resized to adapt to the size of the filter names in other languages.

**NOTE** that this problem can also be reproduced using the `develop` branch and English. In Xcode open `FilterWindowController.xib`. Built and run IINA. The `Custom (FFmpeg)` filter name is now truncated:
![en-filter](https://github.com/iina/iina/assets/86170219/c923dd33-8914-4930-b844-23409874604c)

Digging through all the changes to the XIB Xcode helpfully adds even if you only open the file in the editor and don't make any changes I see:
```xml
- <tableColumn width="477" minWidth="40" maxWidth="1000" id="TbO-kN-XQm">
+ <tableColumn width="468" minWidth="40" maxWidth="1000" id="TbO-kN-XQm">
```

Xcode is messing with the width of table columns.

There are warning in the build log regarding layout problems:
```text
/* com.apple.ibtool.document.notices */
/Users/low-batt/Documents/builds/iina-official/iina/iina/Base.lproj/FilterWindowController.xib:MAd-sY-Hvg: note: NSTextField's height does not match its intrinsic content size, use "Size to Fit Content" to correct [22]
/Users/low-batt/Documents/builds/iina-official/iina/iina/Base.lproj/FilterWindowController.xib:cLl-pZ-KNW: note: View is clipping its content [13]
/Users/low-batt/Documents/builds/iina-official/iina/iina/Base.lproj/FilterWindowController.xib:ZJo-ef-lfp: note: View is clipping its content [13]
/Users/low-batt/Documents/builds/iina-official/iina/iina/Base.lproj/FilterWindowController.xib:56K-2H-lTw: note: View is clipping its content [13]
```

This problem was reported by @ShlomoCode in issue #4776. As that issue reports quite a few RTL related problems I have created this issue to focus just on this particular problem.

**Steps to reproduce:**
- Pull PR #4922
- Open the IINA project in Xcode 
- Under the `Product` menu open the `Scheme` menu and select `Edit Scheme…`  
- Click on the `Options` tab
- Scroll down to the `App Language` setting
- In the pull down select `Hebrew`
- Start IINA running under Xcode
- Click on  `Video Filters…` under the `Video` menu
- The `Video Filters` window appears
- Click on the `+` button
- The sheet for adding a filter appears
- Notice the last filter in the list is truncated

- [x] MPV does not have this problem.

mpv does not support localization.

**How often does this happen?**
Every time.

**Comment by low-batt** [comment] 2024-04-26 20:37
@svobs Would you be able to take this one?

**Comment by svobs** [comment] 2024-05-02 22:27
@low-batt Sure. Funny, I just refactored this dialog on my fork. I needed to rework most of the layout just to get the window to resize sanely. Should be straightforward to cut a PR.

**Comment by low-batt** [comment] 2024-05-03 00:14
Thanks! That would be great!

**Comment by low-batt** [comment] 2024-05-22 23:56
@svobs Just a little reminder on this one. We are planning on merging the RTL support and this is one of the RTL related issues.

**Comment by svobs** [comment] 2024-05-27 21:38
Duplicate of #1098.

**Closed as completed** 2024-05-28 10:33 UTC
Labels: bug, progress: fixed/implemented, feature: ui/ux, type: localization, priority: high
