### ISSUE TITLE
HDR display issue on second screen

### ISSUE THREAD

**Issue by avenius** [iina/iina#4700] opened 2023-11-27 03:08 UTC
On the internal screen of my macBook the HDR works perfect. But if I drag the player to an other display (also HDR capable and supported by macOS) the display gets really bad

- macOS Sonoma 14.1.1 (apple silicon)
- IINA 1.3.3

**Expected behavior:**
Equally display of videos on all displays

**Actual behavior:**
Display (HDR) only works on internal display correctly, on external display it seems to be like a dark gray dimming overlay

**Steps to reproduce:**

just drag a (HDR) clip to an external display

dont now if mpv got this problem, not using it.

**How often does this happen?**
always

**Comment by low-batt** [comment] 2023-11-27 22:00
Open the  	menu and click on the `About This Mac` menu item. What is listed under `Chip`? My MacBook Pro displays `Apple M1 Max`. If yours lists a `M2` or `M3` chip then it is likely this is a duplicate of issue #4312. To confirm this is issue #4312, try applying one of the two known workarounds:
- [Workaround Using Accessibility Zoom](https://github.com/iina/iina/issues/4312#issuecomment-1824775677)
- [Workaround Using Custom Crop](https://github.com/iina/iina/issues/4312#issuecomment-1493042536)

If the Mac uses a `M2` or `M3` chip and the problem disappears after applying one of those workaround then that confirms this is issue #4312.

The root cause of #4312 is suspected to be a macOS defect involving [OpenGL](https://www.opengl.org/). But that is just a working theory. At this time I lack the hardware needed to reproduce this problem. Last I checked with some of the other IINA developers they too had `M1` based Macs. Of course if this is indeed a macOS issue then Apple would need to fix the problem.

**Comment by avenius** [comment] 2023-11-27 22:52
Hi low-batt,
yes I got a M2 Max Chip

I tried both of the workarounds:

- Accessiblilty Zoom fixes the problem in windowed and fullscreen mode
- Custom Crop fixes the problem only in windowed mode.

So it seems it is a duplicate of #4312 

If you want to test something on a M2 Max chip tell me.
IINA build and runs in Xcode on my machine, but find this problem is a bit to much for me (and I just do iOS development)

**Comment by low-batt** [comment] 2023-11-27 23:59
I really appreciate the offer to run tests, but as you correctly indicated this is a non-trivial problem that would require a lot of iterative testing just to narrow down the root cause. Hard enough to do that locally. Very time consuming to try and do that by having a remote person constantly run tests. A significant demotivating factor is that it is very likely this will trace the root cause to macOS.

We are hoping that upon the next macOS release the problem will disappear. Unfortunately quite a few macOS releases have come out since this problem was identified. Some other graphics related macOS defects have been fixed, but this one lingers on.

The other hope is that the `mpv` project will add support for  [GPU Next](https://github.com/mpv-player/mpv/wiki/GPU-Next-vs-GPU) in `libmpv`. That would allow IINA to use [Metal](https://developer.apple.com/metal/), which we suspect would solve this issue.

The recent identification of the accessibility zoom workaround by @waydabber is an interesting development. Possibly a way to automatically apply a tiny amount of zoom could be developed as a temporary hackaround.

Anyway, at the moment I am totally overloaded and need to complete some of my half done IINA work.

**Closed as not planned** 2024-06-24 13:43 UTC
Labels: other: duplicate
