### ISSUE TITLE
list of currently open windows doesn't synch

### ISSUE THREAD

**Issue by GraOrigin** [iina/iina#3097] opened 2020-09-07 13:38 UTC
**System and IINA version:**

- macOS 10.15.6
- IINA 1.1.0-beta1 Build 121

**Expected behavior:**
If one two-finger-clicks on the IINA icon to list all open windows, it should reflect the current names of files open at that time

**Actual behavior:**
If one two-finger-clicks on the IINA icon, the list displayed is not up-to-date.

**Steps to reproduce:**
Open a video file in a folder with multiple files (all being incorporated into a playlist). As soon as the next video in line starts playing the list is not being kept up-to-date, resulting in wrong filenames being displayed.

**Comment by lhc70000** [comment] 2020-09-21 21:45
Sorry but I can't reproduce this issue. Do you mean that the window title showing in the context menu is incorrect? Could you provide more details such as screenshots?

Please note that the "list" at the top in the context menu is just a list of recently opened files, not currently opened windows. By default, IINA updates this list only if the file is opened manually. If you want IINA to add all files (including the ones played automatically in a playlist) to this list, there's a switch under Preferences - General - History.

**Comment by GraOrigin** [comment] 2020-10-04 11:36
@lhc70000 Here is the screenshot
<a href="https://ibb.co/G3V1WCF"><img src="https://i.ibb.co/qFR4Nmx/iina.png" alt="iina" border="0"></a>

I reckon the list above with the "IINA icon" is the recently opened files. 
The list with the "window icon" (with a checkmark in screenshot) is the currently open - which does not synch.
Meaning if I click on a title of those windows currently open, it may show a older filename that's closed already.

**Comment by low-batt** [comment] 2021-06-28 03:26
This same problem was reported again in issue #3159.

The window names are incorrect both in the IINA icon menu and the Window menu.
See my comment on #3159 for more details on the issue.

I have added a pull request with a proposed fix. I don't seem to have the required privileges to be able to link pull requests to issues.

**Comment by low-batt** [comment] 2022-04-30 19:05
The fix (a workaround) in PR #3435 has been merged into the develop branch.

Apple has fixed the AppKit defect in macOS Monterey.

See issue #3159 for details.

**Comment by low-batt** [comment] 2022-05-29 23:20
Closing. Fixed in IINA 1.3.0.

**Closed by low-batt** 2022-05-29 23:20 UTC
Labels: progress: fixed/implemented
