### ISSUE TITLE
Double clicking Does Not Reliably Toggle Full Screen Off and On If Using Legacy Full Screen

### ISSUE THREAD

**Issue by peterinjapan** [iina/iina#3661] opened 2022-03-10 06:47 UTC
On my Mac Mini M1, I've noticed that double clicking, which (coming from VLC, my preferred behavior) should toggle the screen to full screen, then back to a smaller window, when I double click repeatedly. However, in both Iina 1.2.0 build 129 mpv 033.0 and a fresh copy of mpv 0.32.0 I just downloaded, this does not work reliably, usually making the screen go full screen, then back to window, only one time each. I need to quit and reload the program if I need to back into full screen by double clicking.

Note that I have been using Use Legacy Full Screen. The problem seems to not happen when I turn off Use Legacy Full Screen and restart the computer. So it seems to be related to that. 

**System and IINA version:**

- macOS 
- M1 Mac Mini running the current Apple beta release of 12.3 (21E230)
- IINA 
- 1.2.0 build 129 mpv 033.0 and 0.32.0

**Expected behavior:**
I should be able to double click repeatedly into the window of a video playing, causing the video to go into full screen, then back down to window, then full screen, then window repeatedly.

**Actual behavior:**

The enlarge to full screen / reduce to window size only happens once each. After this time, I must quit the program to get this behavior back.

<details>
<summary><b>Crash report:</b></summary>

```
```
</details>

<br>

<details>
<summary><b>mpv log:</b></summary>

```
```
</details>

<br>

**Steps to reproduce:**

On a 

- [x] MPV does not have this problem.

**How often does this happen?**

It seems to happen all the time if I have Use Legacy Full Screen on on my M1 Mac Mini. It doesn't happen on my Intel iMac nor my Macbook Pro M1X with the same settings. 

![Screen Shot 2022-03-10 at 15 31 36](https://user-images.githubusercontent.com/34758336/157603011-3c70dd00-f1e8-4c09-b9bc-596bd7e5c02c.jpg)

![Screen Shot 2022-03-10 at 15 31 56](https://user-images.githubusercontent.com/34758336/157604926-8c85e0a2-5e6f-4356-bf49-2de3bffb1095.jpg)

**Comment by low-batt** [comment] 2022-03-10 14:33
The behavior described matches issue #3211.

Changes in macOS 11 broke the legacy full screen feature requiring the implementation of that feature to change. The new implementation required for macOS 11+ has resulted in problems due to defects in AppKit. The issue with double click working for one cycle when using legacy full screen is due to AppKit stopping to deliver mouse up events to IINA. This has been reproduced in a small test program and reported to Apple. Apple has not yet responded. A workaround in the IINA code has been proposed and is waiting to be reviewed and merged.

Most of the time users do not notice this issue with double clicking because under macOS 11+ when legacy full screen is enabled IINA usually crashes. This is due to another AppKit issue that also was reported to Apple. A workaround has been merged and will be available in the next IINA release. This AppKit issue has been fixed in the latest 12.3 Beta so that workaround will only be needed for macOS 11 - 12.2.

**Comment by varenc** [comment] 2022-04-22 00:20
I'm also dealing with this issue but I'm currently on macOS 12.3.1 where ostensibly the underlying problem is fixed.  This is when compiling the latest code from the *develop* branch which has the legacy fullscreen fixes.

However I discovered that the latest version of the [iina-plus](https://github.com/iina-plus/iina) fork doesn't have this problem.   @low-batt any chance you know the commit/code makes double-click work on iina-plus?

**Comment by low-batt** [comment] 2022-04-22 03:39
See PR #3614
Still waiting to be reviewed and merged.
I view this as a workaround. This seems like an AppKit defect to me. I have reported it to Apple. No response as of yet.
There are multiple legacy full screen issues.
It is the AppKit related crash in issue #3543 that seems to be fixed in macOS 12.3.

**Comment by varenc** [comment] 2022-04-27 20:21
thank you! Also looks like #3614 was just recently merged so this issue can be closed?  Psyched to see IINA getting some of your PRs merged.

**Comment by low-batt** [comment] 2022-04-27 22:03
Not sure of the dev team's policy about when an issue can be closed.
Whether or not they keep it open until the fix is available in a public release...
I'll see if I can find out.
There is a "progress: fixed/implemented" label that should be applied.
I suspect I don't have the privileges required to be able to do that.
I am keeping track of the status of issues I've been involved in.

And yes, the good news is that more progress is being made on reviewing and merging open PRs.
That work continues.

**Comment by eks28** [comment] 2022-04-28 00:28
For me it works but when I click bar it doesnt change time or scrub time so help please

**Comment by eks28** [comment] 2022-04-28 00:51
Works kinda as-in I can get full screen view but can't seek in legacy full screen

**Comment by lhc70000** [comment] 2022-04-28 06:50
@low-batt Yes, to avoid duplicated issues, the issue should be closed after the fix is shipped; and in the meantime, we use the progress: fixed/implemented label. As an org member, you should be able to add labels and please feel free to do so.

**Comment by low-batt** [comment] 2022-05-29 23:08
Closing. Fixed in IINA 1.3.0.

**Closed by low-batt** 2022-05-29 23:08 UTC
Labels: progress: fixed/implemented
