### ISSUE TITLE
application not responding open file in fullscreen

### ISSUE THREAD

**Issue by frimin** [iina/iina#2221] opened 2019-01-15 15:26 UTC
- MacBook (Retina, 12-inch, 2017) macOS MoJave 10.14
- IINA 1.0.1 Build 103

In this case, IINA is playing a video in fullscreen, then open same video (or different) can show this problem. (IINA not crash)

![dongtu](https://user-images.githubusercontent.com/6148936/51189505-26f65500-191b-11e9-90ed-0354c2fea9fa.gif)

Steps:
1. open any video
2. double click to full screen
3. change to main desktop (control + <-)
4. open same video
5. desktop switch to IINA fullscreen (automatically)
6. **IINA not responding** 

------

在全屏模式下打开 IINA 时，滑切到另外的桌面点开其它文件时（不管是不是同一个文件） IINA会无响应（但并未崩溃）

**Comment by lhc70000** [comment] 2019-01-15 15:35
Sorry but I can't reproduce this issue. Could you provide detailed steps if you can reproduce it stably?

**Comment by frimin** [comment] 2019-01-15 15:49
> Sorry but I can't reproduce this issue. Could you provide detailed steps if you can reproduce it stably?

This problem is only happend in my MacBook(12-inch), working properly in MacBook Pro (2015; 12-inch; macOS High Sierra 10.13.6).

**Comment by frimin** [comment] 2019-01-15 16:11
I got a crash message when I kill program:
[iina.txt](https://github.com/iina/iina/files/2760416/iina.txt)

**Comment by owenzhao** [comment] 2019-01-20 07:31
The same here. It is easy to reproduce by:

1. in finder, double click to open a video
2. press f to full screen
3. press q to quit
4. open the same video

iina will open the video with full screen mode at the last played time, however everything hangs. 

Here is my screenshot when crashing. 

[![kCOIPg.md.png](https://s2.ax1x.com/2019/01/20/kCOIPg.md.png)](https://imgchr.com/i/kCOIPg)

version 1.0.1 Build 103

**Comment by xjbeta** [comment] 2019-03-13 11:54
This bug is caused by this commit.
https://github.com/iina/iina/commit/c25ef55781676d0407ea0a754dc16432859c9cc8

**Comment by Noctem** [comment] 2019-04-12 05:20
Disabling "Resume last playback position" in Preferences prevents these crashes for me.

**Comment by dalDevelo** [comment] 2019-04-14 10:14
I'm also having application hangs when using IINA in fullscreen and switching between desktop spaces. However, I am unable to reliably replicate the hang. I'm also unable to replicate using the steps mentioned above. I will post an update here as and when I can reliably replicate on my system.

MacBook Pro (Retina, 15-inch, 2015) macOS Mojave 10.14.4
IINA 1.0.3 Build 106

**Comment by Noctem** [comment] 2019-04-15 08:03
@dalDevelo It's weirdly inconsistent for me too. Sometimes I can reliably trigger it by following the procedure @owenzhao listed, but then later (like after a reboot or switching accounts) it stops doing it consistently. I can't recall if when I was in one of those reliably reproduce states if it worked for every file or only some.

Have you tried disabling "resume last playback position"? As I mentioned, that completely eliminates the problem for me, albeit at the cost of losing the previous playback time (sometimes inconvenient) and window position (don't personally care about).

**Comment by Noctem** [comment] 2019-04-15 08:25
Here's a stack trace from the last hang (on April 11th, since I've had "resume last playback position" disabled since then). 
```
  16  start + 1 (libdyld.dylib + 91093) [0x7fff62cf13d5]
  16  main + 9 (AppDelegate.swift:22,7 in IINA + 31929) [0x109c06cb9]
  16  NSApplicationMain + 777 (AppKit + 13296) [0x7fff33e3f3f0]
  16  -[NSApplication run] + 699 (AppKit + 81584) [0x7fff33e4feb0]
  16  -[NSApplication(NSEvent) _nextEventMatchingEventMask:untilDate:inMode:dequeue:] + 1361 (AppKit + 105875) [0x7fff33e55d93]
  16  _DPSNextEvent + 965 (AppKit + 110587) [0x7fff33e56ffb]
  16  _BlockUntilNextEventMatchingListInModeWithFilter + 64 (HIToolbox + 42150) [0x7fff35abc4a6]
  16  ReceiveNextEventCommon + 603 (HIToolbox + 42773) [0x7fff35abc715]
  16  RunCurrentEventLoopInMode + 292 (HIToolbox + 43483) [0x7fff35abc9db]
  16  CFRunLoopRunSpecific + 459 (CoreFoundation + 237701) [0x7fff367de085]
  16  __CFRunLoopRun + 2141 (CoreFoundation + 240436) [0x7fff367deb34]
  16  __CFRunLoopDoTimers + 330 (CoreFoundation + 365818) [0x7fff367fd4fa]
  16  __CFRunLoopDoTimer + 864 (CoreFoundation + 367041) [0x7fff367fd9c1]
  16  __CFRUNLOOP_IS_CALLING_OUT_TO_A_TIMER_CALLBACK_FUNCTION__ + 20 (CoreFoundation + 368149) [0x7fff367fde15]
  16  ___NSMainRunLoopPerformBlockAfterDelay_block_invoke + 25 (AppKit + 10156197) [0x7fff347eb8a5]
  16  -[_NSEnterFullScreenTransitionController _performFinalTransitionCleanup] + 68 (AppKit + 10149736) [0x7fff347e9f68]
  16  -[_NSWindowEnterFullScreenTransitionController doAfterEnterFullScreen] + 65 (AppKit + 5800069) [0x7fff343c4085]
  16  -[NSWindow(NSFullScreen) _didEnterFullScreen] + 118 (AppKit + 11817300) [0x7fff34981154]
  16  -[NSNotificationCenter postNotificationName:object:userInfo:] + 66 (Foundation + 74263) [0x7fff38a48217]
  16  _CFXNotificationPost + 840 (CoreFoundation + 57191) [0x7fff367b1f67]
  16  -[_CFXNotificationRegistrar find:object:observer:enumerator:] + 1834 (CoreFoundation + 60604) [0x7fff367b2cbc]
  16  ___CFXNotificationPost_block_invoke + 87 (CoreFoundation + 678893) [0x7fff36849bed]
  16  _CFXRegistrationPost + 404 (CoreFoundation + 645054) [0x7fff368417be]
  16  ___CFXRegistrationPost_block_invoke + 63 (CoreFoundation + 645204) [0x7fff36841854]
  16  __CFNOTIFICATIONCENTER_IS_CALLING_OUT_TO_AN_OBSERVER__ + 12 (CoreFoundation + 645338) [0x7fff368418da]
  16  @objc MainWindowController.windowWillClose(_:) + 99 (IINA + 819139) [0x109cc6fc3]
  16  MainWindowController.windowDidEnterFullScreen(_:) + 117 (<compiler-generated> in IINA + 801589) [0x109cc2b35]
  16  specialized MainWindowController.fsState.didset + 370 (MPVController.swift:412,5 in IINA + 910754) [0x109cdd5a2]
  16  mpv_set_property + 90 (libmpv.1.101.0.dylib + 459882) [0x10aaa046a]
  16  mp_dispatch_lock + 201 (libmpv.1.101.0.dylib + 367097) [0x10aa899f9]
  16  __psynch_cvwait + 10 (libsystem_kernel.dylib + 18538) [0x7fff62e2986a]
 *16  psynch_cvcontinue + 0 (pthread + 19324) [0xffffff7f838e9b7c]
```
That was built from [this commit](https://github.com/Noctem/iina/tree/68ce644142d09ccd6c4784c9a2dab76393e6f121) if you want to follow the line numbers.

I investigated a bit a few days ago and it looked to me like there is likely some issue with either suspending/resuming `videoLayer` or locking/unlocking `uninitLock` when restoring playback states, but I didn't have enough time or familiarity with IINA/mpv's codebases to determine what exactly that problem is.

**Comment by saagarjha** [comment] 2019-04-15 08:27
This looks like a deadlock to me. Do you have a full sample (that is, with all the threads) so we can see which threads are deadlocked?

**Comment by Noctem** [comment] 2019-04-15 23:49
@saagarjha Yes, [here are all the threads for IINA](https://gist.github.com/Noctem/09236b2eba30f2512fa97603b829df87). If you need the full report I can email it to you but would prefer to not provide those details about the state of my system publicly.

**Comment by dalDevelo** [comment] 2019-04-16 09:04
@Noctem I can confirm that disabling "resume last playback position" fixes the issue, or at least I didn't have any hangs yesterday 👍🏼

**Comment by jnpatrick99** [comment] 2019-06-30 21:55
I experience this all the time! Good to find it on Github. Stopped updating IINA after beta version because all 1.0.X versions don't work when opening new files.

Do you guys fix the bugs reported by users here?

**Comment by alejx** [comment] 2020-01-06 08:21
Temporarily fixed by disabling advanced rendering.

**Closed** 2020-01-10 06:08 UTC
Labels: bug, progress: fixed/implemented
