### ISSUE TITLE
continue an mp4 when it fullscreen

### ISSUE THREAD

**Issue by chenruisilalala** [iina/iina#2448] opened 2019-05-09 13:26 UTC
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/33834625/57456645-826c9a00-72a0-11e9-86b8-3a2b190d9865.png">
[log.txt](https://github.com/iina/iina/files/3162320/log.txt)

**Comment by alejx** [comment] 2019-05-09 19:58
Duplicate of #2221

**Closed by alejx** 2019-05-09 19:58 UTC
Labels: other: duplicate
