### ISSUE TITLE
Feature Request: IINA App Store Version

### ISSUE THREAD

**Issue by bigplayer-ai** [iina/iina#5138] opened 2024-08-14 14:01 UTC
**Feature Request: IINA App Store Version**

**Requested Feature:**
Could you make IINA available on the App Store?

**Current Status:**
IINA is currently available on GitHub.

**Reason for Request:**
Many users prefer sandboxed applications available through the App Store for added security and ease of installation. Are there any updates on this? 

**Examples from Other Projects:**
[Include relevant examples of similar projects with App Store availability.]

**Comment by low-batt** [comment] 2024-08-14 19:35
I was going to inform you that this is a duplicate of issue #2152, but I see you have found that issue. We should continue the discussion in #2152.

**Closed as completed by low-batt** 2024-08-14 19:35 UTC
Labels: other: duplicate
