### ISSUE TITLE
Add option to enable Do not Disturb when going full screen

### ISSUE THREAD

**Issue by Stanzilla** [iina/iina#2786] opened 2020-02-25 21:38 UTC
**What you want IINA to do:**
I want it to automatically enable/disable the macOS DnD mode when entering or leaving fullscreen

**What IINA does currently:**

**Why you think this should be added:**
- I don't want to get interrupted while watching movies

**Examples of other projects that have something similar:**

- MPC-HC
- VLC

**Comment by alejx** [comment] 2020-02-28 04:54
Info: https://stackoverflow.com/questions/25210120/is-it-possible-to-turn-on-off-do-not-disturb-for-os-x-programmatically

**Comment by megadr01d** [comment] 2020-03-05 20:17
Declined duplicate of https://github.com/iina/iina/issues/1368.

**Comment by Stanzilla** [comment] 2020-03-05 20:24
Oh I did not see that, I hope this gets reconsidered.

**Closed** 2020-03-06 19:12 UTC
Labels: other: duplicate, type: feature request
