### ISSUE TITLE
A white line flashes at the top

### ISSUE THREAD

**Issue by zhaoleihello** [iina/iina#3114] opened 2020-09-20 06:44 UTC
**System and IINA version:**

- macOS 11 developer beta 7 
- IINA 1.1.0 beta1(121) 

**Actual behavior:**
When the video is played in full screen, a white line flashes at the top every second.

**How often does this happen?**
Will appear once every second.

**Comment by lhc70000** [comment] 2020-09-21 22:26
Duplicate of #3104.

**Closed by lhc70000** 2020-09-21 22:26 UTC
